// packages/vue/src/components/complex/Form/FormList.vue
<script setup lang="ts">
import { computed, inject, onMounted, ref, watch } from 'vue'
import { formContextKey } from './context'
import type { FormListOperation } from '@skygraph/core'

let listUid = 0
function genKey(): string {
  return `fl_${++listUid}`
}

export interface FormListField {
  /** Stable key for v-for reconciliation. */
  key: string
  /** Zero-based index in the list value array. */
  index: number
}

export interface FormListProps {
  /** Field path in the form store holding the array value. */
  name: string
  /** Seeds the store when the path is unset on first mount. */
  initialValue?: unknown[]
}

const props = defineProps<FormListProps>()

defineSlots<{
  default(props: {
    fields: FormListField[]
    operation: FormListOperation
    meta: { errors: string[] }
  }): unknown
}>()

const injected = inject(formContextKey, null)
if (!injected) {
  throw new Error('[skygraph/vue] <SgFormList> must be used inside an <SgForm>')
}
const ctx = injected

onMounted(() => {
  if (props.initialValue && !Array.isArray(ctx.core.get(props.name))) {
    ctx.core.set(props.name, props.initialValue)
  }
})

const items = ref<unknown[]>(
  Array.isArray(ctx.core.get(props.name)) ? (ctx.core.get(props.name) as unknown[]) : [],
)
const keys = ref<string[]>(items.value.map(() => genKey()))

const unsub = ctx.core.subscribe(props.name, (v) => {
  const arr = Array.isArray(v) ? v : []
  items.value = arr
})

watch(items, (newItems) => {
  if (newItems.length > keys.value.length) {
    const diff = newItems.length - keys.value.length
    keys.value = [...keys.value, ...Array.from({ length: diff }, () => genKey())]
  } else if (newItems.length < keys.value.length) {
    keys.value = keys.value.slice(0, newItems.length)
  }
})

const fields = computed<FormListField[]>(() =>
  keys.value.slice(0, items.value.length).map((key, index) => ({ key, index })),
)

const add = (defaultValue?: unknown, insertIndex?: number) => {
  ctx.form.listAdd(props.name, defaultValue, insertIndex)
  const k = genKey()
  if (insertIndex !== undefined && insertIndex >= 0 && insertIndex <= keys.value.length) {
    const next = [...keys.value]
    next.splice(insertIndex, 0, k)
    keys.value = next
  } else {
    keys.value = [...keys.value, k]
  }
}

const remove = (index: number | number[]) => {
  ctx.form.listRemove(props.name, index)
  if (Array.isArray(index)) {
    const indices = new Set(index)
    keys.value = keys.value.filter((_, i) => !indices.has(i))
  } else {
    keys.value = keys.value.filter((_, i) => i !== index)
  }
}

const move = (from: number, to: number) => {
  ctx.form.listMove(props.name, from, to)
  const next = [...keys.value]
  const [item] = next.splice(from, 1)
  next.splice(to, 0, item)
  keys.value = next
}

const replace = (values: unknown[]) => {
  ctx.form.listReplace(props.name, values)
  keys.value = values.map(() => genKey())
}

const operation: FormListOperation = { add, remove, move, replace }

const meta = computed(() => ({ errors: ctx.form.getFieldErrors(props.name) }))

import { onBeforeUnmount } from 'vue'
onBeforeUnmount(() => unsub())
</script>

<template>
  <slot :fields="fields" :operation="operation" :meta="meta" />
</template>

// packages/react/src/components/complex/FormList.tsx
import React, { useState, useCallback, useMemo, useRef } from 'react'
import { useFormContext } from './FormContext'
import { useWatch } from '../../hooks/useWatch'
import type { FormListOperation } from '@skygraph/core'

let listUid = 0
function genKey(): string {
  return `fl_${++listUid}`
}

/** Stable identity and position of one row in a {@link FormList}. */
export interface FormListField {
  /** Stable React key for list reconciliation. */
  key: string
  /** Zero-based index in the list value array. */
  index: number
}

/** Props for a dynamic array field bound to form state. */
export interface FormListProps {
  /** Field path in the form store holding the array value. */
  name: string
  /** Seeds the store when the path is unset on first mount. */
  initialValue?: unknown[]
  /** When `true`, each row receives `dragProps` for HTML5 drag-and-drop reordering. */
  draggable?: boolean
  /** Render function receiving fields, list operations, and validation meta. */
  children: (
    fields: FormListField[],
    operation: FormListOperation,
    meta: { errors: string[] },
  ) => React.ReactNode
}

/**
 * Manages an array at `name` with stable keys, add/remove/move/replace helpers,
 * and optional drag reordering when `draggable` is enabled.
 */
export function FormList({ name, initialValue, draggable, children }: FormListProps) {
  const { core, form } = useFormContext()

  React.useEffect(() => {
    if (initialValue && !Array.isArray(core.get(name))) {
      core.set(name, initialValue)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const listValue = useWatch(core, name)
  const items = Array.isArray(listValue) ? listValue : []

  const [keys, setKeys] = useState<string[]>(() => items.map(() => genKey()))

  React.useEffect(() => {
    setKeys((prev) => {
      if (prev.length === items.length) return prev
      if (items.length > prev.length) {
        return [...prev, ...Array.from({ length: items.length - prev.length }, () => genKey())]
      }
      return prev.slice(0, items.length)
    })
  }, [items.length])

  const fields = useMemo(
    () => keys.slice(0, items.length).map((key, index) => ({ key, index })),
    [keys, items.length],
  )

  const add = useCallback(
    (defaultValue?: unknown, insertIndex?: number) => {
      form.listAdd(name, defaultValue, insertIndex)
      setKeys((prev) => {
        const k = genKey()
        if (insertIndex !== undefined && insertIndex >= 0 && insertIndex <= prev.length) {
          const next = [...prev]
          next.splice(insertIndex, 0, k)
          return next
        }
        return [...prev, k]
      })
    },
    [form, name],
  )

  const remove = useCallback(
    (index: number | number[]) => {
      form.listRemove(name, index)
      setKeys((prev) => {
        if (Array.isArray(index)) {
          const indices = new Set(index)
          return prev.filter((_, i) => !indices.has(i))
        }
        return prev.filter((_, i) => i !== index)
      })
    },
    [form, name],
  )

  const move = useCallback(
    (from: number, to: number) => {
      form.listMove(name, from, to)
      setKeys((prev) => {
        const next = [...prev]
        const [item] = next.splice(from, 1)
        next.splice(to, 0, item)
        return next
      })
    },
    [form, name],
  )

  const replace = useCallback(
    (values: unknown[]) => {
      form.listReplace(name, values)
      setKeys(values.map(() => genKey()))
    },
    [form, name],
  )

  const operation: FormListOperation = useMemo(
    () => ({ add, remove, move, replace }),
    [add, remove, move, replace],
  )

  const meta = useMemo(() => ({ errors: form.getFieldErrors(name) }), [form, name])

  // Drag reorder support
  const dragIdx = useRef<number>(-1)
  const dragOverIdx = useRef<number>(-1)

  if (!draggable) {
    return <>{children(fields, operation, meta)}</>
  }

  const dragFields = fields.map((f) => ({
    ...f,
    dragProps: {
      draggable: true,
      onDragStart: () => {
        dragIdx.current = f.index
      },
      onDragOver: (e: React.DragEvent) => {
        e.preventDefault()
        dragOverIdx.current = f.index
      },
      onDrop: () => {
        if (dragIdx.current !== -1 && dragOverIdx.current !== -1 && dragIdx.current !== dragOverIdx.current) {
          move(dragIdx.current, dragOverIdx.current)
        }
        dragIdx.current = -1
        dragOverIdx.current = -1
      },
      onDragEnd: () => {
        dragIdx.current = -1
        dragOverIdx.current = -1
      },
    },
  }))

  return <>{children(dragFields, operation, meta)}</>
}
