// packages/react/src/components/complex/Charts/ChartLegend.tsx
import type { CSSProperties } from 'react'
import { colorForSeries } from './types'
import type { ChartSeries } from './types'
import { useConfig } from '../../ConfigProvider'

export interface ChartLegendProps {
  series: readonly ChartSeries[]
  className?: string
  style?: CSSProperties
}

/**
 * Minimal horizontal legend for charts. Renders below the SVG with one
 * `<span>` per series (colored swatch + label).
 */
export function ChartLegend({ series, className, style }: ChartLegendProps) {
  const chartsLocale = useConfig().locale?.charts
  return (
    <div
      className={['sg-chart-legend', className].filter(Boolean).join(' ')}
      role="list"
      aria-label={chartsLocale?.legend ?? 'Chart legend'}
      style={style}
    >
      {series.map((s, i) => (
        <span key={s.id} role="listitem" className="sg-chart-legend-item">
          <span
            aria-hidden="true"
            className="sg-chart-legend-swatch"
            style={{ background: colorForSeries(s, i) }}
          />
          {s.label}
        </span>
      ))}
    </div>
  )
}

// packages/vue/src/components/complex/Charts/ChartLegend.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useConfig } from '../../ui/ConfigProvider.vue'
import { colorForSeries, type ChartSeries } from './types'

interface Props {
  series: readonly ChartSeries[]
  unstyled?: boolean
  className?: string
}

const props = withDefaults(defineProps<Props>(), { unstyled: false })

const items = computed(() =>
  props.series.map((s, i) => ({ id: s.id, label: s.label, color: colorForSeries(s, i) })),
)

const cfg = useConfig()
const legendLabel = computed(() => cfg.value.locale?.charts?.legend ?? 'Chart legend')
</script>

<template>
  <div
    :class="[!props.unstyled && 'sg-chart-legend', props.className]"
    role="list"
    :aria-label="legendLabel"
  >
    <span
      v-for="item in items"
      :key="item.id"
      class="sg-chart-legend-item"
      role="listitem"
      :data-series-id="item.id"
    >
      <span class="sg-chart-legend-swatch" :style="{ background: item.color }" />
      <span class="sg-chart-legend-label">{{ item.label }}</span>
    </span>
  </div>
</template>
