// packages/react/src/components/complex/Charts/ChartAxes.tsx
import { Fragment } from 'react'
import type { ChartCategory, XAxisOptions, YAxisOptions } from './types'

/**
 * Internal helper — renders X and / or Y axes on top of an existing chart
 * SVG. Stays a pure presentational component (no hooks, no state) so it can
 * be used inside Line / Bar / Area without affecting their existing layout.
 *
 * Both `xAxis` and `yAxis` are optional; if neither is provided the
 * component renders nothing (preserves the v0 "no chrome" look).
 *
 * Coordinates are in the parent SVG's user space:
 *   - `(plotX, plotY)` is the top-left corner of the plot area.
 *   - `plotW` / `plotH` are the plot dimensions in pixels.
 *   - `min` / `max` bound the numeric Y range that the plot maps to.
 *
 * `xPositions` is optional: when provided it overrides the default
 * "evenly-spaced" placement (used by Line / Area). BarChart passes its own
 * group centres so ticks align with the visual middle of each bar group.
 */
export interface ChartAxesProps {
  /** Top-left X of the plot area. */
  plotX: number
  /** Top-left Y of the plot area. */
  plotY: number
  /** Plot area width in pixels. */
  plotW: number
  /** Plot area height in pixels. */
  plotH: number
  /** Lower bound of the numeric Y range. */
  min: number
  /** Upper bound of the numeric Y range. */
  max: number
  /** X-axis categories. Used to label ticks. */
  categories: readonly ChartCategory[]
  /**
   * Optional explicit X position per category (in plot coordinates). When
   * omitted, ticks are placed evenly: `plotX + i * plotW / (n - 1)`.
   */
  xPositions?: readonly number[]
  /** X-axis configuration. Omit to skip the X axis entirely. */
  xAxis?: XAxisOptions
  /** Y-axis configuration. Omit to skip the Y axis entirely. */
  yAxis?: YAxisOptions
  /** Drop default `sg-chart-axis-*` class names. */
  unstyled?: boolean
}

const DEFAULT_Y_TICKS = 5
const TICK_LEN = 4
const TICK_LABEL_GAP = 6

function defaultYFormatter(value: number): string {
  if (Number.isInteger(value)) return String(value)
  if (Math.abs(value) >= 1000) return value.toFixed(0)
  if (Math.abs(value) >= 1) return value.toFixed(2).replace(/\.?0+$/, '')
  return value.toFixed(2)
}

function pickXIndices(total: number, tickCount: number | undefined): number[] {
  if (total <= 0) return []
  if (tickCount === undefined || tickCount >= total) {
    return Array.from({ length: total }, (_, i) => i)
  }
  const k = Math.max(2, tickCount)
  const step = total - 1
  const seen = new Set<number>()
  const out: number[] = []
  for (let i = 0; i < k; i++) {
    const idx = Math.round((i / (k - 1)) * step)
    if (!seen.has(idx)) {
      seen.add(idx)
      out.push(idx)
    }
  }
  return out
}

export function ChartAxes({
  plotX,
  plotY,
  plotW,
  plotH,
  min,
  max,
  categories,
  xPositions,
  xAxis,
  yAxis,
  unstyled = false,
}: ChartAxesProps) {
  if (!xAxis && !yAxis) return null

  const yTickCount = Math.max(2, yAxis?.tickCount ?? DEFAULT_Y_TICKS)
  const range = max - min || 1
  const yTicks: { value: number; y: number }[] = []
  if (yAxis) {
    for (let i = 0; i < yTickCount; i++) {
      const t = i / (yTickCount - 1)
      const value = min + t * range
      const y = plotY + plotH - t * plotH
      yTicks.push({ value, y })
    }
  }

  const categoryCount = categories.length
  const defaultXFor = (i: number) =>
    categoryCount > 1 ? plotX + (i / (categoryCount - 1)) * plotW : plotX + plotW / 2
  const xFor = (i: number) => xPositions?.[i] ?? defaultXFor(i)

  const xIndices = xAxis ? pickXIndices(categoryCount, xAxis.tickCount) : []

  const yFmt = yAxis?.tickFormatter ?? defaultYFormatter
  const xFmt = xAxis?.tickFormatter

  const cls = (suffix: string) => (unstyled ? undefined : `sg-chart-axis-${suffix}`)

  return (
    <g
      className={unstyled ? undefined : 'sg-chart-axis'}
      data-sg-chart-axes=""
      pointerEvents="none"
    >
      {yAxis?.gridLines &&
        yTicks.map((t, i) => (
          <line
            key={`yg-${i}`}
            className={cls('grid')}
            data-sg-axis-grid=""
            x1={plotX}
            x2={plotX + plotW}
            y1={t.y}
            y2={t.y}
            stroke="var(--sg-color-border-secondary, var(--sg-color-border))"
            strokeWidth={1}
            strokeDasharray="2 2"
          />
        ))}

      {yAxis && (
        <g className={cls('y')} data-sg-axis="y">
          <line
            x1={plotX}
            x2={plotX}
            y1={plotY}
            y2={plotY + plotH}
            stroke="var(--sg-color-border)"
            strokeWidth={1}
          />
          {yTicks.map((t, i) => (
            <Fragment key={`yt-${i}`}>
              <line
                className={cls('tick')}
                data-sg-axis-tick="y"
                x1={plotX - TICK_LEN}
                x2={plotX}
                y1={t.y}
                y2={t.y}
                stroke="var(--sg-color-border)"
                strokeWidth={1}
              />
              <text
                className={cls('tick-label')}
                data-sg-axis-tick-label="y"
                x={plotX - TICK_LEN - TICK_LABEL_GAP}
                y={t.y}
                fontSize={11}
                fill="var(--sg-color-text-secondary)"
                textAnchor="end"
                dominantBaseline="central"
              >
                {yFmt(t.value)}
              </text>
            </Fragment>
          ))}
          {yAxis.label && (
            <text
              className={cls('label')}
              data-sg-axis-label="y"
              fontSize={11}
              fontWeight={600}
              fill="var(--sg-color-text)"
              textAnchor="middle"
              dominantBaseline="hanging"
              transform={`translate(2, ${plotY + plotH / 2}) rotate(-90)`}
            >
              {yAxis.label}
            </text>
          )}
        </g>
      )}

      {xAxis && categoryCount > 0 && (
        <g className={cls('x')} data-sg-axis="x">
          <line
            x1={plotX}
            x2={plotX + plotW}
            y1={plotY + plotH}
            y2={plotY + plotH}
            stroke="var(--sg-color-border)"
            strokeWidth={1}
          />
          {xIndices.map((idx) => {
            const cx = xFor(idx)
            const cat = categories[idx]!
            const text = xFmt ? xFmt(cat, idx) : String(cat)
            return (
              <Fragment key={`xt-${idx}`}>
                <line
                  className={cls('tick')}
                  data-sg-axis-tick="x"
                  x1={cx}
                  x2={cx}
                  y1={plotY + plotH}
                  y2={plotY + plotH + TICK_LEN}
                  stroke="var(--sg-color-border)"
                  strokeWidth={1}
                />
                <text
                  className={cls('tick-label')}
                  data-sg-axis-tick-label="x"
                  x={cx}
                  y={plotY + plotH + TICK_LEN + TICK_LABEL_GAP}
                  fontSize={11}
                  fill="var(--sg-color-text-secondary)"
                  textAnchor="middle"
                  dominantBaseline="hanging"
                >
                  {text}
                </text>
              </Fragment>
            )
          })}
          {xAxis.label && (
            <text
              className={cls('label')}
              data-sg-axis-label="x"
              x={plotX + plotW / 2}
              y={plotY + plotH + TICK_LEN + TICK_LABEL_GAP + 14}
              fontSize={11}
              fontWeight={600}
              fill="var(--sg-color-text)"
              textAnchor="middle"
              dominantBaseline="hanging"
            >
              {xAxis.label}
            </text>
          )}
        </g>
      )}
    </g>
  )
}

// packages/vue/src/components/complex/Charts/ChartAxes.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { ChartCategory, XAxisOptions, YAxisOptions } from './types'

interface Props {
  /** Plot-area top-left X in user space. */
  x: number
  /** Plot-area top-left Y in user space. */
  y: number
  /** Plot-area width. */
  plotW: number
  /** Plot-area height. */
  plotH: number
  categories: readonly ChartCategory[]
  /** Min/max for the Y axis. */
  yMin: number
  yMax: number
  xAxis?: XAxisOptions
  yAxis?: YAxisOptions
  unstyled?: boolean
}

const props = withDefaults(defineProps<Props>(), { unstyled: false })

function defaultYFormatter(value: number): string {
  if (Number.isInteger(value)) return String(value)
  if (Math.abs(value) >= 1000) return value.toFixed(0)
  if (Math.abs(value) >= 1) return value.toFixed(2).replace(/\.?0+$/, '')
  return value.toFixed(2)
}

const formatY = (v: number) =>
  props.yAxis?.tickFormatter ? props.yAxis.tickFormatter(v) : defaultYFormatter(v)

const formatX = (c: ChartCategory, i: number) =>
  props.xAxis?.tickFormatter ? props.xAxis.tickFormatter(c, i) : String(c)

const yTicks = computed(() => {
  const count = Math.max(2, props.yAxis?.tickCount ?? 5)
  const arr: { value: number; y: number }[] = []
  for (let i = 0; i < count; i++) {
    const t = i / (count - 1)
    const value = props.yMin + (props.yMax - props.yMin) * (1 - t)
    arr.push({ value, y: props.y + props.plotH * t })
  }
  return arr
})

const xTicks = computed(() => {
  if (props.categories.length === 0) return []
  const tickCount = Math.min(
    props.categories.length,
    Math.max(2, props.xAxis?.tickCount ?? props.categories.length),
  )
  const arr: { label: string; x: number }[] = []
  for (let i = 0; i < tickCount; i++) {
    const idx =
      tickCount === 1 ? 0 : Math.round((i * (props.categories.length - 1)) / (tickCount - 1))
    const t = props.categories.length === 1 ? 0 : idx / (props.categories.length - 1)
    arr.push({
      label: formatX(props.categories[idx], idx),
      x: props.x + props.plotW * t,
    })
  }
  return arr
})
</script>

<template>
  <g :class="!props.unstyled && 'sg-chart-axes'">
    <g v-if="props.yAxis" class="sg-chart-axis sg-chart-axis-y">
      <line
        v-for="(t, i) in yTicks"
        :key="`yg-${i}`"
        v-show="props.yAxis?.gridLines"
        :x1="props.x"
        :y1="t.y"
        :x2="props.x + props.plotW"
        :y2="t.y"
        class="sg-chart-axis-grid"
        stroke="currentColor"
        stroke-opacity="0.1"
        vector-effect="non-scaling-stroke"
      />
      <text
        v-for="(t, i) in yTicks"
        :key="`yt-${i}`"
        :x="props.x - 6"
        :y="t.y + 4"
        text-anchor="end"
        class="sg-chart-axis-label"
        font-size="10"
        fill="currentColor"
      >
        {{ formatY(t.value) }}
      </text>
      <text
        v-if="props.yAxis?.label"
        :x="props.x - 28"
        :y="props.y + props.plotH / 2"
        :transform="`rotate(-90, ${props.x - 28}, ${props.y + props.plotH / 2})`"
        text-anchor="middle"
        class="sg-chart-axis-title"
        font-size="11"
        fill="currentColor"
      >
        {{ props.yAxis.label }}
      </text>
    </g>
    <g v-if="props.xAxis" class="sg-chart-axis sg-chart-axis-x">
      <text
        v-for="(t, i) in xTicks"
        :key="`xt-${i}`"
        :x="t.x"
        :y="props.y + props.plotH + 14"
        text-anchor="middle"
        class="sg-chart-axis-label"
        font-size="10"
        fill="currentColor"
      >
        {{ t.label }}
      </text>
      <text
        v-if="props.xAxis?.label"
        :x="props.x + props.plotW / 2"
        :y="props.y + props.plotH + 28"
        text-anchor="middle"
        class="sg-chart-axis-title"
        font-size="11"
        fill="currentColor"
      >
        {{ props.xAxis.label }}
      </text>
    </g>
  </g>
</template>
