// packages/react/src/components/complex/ResourceCalendar/ResourceCalendar.tsx
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent,
} from 'react'
import { detectConflicts, isAvailable } from '@skygraph/core'
import type { CalendarConflict as Conflict } from '@skygraph/core'
import type { Assignment, CalendarScale, Resource, ResourceCalendarProps } from './types'
import { useConfig } from '../../ConfigProvider'

const DAY = 86_400_000
const STEP_MS: Record<CalendarScale, number> = {
  day: DAY,
  week: 7 * DAY,
  month: 30 * DAY,
}

function toMs(v: Date | number): number {
  return v instanceof Date ? v.getTime() : v
}

function alignDown(t: number, step: number): number {
  return Math.floor(t / step) * step
}

function alignUp(t: number, step: number): number {
  return Math.ceil(t / step) * step
}

function formatTick(timeMs: number, scale: CalendarScale): string {
  const d = new Date(timeMs)
  switch (scale) {
    case 'day': {
      const dd = String(d.getUTCDate()).padStart(2, '0')
      const mm = String(d.getUTCMonth() + 1).padStart(2, '0')
      return `${dd}.${mm}`
    }
    case 'week': {
      const dd = String(d.getUTCDate()).padStart(2, '0')
      const mm = String(d.getUTCMonth() + 1).padStart(2, '0')
      return `W ${dd}.${mm}`
    }
    case 'month': {
      const mm = String(d.getUTCMonth() + 1).padStart(2, '0')
      return `${mm}.${d.getUTCFullYear()}`
    }
  }
}

/**
 * Resolves the visible time axis. `range` is treated as the *minimum*
 * viewport — assignments may pull it further left or right (aligned to
 * `step` so column borders stay whole). When no `range` is provided we
 * derive one purely from `assignments` (with one-step padding on each
 * side for breathing room). This matches the Vue implementation so
 * both adapters expose identical scheduling behaviour.
 */
function resolveRange(
  assignments: readonly Assignment[],
  step: number,
  range: { from: Date; to: Date } | undefined,
): { from: Date; to: Date } {
  let lo = Infinity
  let hi = -Infinity
  for (const a of assignments) {
    const s = toMs(a.start)
    const e = toMs(a.end)
    if (s < lo) lo = s
    if (e > hi) hi = e
  }
  if (range) {
    const rangeFrom = range.from.getTime()
    const rangeTo = range.to.getTime()
    if (assignments.length === 0) return { from: new Date(rangeFrom), to: new Date(rangeTo) }
    return {
      from: new Date(alignDown(Math.min(rangeFrom, lo), step)),
      to: new Date(alignUp(Math.max(rangeTo, hi), step)),
    }
  }
  if (assignments.length === 0) {
    const now = Date.now()
    return {
      from: new Date(alignDown(now, step)),
      to: new Date(alignUp(now + step * 4, step)),
    }
  }
  return {
    from: new Date(alignDown(lo - step, step)),
    to: new Date(alignUp(hi + step, step)),
  }
}

/**
 * Resource Calendar — shifts / bookings per resource lane with
 * automatic conflict detection.
 *
 * v1 capabilities:
 *   - `scale` of `day | week | month` — drives header ticks AND
 *     drag/resize snap (1 column = 1 step).
 *   - `draggable` — drag a block to move it horizontally; both `start`
 *     and `end` shift by the snapped delta. Lane (resource) is
 *     preserved — vertical lane changes are out of scope for v1.
 *   - `resizable` — drag the left/right edge to resize that side
 *     independently. Minimum width clamped to one `scale` step.
 *   - Conflict overlay — assignments participating in any conflict
 *     get the `sg-rcal-assignment-conflict` modifier (red border /
 *     hatched background). `onConflict` fires after every change with
 *     the freshly detected `Conflict[]`.
 *   - `availability-off` background bands appear on slots that fall
 *     outside the configured `rules`.
 *
 * Out-of-scope (planned for v2): cross-lane drag, multi-day all-day
 * blocks, recurrence, exception dates, calendar-aware month widths.
 */
export function ResourceCalendar({
  resources,
  assignments,
  rules,
  scale = 'week',
  range,
  columnWidth = 120,
  rowHeight = 56,
  sidebarWidth = 200,
  draggable = false,
  resizable = false,
  onAssignmentChange,
  onConflict,
  unstyled = false,
  className,
  style,
}: ResourceCalendarProps) {
  const resourceCalendarLocale = useConfig().locale?.resourceCalendar
  const onChangeRef = useRef(onAssignmentChange)
  onChangeRef.current = onAssignmentChange
  const onConflictRef = useRef(onConflict)
  onConflictRef.current = onConflict

  // Local "ghost" overlay during a drag so React state doesn't have to
  // round-trip through the consumer for each mousemove. The ghost is
  // cleared on mouseup; the canonical update is what `onAssignmentChange`
  // produces.
  const [ghost, setGhost] = useState<Assignment | null>(null)

  const step = STEP_MS[scale]
  const resolvedRange = useMemo(
    () => resolveRange(assignments, step, range),
    [range, assignments, step],
  )
  const rangeStart = resolvedRange.from.getTime()
  const rangeEnd = resolvedRange.to.getTime()
  const pxPerMs = columnWidth / step
  const totalWidth = (rangeEnd - rangeStart) * pxPerMs

  const ticks = useMemo(() => {
    const out: Array<{ x: number; label: string; time: number }> = []
    for (let t = rangeStart; t < rangeEnd; t += step) {
      out.push({
        x: (t - rangeStart) * pxPerMs,
        label: formatTick(t, scale),
        time: t,
      })
    }
    return out
  }, [rangeStart, rangeEnd, step, pxPerMs, scale])

  const rowIndexById = useMemo(() => {
    const m = new Map<string, number>()
    resources.forEach((r, i) => m.set(r.id, i))
    return m
  }, [resources])

  const normalizedAssignments = useMemo<Assignment[]>(() => {
    return assignments.map((a) => {
      if (ghost && ghost.id === a.id) return ghost
      return a
    })
  }, [assignments, ghost])

  const conflicts = useMemo<Conflict[]>(() => {
    return detectConflicts(
      {
        resources: resources.map((r) => ({
          id: r.id,
          name: r.name,
          color: r.color,
          capacityPerSlot: r.capacityPerSlot,
          meta: r.meta,
        })),
        assignments: normalizedAssignments.map((a) => ({
          id: a.id,
          resourceId: a.resourceId,
          start: toMs(a.start),
          end: toMs(a.end),
          title: a.title,
          status: a.status,
          meta: a.meta,
        })),
      },
      { scale, rules: rules ?? [] },
    )
  }, [resources, normalizedAssignments, scale, rules])

  const conflictingIds = useMemo(() => {
    const s = new Set<string>()
    for (const c of conflicts) for (const id of c.assignmentIds) s.add(id)
    return s
  }, [conflicts])

  // Fire onConflict whenever the conflict set actually changes. Using a
  // stable key (sorted ids per conflict) avoids spurious calls when
  // detection re-runs but produces the same set.
  const conflictKey = useMemo(
    () =>
      conflicts
        .map((c) => `${c.reason}:${c.assignmentIds.join(',')}`)
        .sort()
        .join('|'),
    [conflicts],
  )
  const lastKeyRef = useRef<string>('')
  useEffect(() => {
    if (lastKeyRef.current === conflictKey) return
    lastKeyRef.current = conflictKey
    onConflictRef.current?.(conflicts)
  }, [conflictKey, conflicts])

  // Compute the screen rectangles for each assignment.
  const assignmentRects = useMemo(() => {
    return normalizedAssignments
      .map((a) => {
        const row = rowIndexById.get(a.resourceId)
        if (row === undefined) return null
        const startMs = toMs(a.start)
        const endMs = toMs(a.end)
        const x = (startMs - rangeStart) * pxPerMs
        const w = Math.max(2, (endMs - startMs) * pxPerMs)
        const y = row * rowHeight
        return { assignment: a, x, y, w, h: rowHeight, row }
      })
      .filter((r): r is NonNullable<typeof r> => r !== null)
  }, [normalizedAssignments, rowIndexById, rangeStart, pxPerMs, rowHeight])

  // Per-row availability bands — pre-compute slot windows where the
  // resource is unavailable. Drawn as background stripes behind the
  // assignment blocks. We bucket slots so non-uniform consecutive
  // unavailable slots merge into one block visually.
  const availabilityBands = useMemo(() => {
    if (!rules || rules.length === 0)
      return [] as Array<{
        key: string
        x: number
        y: number
        w: number
        h: number
      }>
    const out: Array<{ key: string; x: number; y: number; w: number; h: number }> = []
    for (const r of resources) {
      const row = rowIndexById.get(r.id)
      if (row === undefined) continue
      const y = row * rowHeight
      let bandStart: number | null = null
      for (let t = rangeStart; t < rangeEnd; t += step) {
        const ok = isAvailable(
          { id: r.id, name: r.name, color: r.color, capacityPerSlot: r.capacityPerSlot },
          { start: t, end: t + step },
          rules,
        )
        if (!ok) {
          if (bandStart === null) bandStart = t
        } else if (bandStart !== null) {
          out.push({
            key: `${r.id}-${bandStart}`,
            x: (bandStart - rangeStart) * pxPerMs,
            y,
            w: (t - bandStart) * pxPerMs,
            h: rowHeight,
          })
          bandStart = null
        }
      }
      if (bandStart !== null) {
        out.push({
          key: `${r.id}-${bandStart}`,
          x: (bandStart - rangeStart) * pxPerMs,
          y,
          w: (rangeEnd - bandStart) * pxPerMs,
          h: rowHeight,
        })
      }
    }
    return out
  }, [rules, resources, rowIndexById, rangeStart, rangeEnd, step, pxPerMs, rowHeight])

  // ─── Drag / resize plumbing ─────────────────────────────────────────────
  const dragRef = useRef<{
    kind: 'move' | 'resize-start' | 'resize-end'
    assignmentId: string
    startClientX: number
    origStart: number
    origEnd: number
    lastStart: number
    lastEnd: number
  } | null>(null)

  const startInteraction = useCallback(
    (
      e: ReactMouseEvent<HTMLDivElement>,
      assignment: Assignment,
      kind: 'move' | 'resize-start' | 'resize-end',
    ) => {
      if (e.button !== 0) return
      if (kind === 'move' && !draggable) return
      if (kind !== 'move' && !resizable) return
      e.preventDefault()
      e.stopPropagation()

      const origStart = toMs(assignment.start)
      const origEnd = toMs(assignment.end)

      dragRef.current = {
        kind,
        assignmentId: assignment.id,
        startClientX: e.clientX,
        origStart,
        origEnd,
        lastStart: origStart,
        lastEnd: origEnd,
      }
      setGhost({ ...assignment, start: origStart, end: origEnd })

      function emit(nextStart: number, nextEnd: number) {
        const cb = onChangeRef.current
        if (!cb) return
        cb({
          ...assignment,
          start: nextStart,
          end: nextEnd,
        })
      }

      function onMove(ev: MouseEvent) {
        const d = dragRef.current
        if (!d) return
        const dxPx = ev.clientX - d.startClientX
        const dxMs = dxPx / pxPerMs
        const snappedDx = Math.round(dxMs / step) * step
        let nextStart = d.origStart
        let nextEnd = d.origEnd
        if (d.kind === 'move') {
          nextStart = d.origStart + snappedDx
          nextEnd = d.origEnd + snappedDx
        } else if (d.kind === 'resize-end') {
          nextEnd = Math.max(d.origStart + step, d.origEnd + snappedDx)
        } else {
          nextStart = Math.min(d.origEnd - step, d.origStart + snappedDx)
        }
        if (nextStart === d.lastStart && nextEnd === d.lastEnd) return
        d.lastStart = nextStart
        d.lastEnd = nextEnd
        setGhost({ ...assignment, start: nextStart, end: nextEnd })
        emit(nextStart, nextEnd)
      }

      function onUp() {
        dragRef.current = null
        setGhost(null)
        window.removeEventListener('mousemove', onMove)
        window.removeEventListener('mouseup', onUp)
      }

      window.addEventListener('mousemove', onMove)
      window.addEventListener('mouseup', onUp)
    },
    [draggable, resizable, pxPerMs, step],
  )

  const onAssignmentKeyDown = useCallback(
    (e: ReactKeyboardEvent<HTMLDivElement>, assignment: Assignment) => {
      if (!draggable && !resizable) return
      const cb = onChangeRef.current
      if (!cb) return
      const startMs = toMs(assignment.start)
      const endMs = toMs(assignment.end)
      // ArrowLeft / ArrowRight = move ±1 step (when draggable).
      // Shift+ArrowLeft / ArrowRight = resize end ±1 step (when resizable).
      if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
        const dir = e.key === 'ArrowLeft' ? -1 : 1
        e.preventDefault()
        if (e.shiftKey && resizable) {
          const nextEnd = Math.max(startMs + step, endMs + dir * step)
          cb({ ...assignment, start: startMs, end: nextEnd })
        } else if (draggable) {
          cb({
            ...assignment,
            start: startMs + dir * step,
            end: endMs + dir * step,
          })
        }
      }
    },
    [draggable, resizable, step],
  )

  // ─── Render ─────────────────────────────────────────────────────────────
  const wrapperClass = unstyled ? className : ['sg-rcal', className].filter(Boolean).join(' ')

  const headerHeight = Math.max(28, Math.round(rowHeight * 0.6))
  const gridHeight = resources.length * rowHeight
  const totalHeight = gridHeight + headerHeight

  const wrapperStyle: CSSProperties = {
    display: 'grid',
    gridTemplateColumns: `${sidebarWidth}px 1fr`,
    width: '100%',
    overflow: 'auto',
    height: totalHeight,
    ...style,
  }

  return (
    <div
      className={wrapperClass}
      style={wrapperStyle}
      role="region"
      aria-label={resourceCalendarLocale?.ariaLabel ?? 'Resource calendar'}
      data-scale={scale}
    >
      {/* Sidebar (resource list) */}
      <div className={unstyled ? undefined : 'sg-rcal-sidebar'} style={{ width: sidebarWidth }}>
        <div
          className={unstyled ? undefined : 'sg-rcal-sidebar-header'}
          style={{ height: headerHeight }}
        />
        {resources.map((r, i) => (
          <div
            key={r.id}
            className={unstyled ? undefined : 'sg-rcal-sidebar-row'}
            style={{ height: rowHeight }}
            role="row"
            aria-label={
              resourceCalendarLocale?.resource
                ? resourceCalendarLocale.resource(r.name)
                : `Resource ${r.name}`
            }
            data-row-index={i}
            data-resource-id={r.id}
          >
            <span
              className={unstyled ? undefined : 'sg-rcal-sidebar-marker'}
              style={r.color ? { background: r.color } : undefined}
              data-role="marker"
              aria-hidden="true"
            />
            <span className={unstyled ? undefined : 'sg-rcal-sidebar-name'}>{r.name}</span>
            {r.capacityPerSlot !== undefined && (
              <span
                className={unstyled ? undefined : 'sg-rcal-sidebar-capacity'}
                aria-label={
                  resourceCalendarLocale?.capacity
                    ? resourceCalendarLocale.capacity(r.capacityPerSlot)
                    : `capacity ${r.capacityPerSlot} per slot`
                }
              >
                ×{r.capacityPerSlot}
              </span>
            )}
          </div>
        ))}
      </div>

      {/* Main: header + grid + assignments */}
      <div
        className={unstyled ? undefined : 'sg-rcal-main'}
        style={{ position: 'relative', width: totalWidth, minWidth: '100%' }}
      >
        <div
          className={unstyled ? undefined : 'sg-rcal-header'}
          style={{ position: 'relative', height: headerHeight, width: totalWidth }}
        >
          {ticks.map((t) => (
            <div
              key={t.time}
              className={unstyled ? undefined : 'sg-rcal-tick'}
              style={{
                position: 'absolute',
                left: t.x,
                top: 0,
                width: columnWidth,
                height: headerHeight,
              }}
              data-tick-time={t.time}
            >
              {t.label}
            </div>
          ))}
        </div>

        <div
          className={unstyled ? undefined : 'sg-rcal-grid'}
          style={{
            position: 'relative',
            width: totalWidth,
            height: gridHeight,
          }}
          data-conflict-count={conflicts.length}
        >
          {/* Row backgrounds */}
          {resources.map((r, i) => (
            <div
              key={r.id}
              className={unstyled ? undefined : 'sg-rcal-row'}
              style={{
                position: 'absolute',
                left: 0,
                top: i * rowHeight,
                width: totalWidth,
                height: rowHeight,
              }}
              data-row-index={i}
              data-resource-id={r.id}
            >
              {/* Vertical slot dividers */}
              {ticks.map((t) => (
                <div
                  key={t.time}
                  className={unstyled ? undefined : 'sg-rcal-slot'}
                  style={{
                    position: 'absolute',
                    left: t.x,
                    top: 0,
                    width: columnWidth,
                    height: rowHeight,
                  }}
                  data-slot-time={t.time}
                />
              ))}
            </div>
          ))}

          {/* Availability bands (off-window) */}
          {availabilityBands.map((b) => (
            <div
              key={b.key}
              className={unstyled ? undefined : 'sg-rcal-availability-off'}
              style={{
                position: 'absolute',
                left: b.x,
                top: b.y,
                width: b.w,
                height: b.h,
                pointerEvents: 'none',
              }}
              data-role="availability-off"
              aria-hidden="true"
            />
          ))}

          {/* Assignment blocks */}
          {assignmentRects.map(({ assignment, x, y, w, h }) => {
            const status = conflictingIds.has(assignment.id)
              ? 'conflict'
              : (assignment.status ?? 'tentative')
            const blockClass = unstyled
              ? undefined
              : [
                  'sg-rcal-assignment',
                  `sg-rcal-assignment-${status}`,
                  draggable ? 'sg-rcal-assignment-draggable' : '',
                  resizable ? 'sg-rcal-assignment-resizable' : '',
                ]
                  .filter(Boolean)
                  .join(' ')
            const colorOverride =
              status !== 'conflict'
                ? resources.find((r) => r.id === assignment.resourceId)?.color
                : undefined
            return (
              <div
                key={assignment.id}
                className={blockClass}
                style={{
                  position: 'absolute',
                  left: x,
                  top: y + 4,
                  width: w,
                  height: h - 8,
                  background: colorOverride,
                  cursor: draggable ? 'grab' : undefined,
                  userSelect: draggable || resizable ? 'none' : undefined,
                }}
                role="button"
                tabIndex={0}
                aria-label={`${assignment.title}${status === 'conflict' ? (resourceCalendarLocale?.conflictSuffix ?? ' (conflict)') : ''}`}
                data-assignment-id={assignment.id}
                data-status={status}
                data-resource-id={assignment.resourceId}
                onMouseDown={draggable ? (e) => startInteraction(e, assignment, 'move') : undefined}
                onKeyDown={(e) => onAssignmentKeyDown(e, assignment)}
              >
                {resizable && (
                  <div
                    className={unstyled ? undefined : 'sg-rcal-assignment-resize-start'}
                    role="button"
                    aria-label={resourceCalendarLocale?.resizeStart ?? 'Resize start'}
                    tabIndex={-1}
                    data-role="resize-handle-start"
                    style={{
                      position: 'absolute',
                      left: 0,
                      top: 0,
                      bottom: 0,
                      width: 6,
                      cursor: 'ew-resize',
                    }}
                    onMouseDown={(e) => startInteraction(e, assignment, 'resize-start')}
                  />
                )}
                <span
                  className={unstyled ? undefined : 'sg-rcal-assignment-title'}
                  style={{ position: 'relative', zIndex: 1 }}
                >
                  {assignment.title}
                </span>
                {resizable && (
                  <div
                    className={unstyled ? undefined : 'sg-rcal-assignment-resize-end'}
                    role="button"
                    aria-label={resourceCalendarLocale?.resizeEnd ?? 'Resize end'}
                    tabIndex={-1}
                    data-role="resize-handle-end"
                    style={{
                      position: 'absolute',
                      right: 0,
                      top: 0,
                      bottom: 0,
                      width: 6,
                      cursor: 'ew-resize',
                    }}
                    onMouseDown={(e) => startInteraction(e, assignment, 'resize-end')}
                  />
                )}
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}

// `Resource` is part of the local domain; explicitly used here so the
// helper lives next to its only consumer (rendering).
export type { Resource }

// packages/vue/src/components/complex/ResourceCalendar/ResourceCalendar.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useConfig } from '../../ui/ConfigProvider.vue'
import type { Assignment, CalendarScale, ResourceCalendarProps } from './types'

const props = withDefaults(defineProps<ResourceCalendarProps>(), {
  scale: 'week',
  columnWidth: 120,
  rowHeight: 56,
  sidebarWidth: 200,
  draggable: false,
  resizable: false,
  unstyled: false,
})

const emit = defineEmits<{
  (e: 'assignment-change', next: Assignment): void
  (e: 'assignmentChange', next: Assignment): void
  (e: 'conflict', conflicts: Array<{ a: Assignment; b: Assignment }>): void
}>()

const cfg = useConfig()
const calendarLabel = computed(
  () => cfg.value.locale?.resourceCalendar?.ariaLabel ?? 'Resource calendar',
)
const resizeStartLabel = computed(
  () => cfg.value.locale?.resourceCalendar?.resizeStart ?? 'Resize start',
)
const resizeEndLabel = computed(() => cfg.value.locale?.resourceCalendar?.resizeEnd ?? 'Resize end')

const MS_PER_DAY = 24 * 60 * 60 * 1000

const stepMs = (scale: CalendarScale): number => {
  switch (scale) {
    case 'day':
      return MS_PER_DAY
    case 'week':
      return MS_PER_DAY * 7
    case 'month':
      return MS_PER_DAY * 30
  }
}

const toMs = (d: Date | number) => (d instanceof Date ? d.getTime() : d)

function alignDown(t: number, step: number): number {
  return Math.floor(t / step) * step
}
function alignUp(t: number, step: number): number {
  return Math.ceil(t / step) * step
}

const computedRange = computed(() => {
  const step = stepMs(props.scale)

  // Scan the live assignments so the timeline can grow past `props.range`
  // when the user drag-resizes a bar past the right-hand edge. Without this
  // the bar would render off-screen and leave the user without any visual
  // feedback for the resize.
  let assignmentMin = Infinity
  let assignmentMax = -Infinity
  for (const a of props.assignments) {
    const s = toMs(a.start)
    const e = toMs(a.end)
    if (s < assignmentMin) assignmentMin = s
    if (e > assignmentMax) assignmentMax = e
  }

  if (props.range) {
    const rangeFrom = props.range.from.getTime()
    const rangeTo = props.range.to.getTime()
    if (props.assignments.length === 0) {
      return { from: rangeFrom, to: rangeTo }
    }
    // `range` is treated as the *minimum* viewport — assignments may pull
    // the visible window further in either direction (aligned to step so
    // the column grid stays whole).
    return {
      from: alignDown(Math.min(rangeFrom, assignmentMin), step),
      to: alignUp(Math.max(rangeTo, assignmentMax), step),
    }
  }

  if (props.assignments.length === 0) {
    const now = Date.now()
    return { from: alignDown(now, step), to: alignUp(now + step * 4, step) }
  }
  return {
    from: alignDown(assignmentMin - step, step),
    to: alignUp(assignmentMax + step, step),
  }
})

const totalMs = computed(() => computedRange.value.to - computedRange.value.from)
const stepValue = computed(() => stepMs(props.scale))
const totalSteps = computed(() => Math.max(1, Math.ceil(totalMs.value / stepValue.value)))
const pxPerMs = computed(() => props.columnWidth / stepValue.value)
const totalWidth = computed(() => totalMs.value * pxPerMs.value)

const headerHeight = computed(() => Math.max(28, Math.round(props.rowHeight * 0.6)))
const gridHeight = computed(() => props.resources.length * props.rowHeight)
const totalHeight = computed(() => gridHeight.value + headerHeight.value)

function formatTick(timeMs: number, scale: CalendarScale): string {
  const d = new Date(timeMs)
  switch (scale) {
    case 'day': {
      const dd = String(d.getUTCDate()).padStart(2, '0')
      const mm = String(d.getUTCMonth() + 1).padStart(2, '0')
      return `${dd}.${mm}`
    }
    case 'week': {
      const dd = String(d.getUTCDate()).padStart(2, '0')
      const mm = String(d.getUTCMonth() + 1).padStart(2, '0')
      return `W ${dd}.${mm}`
    }
    case 'month': {
      const mm = String(d.getUTCMonth() + 1).padStart(2, '0')
      return `${mm}.${d.getUTCFullYear()}`
    }
  }
}

const ticks = computed(() => {
  const arr: Array<{ x: number; label: string; time: number }> = []
  const step = stepValue.value
  for (let i = 0; i < totalSteps.value; i++) {
    const t = computedRange.value.from + i * step
    arr.push({
      x: i * props.columnWidth,
      label: formatTick(t, props.scale),
      time: t,
    })
  }
  return arr
})

const rowIndexById = computed(() => {
  const m = new Map<string, number>()
  props.resources.forEach((r, i) => m.set(r.id, i))
  return m
})

// Naive per-resource overlap detection (documented simplification vs the
// React engine). Produces the `{ a, b }` pairs the `conflict` event carries.
const conflictPairs = computed<Array<{ a: Assignment; b: Assignment }>>(() => {
  const pairs: Array<{ a: Assignment; b: Assignment }> = []
  const byResource = new Map<string, Assignment[]>()
  for (const a of props.assignments) {
    const list = byResource.get(a.resourceId) ?? []
    list.push(a)
    byResource.set(a.resourceId, list)
  }
  for (const list of byResource.values()) {
    for (let i = 0; i < list.length; i++) {
      for (let j = i + 1; j < list.length; j++) {
        const aS = toMs(list[i].start)
        const aE = toMs(list[i].end)
        const bS = toMs(list[j].start)
        const bE = toMs(list[j].end)
        if (aS < bE && bS < aE) {
          pairs.push({ a: list[i], b: list[j] })
        }
      }
    }
  }
  return pairs
})

const conflictingIds = computed(() => {
  const ids = new Set<string>()
  for (const { a, b } of conflictPairs.value) {
    ids.add(a.id)
    ids.add(b.id)
  }
  return ids
})

// Fire `conflict` whenever the detected set actually changes. A stable key
// (sorted id-pairs) avoids spurious emits when detection re-runs with the
// same result mid-drag. Runs immediately so consumers see the initial set
// without waiting for an interaction.
const conflictKey = computed(() =>
  conflictPairs.value
    .map((p) => [p.a.id, p.b.id].sort().join('~'))
    .sort()
    .join('|'),
)

watch(
  conflictKey,
  () => {
    emit('conflict', conflictPairs.value)
  },
  { immediate: true },
)

const assignmentRects = computed(() => {
  return props.assignments
    .map((a) => {
      const row = rowIndexById.value.get(a.resourceId)
      if (row === undefined) return null
      const startMs = toMs(a.start)
      const endMs = toMs(a.end)
      const x = (startMs - computedRange.value.from) * pxPerMs.value
      const w = Math.max(2, (endMs - startMs) * pxPerMs.value)
      const y = row * props.rowHeight
      return { assignment: a, x, y, w, h: props.rowHeight, row }
    })
    .filter((r): r is NonNullable<typeof r> => r !== null)
})

function statusOf(a: Assignment): string {
  if (conflictingIds.value.has(a.id)) return 'conflict'
  return a.status ?? 'tentative'
}

function blockClass(a: Assignment): string {
  if (props.unstyled) return ''
  return [
    'sg-rcal-assignment',
    `sg-rcal-assignment-${statusOf(a)}`,
    props.draggable ? 'sg-rcal-assignment-draggable' : '',
    props.resizable ? 'sg-rcal-assignment-resizable' : '',
  ]
    .filter(Boolean)
    .join(' ')
}

function colorOverrideFor(a: Assignment): string | undefined {
  if (statusOf(a) === 'conflict') return undefined
  return props.resources.find((r) => r.id === a.resourceId)?.color
}

interface DragSession {
  kind: 'move' | 'resize-start' | 'resize-end'
  id: string
  startClientX: number
  origStart: number
  origEnd: number
}

const drag = ref<DragSession | null>(null)

function startInteraction(
  e: PointerEvent,
  a: Assignment,
  kind: 'move' | 'resize-start' | 'resize-end',
) {
  if (e.button !== 0) return
  if (kind === 'move' && !props.draggable) return
  if (kind !== 'move' && !props.resizable) return
  e.preventDefault()
  e.stopPropagation()
  ;(e.target as HTMLElement).setPointerCapture?.(e.pointerId)
  drag.value = {
    kind,
    id: a.id,
    startClientX: e.clientX,
    origStart: toMs(a.start),
    origEnd: toMs(a.end),
  }
}

function onPointerMove(e: PointerEvent) {
  const d = drag.value
  if (!d) return
  const a = props.assignments.find((x) => x.id === d.id)
  if (!a) return
  const dxPx = e.clientX - d.startClientX
  const dxMs = dxPx / pxPerMs.value
  const step = stepValue.value
  const snappedDx = Math.round(dxMs / step) * step
  let nextStart = d.origStart
  let nextEnd = d.origEnd
  if (d.kind === 'move') {
    nextStart = d.origStart + snappedDx
    nextEnd = d.origEnd + snappedDx
  } else if (d.kind === 'resize-end') {
    nextEnd = Math.max(d.origStart + step, d.origEnd + snappedDx)
  } else {
    nextStart = Math.min(d.origEnd - step, d.origStart + snappedDx)
  }
  const next: Assignment = { ...a, start: nextStart, end: nextEnd }
  emit('assignment-change', next)
  emit('assignmentChange', next)
}

function onPointerUp() {
  drag.value = null
}

function onAssignmentKeyDown(e: KeyboardEvent, a: Assignment) {
  if (!props.draggable && !props.resizable) return
  const step = stepValue.value
  const startMs = toMs(a.start)
  const endMs = toMs(a.end)
  if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
    const dir = e.key === 'ArrowLeft' ? -1 : 1
    e.preventDefault()
    let next: Assignment
    if (e.shiftKey && props.resizable) {
      next = { ...a, start: startMs, end: Math.max(startMs + step, endMs + dir * step) }
    } else if (props.draggable) {
      next = { ...a, start: startMs + dir * step, end: endMs + dir * step }
    } else {
      return
    }
    emit('assignment-change', next)
    emit('assignmentChange', next)
  }
}

const wrapperClass = computed(() => {
  if (props.unstyled) return props.className ?? ''
  return ['sg-rcal', props.className].filter(Boolean).join(' ')
})

const wrapperStyle = computed(() => ({
  display: 'grid',
  gridTemplateColumns: `${props.sidebarWidth}px 1fr`,
  width: '100%',
  overflow: 'auto',
  height: `${totalHeight.value}px`,
  ...(props.style ?? {}),
}))
</script>

<template>
  <div
    :class="wrapperClass"
    :style="wrapperStyle"
    role="region"
    :aria-label="calendarLabel"
    :data-scale="scale"
    :data-conflict-count="conflictingIds.size"
    @pointermove="onPointerMove"
    @pointerup="onPointerUp"
  >
    <!-- Sidebar -->
    <div :class="unstyled ? undefined : 'sg-rcal-sidebar'" :style="{ width: `${sidebarWidth}px` }">
      <div
        :class="unstyled ? undefined : 'sg-rcal-sidebar-header'"
        :style="{ height: `${headerHeight}px` }"
      />
      <div
        v-for="(r, i) in resources"
        :key="r.id"
        :class="unstyled ? undefined : 'sg-rcal-sidebar-row'"
        :style="{ height: `${rowHeight}px` }"
        role="row"
        :aria-label="`Resource ${r.name}`"
        :data-row-index="i"
        :data-resource-id="r.id"
      >
        <span
          :class="unstyled ? undefined : 'sg-rcal-sidebar-marker'"
          :style="r.color ? { background: r.color } : undefined"
          data-role="marker"
          aria-hidden="true"
        />
        <span :class="unstyled ? undefined : 'sg-rcal-sidebar-name'">{{ r.name }}</span>
        <span
          v-if="r.capacityPerSlot !== undefined"
          :class="unstyled ? undefined : 'sg-rcal-sidebar-capacity'"
          :aria-label="`capacity ${r.capacityPerSlot} per slot`"
          >×{{ r.capacityPerSlot }}</span
        >
      </div>
    </div>

    <!-- Main pane -->
    <div
      :class="unstyled ? undefined : 'sg-rcal-main'"
      :style="{ position: 'relative', width: `${totalWidth}px`, minWidth: '100%' }"
    >
      <div
        :class="unstyled ? undefined : 'sg-rcal-header'"
        :style="{ position: 'relative', height: `${headerHeight}px`, width: `${totalWidth}px` }"
      >
        <div
          v-for="t in ticks"
          :key="t.time"
          :class="unstyled ? undefined : 'sg-rcal-tick'"
          :style="{
            position: 'absolute',
            left: `${t.x}px`,
            top: 0,
            width: `${columnWidth}px`,
            height: `${headerHeight}px`,
          }"
          :data-tick-time="t.time"
        >
          {{ t.label }}
        </div>
      </div>

      <div
        :class="unstyled ? undefined : 'sg-rcal-grid'"
        :style="{
          position: 'relative',
          width: `${totalWidth}px`,
          height: `${gridHeight}px`,
        }"
        :data-conflict-count="conflictingIds.size"
      >
        <!-- Row backgrounds -->
        <div
          v-for="(r, i) in resources"
          :key="r.id"
          :class="unstyled ? undefined : 'sg-rcal-row'"
          :style="{
            position: 'absolute',
            left: 0,
            top: `${i * rowHeight}px`,
            width: `${totalWidth}px`,
            height: `${rowHeight}px`,
          }"
          :data-row-index="i"
          :data-resource-id="r.id"
        >
          <div
            v-for="t in ticks"
            :key="t.time"
            :class="unstyled ? undefined : 'sg-rcal-slot'"
            :style="{
              position: 'absolute',
              left: `${t.x}px`,
              top: 0,
              width: `${columnWidth}px`,
              height: `${rowHeight}px`,
            }"
            :data-slot-time="t.time"
          />
        </div>

        <!-- Assignment blocks -->
        <div
          v-for="rect in assignmentRects"
          :key="rect.assignment.id"
          :class="blockClass(rect.assignment)"
          :style="{
            position: 'absolute',
            left: `${rect.x}px`,
            top: `${rect.y + 4}px`,
            width: `${rect.w}px`,
            height: `${rect.h - 8}px`,
            background: colorOverrideFor(rect.assignment),
            cursor: draggable ? 'grab' : undefined,
            userSelect: draggable || resizable ? 'none' : undefined,
          }"
          role="button"
          tabindex="0"
          :aria-label="`${rect.assignment.title}${statusOf(rect.assignment) === 'conflict' ? ' (conflict)' : ''}`"
          :data-assignment-id="rect.assignment.id"
          :data-status="statusOf(rect.assignment)"
          :data-resource-id="rect.assignment.resourceId"
          @pointerdown="draggable ? startInteraction($event, rect.assignment, 'move') : undefined"
          @keydown="(e: KeyboardEvent) => onAssignmentKeyDown(e, rect.assignment)"
        >
          <div
            v-if="resizable"
            :class="unstyled ? undefined : 'sg-rcal-assignment-resize-start'"
            role="button"
            :aria-label="resizeStartLabel"
            tabindex="-1"
            data-role="resize-handle-start"
            :style="{
              position: 'absolute',
              left: 0,
              top: 0,
              bottom: 0,
              width: '6px',
              cursor: 'ew-resize',
            }"
            @pointerdown="(e: PointerEvent) => startInteraction(e, rect.assignment, 'resize-start')"
          />
          <span
            :class="unstyled ? undefined : 'sg-rcal-assignment-title'"
            :style="{ position: 'relative', zIndex: 1 }"
            >{{ rect.assignment.title }}</span
          >
          <div
            v-if="resizable"
            :class="unstyled ? undefined : 'sg-rcal-assignment-resize-end'"
            role="button"
            :aria-label="resizeEndLabel"
            tabindex="-1"
            data-role="resize-handle-end"
            :style="{
              position: 'absolute',
              right: 0,
              top: 0,
              bottom: 0,
              width: '6px',
              cursor: 'ew-resize',
            }"
            @pointerdown="(e: PointerEvent) => startInteraction(e, rect.assignment, 'resize-end')"
          />
        </div>
      </div>
    </div>
  </div>
</template>
