// packages/react/src/components/ui/Avatar.tsx
import React from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, SizeType } from '../../types'

/** Props for the Avatar component (image, icon, or text fallback). */
export interface AvatarProps extends BaseComponentProps {
  /** Image URL when displaying a photo avatar. */
  src?: string
  /** Alt text for the image when `src` is set. */
  alt?: string
  /** Accessible name for the avatar when there is no visible text. */
  'aria-label'?: string
  /** Width/height in px (number) or preset size token. */
  size?: SizeType | number
  /** Outer shape of the avatar. @default 'circle' */
  shape?: 'circle' | 'square'
  /** Icon node shown when `src` is omitted. */
  icon?: React.ReactNode
  /** Text or initials shown when neither `src` nor `icon` is set. */
  children?: React.ReactNode
}

const sizeMap: Record<string, number> = {
  small: 24,
  default: 32,
  large: 40,
}

/**
 * Renders a user avatar from an image URL, icon, or text content.
 */
export function Avatar({
  src,
  alt,
  'aria-label': ariaLabel,
  size: sizeProp,
  shape = 'circle',
  icon,
  children,
  className,
  style,
  unstyled,
}: AvatarProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const avatarSize = typeof size === 'number' ? size : (size === 'middle' ? 'default' : size)
  const px = typeof size === 'number' ? size : sizeMap[avatarSize]
  const fontSize = Math.round(px * 0.45)

  if (unstyled) {
    return (
      <span className={className} style={style} role="img" aria-label={ariaLabel}>
        {src ? <img src={src} alt={alt} /> : icon ?? children}
      </span>
    )
  }

  const classes = [
    'sg-avatar',
    `sg-avatar-${shape}`,
    typeof size === 'string' ? `sg-avatar-${avatarSize}` : '',
    className,
  ].filter(Boolean).join(' ')

  const sizeStyle: React.CSSProperties = {
    width: px,
    height: px,
    lineHeight: `${px}px`,
    fontSize: src ? undefined : fontSize,
    ...style,
  }

  return (
    <span className={classes} style={sizeStyle} role="img" aria-label={ariaLabel}>
      {src ? (
        <img className="sg-avatar-image" src={src} alt={alt} />
      ) : icon ? (
        <span className="sg-avatar-icon">{icon}</span>
      ) : (
        <span className="sg-avatar-text">{children}</span>
      )}
    </span>
  )
}

// packages/vue/src/components/ui/Avatar.vue
<script setup lang="ts">
import { computed, useSlots, type CSSProperties } from 'vue'
import { useConfig } from './ConfigProvider.vue'
import type { SizeType } from '../../types'

export interface AvatarProps {
  /** Image URL when displaying a photo avatar. */
  src?: string
  /** Alt text. */
  alt?: string
  /** Accessible name. */
  ariaLabel?: string
  /** Width/height in px or preset size token. */
  size?: SizeType | number
  /** Outer shape. @default 'circle' */
  shape?: 'circle' | 'square'
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<AvatarProps>(), {
  shape: 'circle',
})

defineSlots<{
  default(props: Record<string, never>): unknown
  icon(props: Record<string, never>): unknown
}>()

const cfg = useConfig()
const sizeMap: Record<string, number> = { small: 24, default: 32, large: 40 }

const resolvedSize = computed<SizeType | number>(() =>
  props.size ?? cfg.value.size ?? 'middle',
)

const avatarSize = computed(() => {
  const s = resolvedSize.value
  if (typeof s === 'number') return s
  return s === 'middle' ? 'default' : s
})

const px = computed(() => {
  const s = resolvedSize.value
  return typeof s === 'number' ? s : sizeMap[avatarSize.value as string]
})

const fontSize = computed(() => Math.round(px.value * 0.45))

const slots = useSlots()
const hasIcon = computed(() => Boolean(slots.icon))

const classes = computed(() =>
  [
    'sg-avatar',
    `sg-avatar-${props.shape}`,
    typeof resolvedSize.value === 'string' ? `sg-avatar-${avatarSize.value}` : '',
  ]
    .filter(Boolean)
    .join(' '),
)

const sizeStyle = computed<CSSProperties>(() => ({
  width: `${px.value}px`,
  height: `${px.value}px`,
  lineHeight: `${px.value}px`,
  fontSize: props.src ? undefined : `${fontSize.value}px`,
}))
</script>

<template>
  <span
    v-if="unstyled"
    role="img"
    :aria-label="ariaLabel"
  >
    <img v-if="src" :src="src" :alt="alt" />
    <slot v-else-if="hasIcon" name="icon" />
    <slot v-else />
  </span>
  <span
    v-else
    :class="classes"
    :style="sizeStyle"
    role="img"
    :aria-label="ariaLabel"
  >
    <img v-if="src" class="sg-avatar-image" :src="src" :alt="alt" />
    <span v-else-if="hasIcon" class="sg-avatar-icon"><slot name="icon" /></span>
    <span v-else class="sg-avatar-text"><slot /></span>
  </span>
</template>
