// packages/react/src/components/ui/Badge.tsx
import React from 'react'
import type { BaseComponentProps, SizableProps } from '../../types'

/** Props for the Badge component (count, dot, or status ribbon). */
export interface BadgeProps extends BaseComponentProps, SizableProps {
  /** Numeric value shown in the badge; hidden when zero unless `showZero`. */
  count?: number
  /** Renders a small dot indicator instead of a numeric count. */
  dot?: boolean
  /** Maximum count before showing `{overflowCount}+`. @default 99 */
  overflowCount?: number
  /** When true, shows the badge even when `count` is zero. */
  showZero?: boolean
  /** Custom background color for the dot or count (CSS color). */
  color?: string
  /** Preset status style for standalone status badges. */
  status?: 'success' | 'error' | 'warning' | 'processing' | 'default'
  /** Text shown next to the status dot when `status` is set. */
  text?: React.ReactNode
  /** Pixel offset `[right, top]` for the dot or count position. */
  offset?: [number, number]
  /** Wrapped trigger element (e.g. icon or avatar). */
  children?: React.ReactNode
}

/**
 * Displays a notification count, dot, or status label on a child element.
 */
export function Badge({
  count,
  dot,
  overflowCount = 99,
  showZero,
  color,
  status,
  text,
  offset,
  children,
  className,
  style,
  unstyled,
}: BadgeProps) {
  const hasCount = count !== undefined && (count > 0 || showZero)
  const displayCount = hasCount ? (count! > overflowCount ? `${overflowCount}+` : `${count}`) : null

  if (unstyled) {
    return (
      <span
        className={className}
        style={{ position: 'relative', display: 'inline-block', ...style }}
      >
        {children}
        {(dot || hasCount) && <sup>{displayCount}</sup>}
        {status && <span>{text}</span>}
      </span>
    )
  }

  if (status && !children) {
    return (
      <span className={['sg-badge-status', className].filter(Boolean).join(' ')}>
        <span
          className={`sg-badge-status-dot sg-badge-status-${status}`}
          style={color ? { background: color } : undefined}
        />
        {text && <span className="sg-badge-status-text">{text}</span>}
      </span>
    )
  }

  const isStandalone = !children && (hasCount || dot)
  const offsetStyle: React.CSSProperties | undefined =
    offset && !isStandalone ? { right: -offset[0], marginTop: offset[1] } : undefined

  return (
    <span
      className={['sg-badge', isStandalone && 'sg-badge-standalone', className]
        .filter(Boolean)
        .join(' ')}
    >
      {children}
      {dot && !hasCount && (
        <sup
          className="sg-badge-dot"
          style={{ ...offsetStyle, ...(color ? { background: color } : {}) }}
        />
      )}
      {hasCount && (
        <sup
          className="sg-badge-count"
          style={{ ...offsetStyle, ...(color ? { background: color } : {}) }}
          aria-label={displayCount ?? undefined}
        >
          {displayCount}
        </sup>
      )}
    </span>
  )
}

// packages/vue/src/components/ui/Badge.vue
<script setup lang="ts">
import { computed, useSlots, type CSSProperties } from 'vue'

export interface BadgeProps {
  /** Numeric value shown in the badge. */
  count?: number
  /** Renders a small dot indicator. */
  dot?: boolean
  /** Maximum count before showing `{overflowCount}+`. @default 99 */
  overflowCount?: number
  /** Show even when count is 0. */
  showZero?: boolean
  /** Custom CSS color. */
  color?: string
  /** Preset status style. */
  status?: 'success' | 'error' | 'warning' | 'processing' | 'default'
  /** Status label text. */
  text?: string
  /** Pixel offset `[right, top]`. */
  offset?: [number, number]
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<BadgeProps>(), {
  overflowCount: 99,
})

defineSlots<{
  default(props: Record<string, never>): unknown
}>()

const slots = useSlots()
const hasChildren = computed(() => Boolean(slots.default))

const hasCount = computed(() => props.count !== undefined && (props.count > 0 || props.showZero))

const displayCount = computed(() => {
  if (!hasCount.value) return null
  return props.count! > props.overflowCount ? `${props.overflowCount}+` : `${props.count}`
})

const isStandalone = computed(() => !hasChildren.value && (hasCount.value || Boolean(props.dot)))

const offsetStyle = computed<CSSProperties | undefined>(() =>
  props.offset && !isStandalone.value
    ? { right: `${-props.offset[0]}px`, marginTop: `${props.offset[1]}px` }
    : undefined,
)

const colorStyle = computed<CSSProperties | undefined>(() =>
  props.color ? { background: props.color } : undefined,
)
</script>

<template>
  <span v-if="unstyled" style="position: relative; display: inline-block">
    <slot />
    <sup v-if="dot || hasCount">{{ displayCount }}</sup>
    <span v-if="status">{{ text }}</span>
  </span>
  <span v-else-if="status && !hasChildren" class="sg-badge-status">
    <span :class="`sg-badge-status-dot sg-badge-status-${status}`" :style="colorStyle" />
    <span v-if="text" class="sg-badge-status-text">{{ text }}</span>
  </span>
  <span v-else :class="['sg-badge', isStandalone ? 'sg-badge-standalone' : null]">
    <slot />
    <sup
      v-if="dot && !hasCount"
      class="sg-badge-dot"
      :style="{ ...(offsetStyle ?? {}), ...(colorStyle ?? {}) }"
    />
    <sup
      v-if="hasCount"
      class="sg-badge-count"
      :style="{ ...(offsetStyle ?? {}), ...(colorStyle ?? {}) }"
      :aria-label="displayCount ?? undefined"
    >
      {{ displayCount }}
    </sup>
  </span>
</template>
