// packages/react/src/components/ui/Carousel.tsx
import React, { useState, useEffect, useCallback, Children } from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps } from '../../types'

/** Props for a simple slide carousel with dots and optional autoplay. */
export interface CarouselProps extends BaseComponentProps {
  /** Advances to the next slide on an interval when there is more than one slide. @default false */
  autoplay?: boolean
  /** Interval in ms between autoplay steps. @default 3000 */
  autoplaySpeed?: number
  /** Shows dot controls to jump between slides (hidden when only one slide in styled mode). @default true */
  dots?: boolean
  /** Where dot navigation is placed relative to the track. @default 'bottom' */
  dotPosition?: 'top' | 'bottom' | 'left' | 'right'
  /** Transition between slides: horizontal offset or crossfade. @default 'slide' */
  effect?: 'slide' | 'fade'
  /** Each direct child is treated as one slide. */
  children: React.ReactNode
}

/**
 * Cycles through child slides with optional autoplay, dot navigation, and slide or fade transitions.
 */
export function Carousel({
  autoplay = false,
  autoplaySpeed = 3000,
  dots = true,
  dotPosition = 'bottom',
  effect = 'slide',
  children,
  className,
  style,
  unstyled,
}: CarouselProps) {
  const slides = Children.toArray(children)
  const count = slides.length
  const [current, setCurrent] = useState(0)
  const slideLabel = useConfig().locale?.carousel?.slide ?? ((index: number) => `Slide ${index}`)

  const goTo = useCallback(
    (index: number) => {
      setCurrent(((index % count) + count) % count)
    },
    [count],
  )

  useEffect(() => {
    if (!autoplay || count <= 1) return
    const id = setInterval(() => goTo(current + 1), autoplaySpeed)
    return () => clearInterval(id)
  }, [autoplay, autoplaySpeed, current, count, goTo])

  if (unstyled) {
    return (
      <div className={className} style={style}>
        {slides[current]}
        {dots && (
          <div>
            {slides.map((_, i) => (
              <button key={i} onClick={() => goTo(i)} aria-current={i === current}>
                {i + 1}
              </button>
            ))}
          </div>
        )}
      </div>
    )
  }

  const isVertical = dotPosition === 'left' || dotPosition === 'right'

  return (
    <div
      className={[
        'sg-carousel',
        `sg-carousel-dots-${dotPosition}`,
        isVertical ? 'sg-carousel-vertical' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      style={style}
    >
      <div className="sg-carousel-container">
        <div className="sg-carousel-track">
          {slides.map((slide, i) => (
            <div
              key={i}
              className={[
                'sg-carousel-slide',
                i === current ? 'sg-carousel-slide-active' : '',
                `sg-carousel-effect-${effect}`,
              ]
                .filter(Boolean)
                .join(' ')}
              style={
                effect === 'slide'
                  ? { transform: `translateX(${(i - current) * 100}%)` }
                  : undefined
              }
              aria-hidden={i !== current}
            >
              {slide}
            </div>
          ))}
        </div>
      </div>

      {dots && count > 1 && (
        <div
          className={['sg-carousel-dots', isVertical ? 'sg-carousel-dots-vertical' : '']
            .filter(Boolean)
            .join(' ')}
        >
          {slides.map((_, i) => (
            <button
              key={i}
              className={['sg-carousel-dot', i === current ? 'sg-carousel-dot-active' : '']
                .filter(Boolean)
                .join(' ')}
              onClick={() => goTo(i)}
              aria-label={slideLabel(i + 1)}
            />
          ))}
        </div>
      )}
    </div>
  )
}

// packages/vue/src/components/ui/Carousel.vue
<script lang="ts">
import {
  Comment,
  Fragment,
  Text,
  computed,
  defineComponent,
  h,
  onBeforeUnmount,
  ref,
  watch,
  type PropType,
  type VNode,
} from 'vue'
import { useConfig } from './ConfigProvider.vue'

export interface CarouselProps {
  /** Auto-advance slides on an interval. @default false */
  autoplay?: boolean
  /** Interval in ms between autoplay steps. @default 3000 */
  autoplaySpeed?: number
  /** Show dot navigation. @default true */
  dots?: boolean
  /** Where dots are placed. @default 'bottom' */
  dotPosition?: 'top' | 'bottom' | 'left' | 'right'
  /** Slide transition. @default 'slide' */
  effect?: 'slide' | 'fade'
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

function flatten(nodes: VNode[]): VNode[] {
  const out: VNode[] = []
  for (const node of nodes) {
    if (node.type === Comment) continue
    if (node.type === Text) continue
    if (node.type === Fragment && Array.isArray(node.children)) {
      out.push(...flatten(node.children as VNode[]))
      continue
    }
    out.push(node)
  }
  return out
}

export default defineComponent({
  name: 'SgCarousel',
  props: {
    autoplay: { type: Boolean, default: false },
    autoplaySpeed: { type: Number, default: 3000 },
    dots: { type: Boolean, default: true },
    dotPosition: {
      type: String as PropType<'top' | 'bottom' | 'left' | 'right'>,
      default: 'bottom',
    },
    effect: {
      type: String as PropType<'slide' | 'fade'>,
      default: 'slide',
    },
    unstyled: { type: Boolean, default: false },
  },
  setup(props, { slots }) {
    const current = ref(0)
    const slideCount = ref(0)
    let timer: ReturnType<typeof setInterval> | undefined

    function goTo(index: number, total: number) {
      if (total === 0) {
        current.value = 0
        return
      }
      current.value = ((index % total) + total) % total
    }

    function startAutoplay() {
      if (timer) clearInterval(timer)
      const total = slideCount.value
      if (!props.autoplay || total <= 1) return
      timer = setInterval(() => goTo(current.value + 1, total), props.autoplaySpeed)
    }

    watch(
      () => [props.autoplay, props.autoplaySpeed, slideCount.value] as const,
      () => startAutoplay(),
    )

    onBeforeUnmount(() => {
      if (timer) clearInterval(timer)
    })

    const isVertical = computed(() => props.dotPosition === 'left' || props.dotPosition === 'right')

    const cfg = useConfig()
    const slideLabel = computed(
      () => cfg.value.locale?.carousel?.slide ?? ((index: number) => `Slide ${index}`),
    )

    return () => {
      const raw = slots.default?.() ?? []
      const slides = flatten(raw)
      const count = slides.length
      if (slideCount.value !== count) {
        slideCount.value = count
      }
      if (current.value >= count && count > 0) {
        current.value = count - 1
      }

      if (props.unstyled) {
        return h('div', null, [
          slides[current.value] ? h('div', null, [slides[current.value]]) : null,
          props.dots
            ? h(
                'div',
                null,
                slides.map((_, i) =>
                  h(
                    'button',
                    {
                      key: i,
                      type: 'button',
                      'aria-current': i === current.value,
                      onClick: () => goTo(i, count),
                    },
                    String(i + 1),
                  ),
                ),
              )
            : null,
        ])
      }

      const rootClasses = [
        'sg-carousel',
        `sg-carousel-dots-${props.dotPosition}`,
        isVertical.value ? 'sg-carousel-vertical' : '',
      ]
        .filter(Boolean)
        .join(' ')

      return h('div', { class: rootClasses }, [
        h('div', { class: 'sg-carousel-container' }, [
          h(
            'div',
            { class: 'sg-carousel-track' },
            slides.map((slide, i) =>
              h(
                'div',
                {
                  key: i,
                  class: [
                    'sg-carousel-slide',
                    i === current.value ? 'sg-carousel-slide-active' : '',
                    `sg-carousel-effect-${props.effect}`,
                  ],
                  style:
                    props.effect === 'slide'
                      ? { transform: `translateX(${(i - current.value) * 100}%)` }
                      : undefined,
                  'aria-hidden': i !== current.value,
                },
                [slide],
              ),
            ),
          ),
        ]),
        props.dots && count > 1
          ? h(
              'div',
              {
                class: ['sg-carousel-dots', isVertical.value ? 'sg-carousel-dots-vertical' : ''],
              },
              slides.map((_, i) =>
                h('button', {
                  key: i,
                  type: 'button',
                  class: ['sg-carousel-dot', i === current.value ? 'sg-carousel-dot-active' : ''],
                  'aria-label': slideLabel.value(i + 1),
                  onClick: () => goTo(i, count),
                }),
              ),
            )
          : null,
      ])
    }
  },
})
</script>
