// packages/react/src/components/ui/Collapse.tsx
import { useState, useRef, useEffect, type ReactNode } from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, SizableProps } from '../../types'

/** Single collapsible section: header, body, and optional metadata. */
export interface CollapseItem {
  /** Unique key used for selection state and toggling. */
  key: string
  /** Header content shown in the panel trigger. */
  label: ReactNode
  /** Body content revealed when the panel is expanded. */
  children: ReactNode
  /** Optional content rendered beside the header (e.g. actions). */
  extra?: ReactNode
  /** When `false`, hides the expand/collapse arrow. */
  showArrow?: boolean
  /** When `true`, the panel cannot be toggled. */
  disabled?: boolean
}

/** Props for the vertical accordion-style collapse list. */
export interface CollapseProps extends BaseComponentProps, SizableProps {
  /** Panels to render, each with a stable `key`. */
  items: CollapseItem[]
  /** Controlled open keys; when set, overrides internal state. */
  activeKey?: string | string[]
  /** Initial open keys when uncontrolled. */
  defaultActiveKey?: string | string[]
  /** Called after the open set changes (controlled or uncontrolled). */
  onChange?: (activeKey: string[]) => void
  /** When `true`, only one panel may be open at a time. @default false */
  accordion?: boolean
  /** When `true`, draws a border around the collapse container. @default true */
  bordered?: boolean
  /** Placement of the expand icon relative to the header text. @default 'start' */
  expandIconPosition?: 'start' | 'end'
  /** Transparent style without panel background borders. @default false */
  ghost?: boolean
}

function toArray(val?: string | string[]): string[] {
  if (val === undefined) return []
  return Array.isArray(val) ? val : [val]
}

/**
 * Renders an expandable list of panels with optional accordion mode and styled or unstyled markup.
 */
export function Collapse({
  items,
  activeKey,
  defaultActiveKey,
  onChange,
  accordion = false,
  bordered = true,
  expandIconPosition = 'start',
  ghost = false,
  size: sizeProp,
  className,
  style,
  unstyled,
}: CollapseProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'

  const [internalActive, setInternalActive] = useState<string[]>(
    toArray(activeKey ?? defaultActiveKey),
  )
  const currentActive = activeKey !== undefined ? toArray(activeKey) : internalActive

  const toggle = (key: string) => {
    let next: string[]
    if (accordion) {
      next = currentActive.includes(key) ? [] : [key]
    } else {
      next = currentActive.includes(key)
        ? currentActive.filter((k) => k !== key)
        : [...currentActive, key]
    }
    setInternalActive(next)
    onChange?.(next)
  }

  if (unstyled) {
    return (
      <div className={className} style={style}>
        {items.map((item) => {
          const isActive = currentActive.includes(item.key)
          return (
            <div key={item.key}>
              <button
                disabled={item.disabled}
                aria-expanded={isActive}
                onClick={() => !item.disabled && toggle(item.key)}
              >
                {item.label}
                {item.extra}
              </button>
              {isActive && <div>{item.children}</div>}
            </div>
          )
        })}
      </div>
    )
  }

  const rootClasses = [
    'sg-collapse',
    bordered ? 'sg-collapse-bordered' : '',
    ghost ? 'sg-collapse-ghost' : '',
    `sg-collapse-${size}`,
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={rootClasses} style={style}>
      {items.map((item) => {
        const isActive = currentActive.includes(item.key)
        const showArrow = item.showArrow !== false
        return (
          <CollapsePanel
            key={item.key}
            item={item}
            isActive={isActive}
            showArrow={showArrow}
            expandIconPosition={expandIconPosition}
            onToggle={() => !item.disabled && toggle(item.key)}
          />
        )
      })}
    </div>
  )
}

function CollapsePanel({
  item,
  isActive,
  showArrow,
  expandIconPosition,
  onToggle,
}: {
  item: CollapseItem
  isActive: boolean
  showArrow: boolean
  expandIconPosition: 'start' | 'end'
  onToggle: () => void
}) {
  const contentRef = useRef<HTMLDivElement>(null)
  const [height, setHeight] = useState<number | undefined>(undefined)
  const firstRender = useRef(true)

  useEffect(() => {
    if (firstRender.current) {
      firstRender.current = false
      if (isActive && contentRef.current) {
        setHeight(contentRef.current.scrollHeight)
      }
      return
    }
    if (!contentRef.current) return
    if (isActive) {
      setHeight(contentRef.current.scrollHeight)
    } else {
      setHeight(contentRef.current.scrollHeight)
      requestAnimationFrame(() => {
        setHeight(0)
      })
    }
  }, [isActive])

  const handleTransitionEnd = () => {
    if (isActive && contentRef.current) {
      setHeight(undefined)
    }
  }

  const panelClasses = [
    'sg-collapse-panel',
    isActive ? 'sg-collapse-panel-active' : '',
    item.disabled ? 'sg-collapse-panel-disabled' : '',
  ]
    .filter(Boolean)
    .join(' ')

  const arrow = showArrow ? (
    <span
      className={['sg-collapse-arrow', isActive ? 'sg-collapse-arrow-open' : '']
        .filter(Boolean)
        .join(' ')}
    />
  ) : null

  return (
    <div className={panelClasses}>
      <div
        className="sg-collapse-header"
        role="button"
        tabIndex={item.disabled ? -1 : 0}
        aria-expanded={isActive}
        onClick={onToggle}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            onToggle()
          }
        }}
      >
        {expandIconPosition === 'start' && arrow}
        <span className="sg-collapse-header-text">{item.label}</span>
        {expandIconPosition === 'end' && arrow}
        {item.extra && <span className="sg-collapse-extra">{item.extra}</span>}
      </div>
      <div
        ref={contentRef}
        className="sg-collapse-content"
        style={{
          ['--sg-collapse-content-max-height' as string]:
            height !== undefined ? `${height}px` : isActive ? 'none' : '0px',
        }}
        onTransitionEnd={handleTransitionEnd}
      >
        <div className="sg-collapse-content-inner">{item.children}</div>
      </div>
    </div>
  )
}

// packages/vue/src/components/ui/Collapse.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { useConfigWithDefaults } from './ConfigProvider.vue'
import type { SizeType } from '../../types'

export interface CollapseItem {
  /** Unique key. */
  key: string
  /** Header text. */
  label: string
  /** Body text revealed when expanded. */
  content: string
  /** Optional content next to header. */
  extra?: string
  /** When `false`, hides the expand/collapse arrow. */
  showArrow?: boolean
  /** When `true`, the panel cannot be toggled. */
  disabled?: boolean
}

export interface CollapseProps {
  items: CollapseItem[]
  /** Controlled open keys. */
  activeKey?: string | string[]
  /** Initial open keys. */
  defaultActiveKey?: string | string[]
  /** Only one panel open at a time. */
  accordion?: boolean
  /** Draw a border. @default true */
  bordered?: boolean
  /** Placement of expand icon. @default 'start' */
  expandIconPosition?: 'start' | 'end'
  /** Transparent style. */
  ghost?: boolean
  /** Component size variant. */
  size?: SizeType
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<CollapseProps>(), {
  accordion: false,
  bordered: true,
  expandIconPosition: 'start',
  ghost: false,
})

const emit = defineEmits<{
  (e: 'change', activeKey: string[]): void
}>()

defineSlots<{
  panel(props: { item: CollapseItem }): unknown
}>()

const { resolvedSize } = useConfigWithDefaults({ size: undefined }, {})
const realSize = computed<SizeType>(() => props.size ?? resolvedSize.value)

function toArray(val?: string | string[]): string[] {
  if (val === undefined) return []
  return Array.isArray(val) ? val : [val]
}

const internalActive = ref<string[]>(toArray(props.activeKey ?? props.defaultActiveKey))
const currentActive = computed(() =>
  props.activeKey !== undefined ? toArray(props.activeKey) : internalActive.value,
)

function toggle(key: string) {
  let next: string[]
  if (props.accordion) {
    next = currentActive.value.includes(key) ? [] : [key]
  } else {
    next = currentActive.value.includes(key)
      ? currentActive.value.filter((k) => k !== key)
      : [...currentActive.value, key]
  }
  internalActive.value = next
  emit('change', next)
}

const rootClasses = computed(() =>
  [
    'sg-collapse',
    props.bordered ? 'sg-collapse-bordered' : '',
    props.ghost ? 'sg-collapse-ghost' : '',
    `sg-collapse-${realSize.value}`,
  ]
    .filter(Boolean)
    .join(' '),
)

function panelClasses(item: CollapseItem) {
  const isActive = currentActive.value.includes(item.key)
  return [
    'sg-collapse-panel',
    isActive ? 'sg-collapse-panel-active' : '',
    item.disabled ? 'sg-collapse-panel-disabled' : '',
  ]
    .filter(Boolean)
    .join(' ')
}

function arrowClasses(item: CollapseItem) {
  const isActive = currentActive.value.includes(item.key)
  return ['sg-collapse-arrow', isActive ? 'sg-collapse-arrow-open' : ''].filter(Boolean).join(' ')
}

function isOpen(key: string) {
  return currentActive.value.includes(key)
}

function onKeyDown(e: KeyboardEvent, item: CollapseItem) {
  if (item.disabled) return
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault()
    toggle(item.key)
  }
}

/* --- Per-panel animated max-height bookkeeping --- */

const contentRefs = ref<Map<string, HTMLElement>>(new Map())
const measuredHeights = ref<Map<string, number | null>>(new Map())

function setContentRef(key: string, el: Element | null) {
  if (el) contentRefs.value.set(key, el as HTMLElement)
  else contentRefs.value.delete(key)
}

function contentStyle(item: CollapseItem) {
  const measured = measuredHeights.value.get(item.key)
  const open = isOpen(item.key)
  let value: string
  if (measured !== undefined && measured !== null) value = `${measured}px`
  else if (open) value = 'none'
  else value = '0px'
  return { '--sg-collapse-content-max-height': value } as Record<string, string>
}

function syncHeight(item: CollapseItem) {
  const el = contentRefs.value.get(item.key)
  if (!el) return
  if (isOpen(item.key)) {
    measuredHeights.value.set(item.key, el.scrollHeight)
  } else {
    measuredHeights.value.set(item.key, el.scrollHeight)
    requestAnimationFrame(() => {
      measuredHeights.value.set(item.key, 0)
      measuredHeights.value = new Map(measuredHeights.value)
    })
  }
  measuredHeights.value = new Map(measuredHeights.value)
}

function onTransitionEnd(item: CollapseItem) {
  if (isOpen(item.key)) {
    measuredHeights.value.set(item.key, null)
    measuredHeights.value = new Map(measuredHeights.value)
  }
}

onMounted(() => {
  // Prime measurements for any panels that start open so their CSS
  // max-height reflects the actual scrollHeight (Vue mounted the DOM
  // synchronously, so refs are populated by this tick).
  for (const item of props.items) {
    if (isOpen(item.key)) {
      const el = contentRefs.value.get(item.key)
      if (el) {
        measuredHeights.value.set(item.key, el.scrollHeight)
      }
    }
  }
  measuredHeights.value = new Map(measuredHeights.value)
})

watch(currentActive, (next, prev) => {
  const prevSet = new Set(prev ?? [])
  const nextSet = new Set(next ?? [])
  const changed: string[] = []
  for (const item of props.items) {
    const was = prevSet.has(item.key)
    const now = nextSet.has(item.key)
    if (was !== now) changed.push(item.key)
  }
  if (changed.length === 0) return
  void nextTick(() => {
    for (const key of changed) {
      const item = props.items.find((i) => i.key === key)
      if (item) syncHeight(item)
    }
  })
})
</script>

<template>
  <div v-if="unstyled">
    <div v-for="item in items" :key="item.key">
      <button
        type="button"
        :disabled="item.disabled"
        :aria-expanded="isOpen(item.key)"
        @click="!item.disabled && toggle(item.key)"
      >
        {{ item.label }}
        <span v-if="item.extra">{{ item.extra }}</span>
      </button>
      <div v-if="isOpen(item.key)">
        <slot name="panel" :item="item">{{ item.content }}</slot>
      </div>
    </div>
  </div>
  <div v-else :class="rootClasses">
    <div v-for="item in items" :key="item.key" :class="panelClasses(item)">
      <div
        class="sg-collapse-header"
        role="button"
        :tabindex="item.disabled ? -1 : 0"
        :aria-expanded="isOpen(item.key)"
        @click="!item.disabled && toggle(item.key)"
        @keydown="onKeyDown($event, item)"
      >
        <span
          v-if="expandIconPosition === 'start' && item.showArrow !== false"
          :class="arrowClasses(item)"
        />
        <span class="sg-collapse-header-text">{{ item.label }}</span>
        <span
          v-if="expandIconPosition === 'end' && item.showArrow !== false"
          :class="arrowClasses(item)"
        />
        <span v-if="item.extra" class="sg-collapse-extra">{{ item.extra }}</span>
      </div>
      <div
        :ref="(el) => setContentRef(item.key, el as Element | null)"
        class="sg-collapse-content"
        :style="contentStyle(item)"
        @transitionend="onTransitionEnd(item)"
      >
        <div class="sg-collapse-content-inner">
          <slot name="panel" :item="item">{{ item.content }}</slot>
        </div>
      </div>
    </div>
  </div>
</template>
