// packages/react/src/components/ui/Dropdown.tsx
import React, { useState, useRef, useEffect, useId } from 'react'
import { Transition } from './Transition'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps } from '../../types'

/** One entry in the dropdown menu: action row or non-interactive divider. */
export interface DropdownItem {
  /** Unique key passed to `onSelect` when the row is activated. */
  key: string
  /** Visible menu row content. */
  label: React.ReactNode
  /** When true, the row cannot be selected. */
  disabled?: boolean
  /** When true, styles the row as a destructive action. */
  danger?: boolean
  /** When true, renders a separator instead of a selectable row. */
  divider?: boolean
}

/** Props for the trigger + anchored menu dropdown. */
export interface DropdownProps extends BaseComponentProps {
  /** Menu rows and optional dividers. */
  items: DropdownItem[]
  /** Called with the item `key` after a successful selection. */
  onSelect?: (key: string) => void
  /** Opens the menu on click or hover. @default 'hover' */
  trigger?: 'click' | 'hover'
  /** Menu position relative to the trigger. @default 'bottomLeft' */
  placement?: 'bottomLeft' | 'bottomRight' | 'topLeft' | 'topRight'
  /** When true, ignores open/close and selection; uses ConfigProvider when omitted. */
  disabled?: boolean
  /** Element rendered as the menu trigger. */
  children: React.ReactElement
}

/**
 * Anchored menu opened by hover or click, with keyboard support and outside-click close.
 * Styled variant uses a slide transition; unstyled variant renders a minimal structure.
 */
export function Dropdown({
  items,
  onSelect,
  trigger = 'hover',
  placement = 'bottomLeft',
  disabled: disabledProp,
  children,
  className,
  unstyled,
}: DropdownProps) {
  const config = useConfig()
  const disabled = disabledProp ?? config.disabled ?? false

  const [open, setOpen] = useState(false)
  const [focusedIndex, setFocusedIndex] = useState(-1)
  const ref = useRef<HTMLDivElement>(null)
  const timerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined)
  const menuId = useId()

  useEffect(() => {
    if (!open) return
    const handleClick = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setOpen(false)
      }
    }
    document.addEventListener('mousedown', handleClick)
    return () => document.removeEventListener('mousedown', handleClick)
  }, [open])

  useEffect(() => {
    if (!open) setFocusedIndex(-1)
  }, [open])

  const getNextMenuIndex = (current: number, direction: 1 | -1) => {
    let next = current
    for (let i = 0; i < items.length; i++) {
      next = (next + direction + items.length) % items.length
      if (!items[next].divider && !items[next].disabled) return next
    }
    return current
  }

  const handleMouseEnter = () => {
    if (trigger !== 'hover' || disabled) return
    clearTimeout(timerRef.current)
    setOpen(true)
  }

  const handleMouseLeave = () => {
    if (trigger !== 'hover') return
    timerRef.current = setTimeout(() => setOpen(false), 100)
  }

  const handleClick = () => {
    if (trigger !== 'click' || disabled) return
    setOpen(!open)
  }

  const handleSelect = (item: DropdownItem) => {
    if (item.disabled) return
    setOpen(false)
    onSelect?.(item.key)
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (disabled) return
    switch (e.key) {
      case 'Enter':
      case ' ':
        e.preventDefault()
        if (open && focusedIndex >= 0 && !items[focusedIndex].divider) {
          handleSelect(items[focusedIndex])
        } else {
          setOpen(!open)
        }
        break
      case 'Escape':
        e.preventDefault()
        setOpen(false)
        break
      case 'ArrowDown':
        e.preventDefault()
        if (!open) setOpen(true)
        else setFocusedIndex((i) => getNextMenuIndex(i, 1))
        break
      case 'ArrowUp':
        e.preventDefault()
        if (!open) setOpen(true)
        else setFocusedIndex((i) => getNextMenuIndex(i, -1))
        break
      case 'Home':
        if (open) {
          e.preventDefault()
          setFocusedIndex(getNextMenuIndex(-1, 1))
        }
        break
      case 'End':
        if (open) {
          e.preventDefault()
          setFocusedIndex(getNextMenuIndex(items.length, -1))
        }
        break
    }
  }

  if (unstyled) {
    return (
      <div ref={ref} className={className} style={{ position: 'relative', display: 'inline-block' }}>
        <div onClick={handleClick} onMouseEnter={handleMouseEnter} onMouseLeave={handleMouseLeave}>
          {children}
        </div>
        {open && (
          <div onMouseEnter={handleMouseEnter} onMouseLeave={handleMouseLeave}>
            {items.map((item) =>
              item.divider ? <hr key={item.key} /> : (
                <div key={item.key} onClick={() => handleSelect(item)}>{item.label}</div>
              )
            )}
          </div>
        )}
      </div>
    )
  }

  return (
    <div
      ref={ref}
      className={['sg-dropdown-wrapper', className].filter(Boolean).join(' ')}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      <div
        className="sg-dropdown-trigger"
        aria-expanded={open}
        aria-haspopup="menu"
        aria-controls={menuId}
        tabIndex={disabled ? -1 : 0}
        onClick={handleClick}
        onKeyDown={handleKeyDown}
      >
        {children}
      </div>
      <Transition visible={open} name="sg-slide-up" unmountOnExit>
        <div
          className={`sg-dropdown sg-dropdown-${placement}`}
          role="menu"
          id={menuId}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
        >
          {items.map((item, idx) =>
            item.divider ? (
              <div key={item.key} className="sg-dropdown-divider" role="separator" />
            ) : (
              <div
                key={item.key}
                role="menuitem"
                className={[
                  'sg-dropdown-item',
                  item.disabled ? 'sg-dropdown-item-disabled' : '',
                  item.danger ? 'sg-dropdown-item-danger' : '',
                  idx === focusedIndex ? 'sg-dropdown-item-focused' : '',
                ].filter(Boolean).join(' ')}
                onClick={() => handleSelect(item)}
              >
                {item.label}
              </div>
            )
          )}
        </div>
      </Transition>
    </div>
  )
}

// packages/vue/src/components/ui/Dropdown.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch, type PropType } from 'vue'
import { useConfigWithDefaults } from './ConfigProvider.vue'
import SgTransition from './Transition.vue'

let uid = 0
function genId() {
  return `sg-dropdown-${++uid}`
}

export interface DropdownItem {
  /** Unique key passed when activated. */
  key: string
  /** Visible menu row content. */
  label: string
  /** When true, the row cannot be selected. */
  disabled?: boolean
  /** When true, styles the row as destructive. */
  danger?: boolean
  /** When true, renders a separator instead of a selectable row. */
  divider?: boolean
}

export interface DropdownProps {
  items: DropdownItem[]
  trigger?: 'click' | 'hover'
  placement?: 'bottomLeft' | 'bottomRight' | 'topLeft' | 'topRight'
  disabled?: boolean
  unstyled?: boolean
}

const props = defineProps({
  items: {
    type: Array as PropType<DropdownItem[]>,
    required: true,
  },
  trigger: {
    type: String as PropType<'click' | 'hover'>,
    default: 'hover',
  },
  placement: {
    type: String as PropType<'bottomLeft' | 'bottomRight' | 'topLeft' | 'topRight'>,
    default: 'bottomLeft',
  },
  disabled: { type: Boolean, default: undefined },
  unstyled: { type: Boolean, default: false },
})

const emit = defineEmits<{
  (e: 'select', key: string): void
}>()

defineSlots<{
  default(props: Record<string, never>): unknown
  /** Custom row renderer (replaces `item.label` rendering). */
  item(props: { item: DropdownItem; index: number; focused: boolean }): unknown
}>()

const { resolvedDisabled } = useConfigWithDefaults({ disabled: undefined }, {})
const disabled = computed(() => props.disabled ?? resolvedDisabled.value)

const open = ref(false)
const focusedIndex = ref(-1)
const wrapperRef = ref<HTMLElement | null>(null)
let timer: ReturnType<typeof setTimeout> | undefined

const menuId = genId()

function getNextMenuIndex(current: number, direction: 1 | -1) {
  const items = props.items
  let next = current
  for (let i = 0; i < items.length; i++) {
    next = (next + direction + items.length) % items.length
    if (!items[next].divider && !items[next].disabled) return next
  }
  return current
}

function handleMouseEnter() {
  if (props.trigger !== 'hover' || disabled.value) return
  if (timer) clearTimeout(timer)
  open.value = true
}

function handleMouseLeave() {
  if (props.trigger !== 'hover') return
  timer = setTimeout(() => (open.value = false), 100)
}

function handleClick() {
  if (props.trigger !== 'click' || disabled.value) return
  open.value = !open.value
}

function handleSelect(item: DropdownItem) {
  if (item.disabled) return
  open.value = false
  emit('select', item.key)
}

function handleKeyDown(e: KeyboardEvent) {
  if (disabled.value) return
  switch (e.key) {
    case 'Enter':
    case ' ':
      e.preventDefault()
      if (open.value && focusedIndex.value >= 0 && !props.items[focusedIndex.value].divider) {
        handleSelect(props.items[focusedIndex.value])
      } else {
        open.value = !open.value
      }
      break
    case 'Escape':
      e.preventDefault()
      open.value = false
      break
    case 'ArrowDown':
      e.preventDefault()
      if (!open.value) open.value = true
      else focusedIndex.value = getNextMenuIndex(focusedIndex.value, 1)
      break
    case 'ArrowUp':
      e.preventDefault()
      if (!open.value) open.value = true
      else focusedIndex.value = getNextMenuIndex(focusedIndex.value, -1)
      break
    case 'Home':
      if (open.value) {
        e.preventDefault()
        focusedIndex.value = getNextMenuIndex(-1, 1)
      }
      break
    case 'End':
      if (open.value) {
        e.preventDefault()
        focusedIndex.value = getNextMenuIndex(props.items.length, -1)
      }
      break
  }
}

function handleDocumentClick(e: MouseEvent) {
  if (wrapperRef.value && !wrapperRef.value.contains(e.target as Node)) {
    open.value = false
  }
}

watch(
  open,
  (next) => {
    if (next) {
      document.addEventListener('mousedown', handleDocumentClick)
    } else {
      focusedIndex.value = -1
      document.removeEventListener('mousedown', handleDocumentClick)
    }
  },
  { immediate: true },
)

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleDocumentClick)
  if (timer) clearTimeout(timer)
})

const menuClasses = computed(() => `sg-dropdown sg-dropdown-${props.placement}`)
</script>

<template>
  <div v-if="unstyled" ref="wrapperRef" style="position: relative; display: inline-block">
    <div @click="handleClick" @mouseenter="handleMouseEnter" @mouseleave="handleMouseLeave">
      <slot />
    </div>
    <div v-if="open" @mouseenter="handleMouseEnter" @mouseleave="handleMouseLeave">
      <template v-for="(item, idx) in items" :key="item.key">
        <hr v-if="item.divider" />
        <div v-else @click="handleSelect(item)">
          <slot name="item" :item="item" :index="idx" :focused="idx === focusedIndex">
            {{ item.label }}
          </slot>
        </div>
      </template>
    </div>
  </div>
  <div
    v-else
    ref="wrapperRef"
    class="sg-dropdown-wrapper"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <div
      class="sg-dropdown-trigger"
      :aria-expanded="open"
      aria-haspopup="menu"
      :aria-controls="menuId"
      :tabindex="disabled ? -1 : 0"
      @click="handleClick"
      @keydown="handleKeyDown"
    >
      <slot />
    </div>
    <SgTransition :visible="open" name="sg-slide-up">
      <div
        :class="menuClasses"
        role="menu"
        :id="menuId"
        @mouseenter="handleMouseEnter"
        @mouseleave="handleMouseLeave"
      >
        <template v-for="(item, idx) in items" :key="item.key">
          <div v-if="item.divider" class="sg-dropdown-divider" role="separator" />
          <div
            v-else
            role="menuitem"
            :class="[
              'sg-dropdown-item',
              item.disabled ? 'sg-dropdown-item-disabled' : '',
              item.danger ? 'sg-dropdown-item-danger' : '',
              idx === focusedIndex ? 'sg-dropdown-item-focused' : '',
            ]"
            @click="handleSelect(item)"
          >
            <slot name="item" :item="item" :index="idx" :focused="idx === focusedIndex">
              {{ item.label }}
            </slot>
          </div>
        </template>
      </div>
    </SgTransition>
  </div>
</template>
