// packages/react/src/components/ui/Input.tsx
import React from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps, SizableProps } from '../../types'
import { Spin } from './Spin'

/** Props for the Input component. */
export interface InputProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Controlled input value. */
  value?: string
  /** Uncontrolled initial value. */
  defaultValue?: string
  /** Placeholder text when the field is empty. */
  placeholder?: string
  /** Native HTML input type. @default 'text' */
  type?: 'text' | 'email' | 'password' | 'number'
  /**
   * Marks the field as read-only. The value is selectable and submitted
   * but cannot be edited. Sets the HTML `readonly` attribute,
   * `aria-readonly="true"`, and adds the `sg-input-readonly` modifier class.
   * @default false
   */
  readOnly?: boolean
  /** DOM id forwarded to the underlying `<input>`. */
  id?: string
  /**
   * When true, renders a clear (×) button while the field has a value.
   * Disabled and read-only fields hide the button. @default false
   */
  allowClear?: boolean
  /**
   * Validation status badge. Adds `sg-input-wrapper-status-{status}` and
   * `sg-input-status-{status}` modifier classes and sets `aria-invalid` when
   * `error`.
   */
  status?: 'error' | 'warning'
  /** Optional content rendered before the `<input>` (e.g. icon). */
  prefix?: React.ReactNode
  /** Optional content rendered after the `<input>` (e.g. icon, unit). */
  suffix?: React.ReactNode
  /** Exposes invalid state to assistive technologies. */
  'aria-invalid'?: boolean | 'false' | 'true' | 'grammar' | 'spelling'
  /** Marks the field as required for assistive technologies. */
  'aria-required'?: boolean | 'false' | 'true'
  /** Connects the input to description / error nodes for assistive technologies. */
  'aria-describedby'?: string
  /** Called when the text value changes. */
  onChange?: (value: string) => void
  /** Called when the input loses focus. */
  onBlur?: () => void
  /** Called when the input gains focus. */
  onFocus?: () => void
  /** Called when the user activates the built-in clear button. */
  onClear?: () => void
}

/** Single-line text input with optional loading indicator and configurable HTML type. */
export function Input({
  value,
  defaultValue,
  placeholder,
  type = 'text',
  readOnly = false,
  size: sizeProp,
  disabled: disabledProp,
  loading,
  allowClear = false,
  status,
  prefix,
  suffix,
  onChange,
  onBlur,
  onFocus,
  onClear,
  'aria-invalid': ariaInvalid,
  'aria-required': ariaRequired,
  'aria-describedby': ariaDescribedBy,
  id,
  className,
  style,
  unstyled,
}: InputProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const disabled = disabledProp ?? config.disabled ?? false

  const [internalValue, setInternalValue] = React.useState<string>(defaultValue ?? '')
  const currentValue = value ?? internalValue
  const isControlled = value !== undefined

  const wrapperClasses = unstyled
    ? (className ?? '')
    : [
        'sg-input-wrapper',
        `sg-input-wrapper-${size}`,
        loading ? 'sg-input-wrapper-loading' : '',
        readOnly ? 'sg-input-wrapper-readonly' : '',
        status ? `sg-input-wrapper-status-${status}` : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')

  const inputClasses = unstyled
    ? ''
    : [
        'sg-input',
        `sg-input-${size}`,
        readOnly ? 'sg-input-readonly' : '',
        status ? `sg-input-status-${status}` : '',
      ]
        .filter(Boolean)
        .join(' ')

  const clearLabel = config.locale?.input?.clear ?? 'Clear'
  const showClear = allowClear && !disabled && !readOnly && !loading && currentValue !== ''

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!isControlled) setInternalValue(e.target.value)
    onChange?.(e.target.value)
  }

  const handleClear = () => {
    if (!isControlled) setInternalValue('')
    onChange?.('')
    onClear?.()
  }

  const resolvedAriaInvalid = ariaInvalid ?? (status === 'error' ? true : undefined)

  return (
    <span className={wrapperClasses} style={style}>
      {prefix && <span className="sg-input-prefix">{prefix}</span>}
      <input
        id={id}
        type={type}
        className={inputClasses}
        value={currentValue}
        placeholder={placeholder}
        disabled={disabled || loading}
        readOnly={readOnly}
        aria-invalid={resolvedAriaInvalid}
        aria-required={ariaRequired}
        aria-readonly={readOnly || undefined}
        aria-describedby={ariaDescribedBy}
        onChange={handleChange}
        onBlur={onBlur}
        onFocus={onFocus}
      />
      {showClear && (
        <button
          type="button"
          className="sg-input-clear"
          aria-label={clearLabel}
          onClick={handleClear}
        >
          ×
        </button>
      )}
      {loading && <Spin size="small" unstyled={unstyled} />}
      {suffix && <span className="sg-input-suffix">{suffix}</span>}
    </span>
  )
}

// packages/vue/src/components/ui/Input.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue'
import { useConfig } from './ConfigProvider.vue'

export interface InputProps {
  /** v-model value (Vue idiom) — alias for `value`. */
  modelValue?: string
  /** Compat alias for `modelValue` — emits `change` like React's onChange. */
  value?: string
  /** Placeholder text when the field is empty. */
  placeholder?: string
  /** Native input type. */
  type?: 'text' | 'email' | 'password' | 'number'
  /** Size token. */
  size?: 'small' | 'middle' | 'large'
  /** Disables editing. */
  disabled?: boolean
  /** Marks the field as read-only. */
  readOnly?: boolean
  /** Optional input id forwarded to the underlying `<input>`. */
  id?: string
  /** Whether to render a clear button. */
  allowClear?: boolean
  /** Validation status badge. */
  status?: 'error' | 'warning'
  /** Strips built-in styling. */
  unstyled?: boolean
  /** Shows a loading spinner. */
  loading?: boolean
  /**
   * Exposes invalid state to assistive technologies. Accepts a string token
   * (`'true'` / `'false'` / `'grammar'` / `'spelling'`); the prop is
   * intentionally string-only so Vue's Boolean prop coercion does not
   * default it to `false` when the consumer omits it. Pass strings — e.g.
   * `aria-invalid="true"`.
   */
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling'
  /** Marks the field as required for assistive technologies. */
  ariaRequired?: 'false' | 'true'
  /** Connects the input to description / error nodes for assistive technologies. */
  ariaDescribedby?: string
}

const props = withDefaults(defineProps<InputProps>(), {
  modelValue: '',
  type: 'text',
  size: 'middle',
  disabled: false,
  readOnly: false,
  allowClear: false,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'change', value: string): void
  (e: 'focus', evt: FocusEvent): void
  (e: 'blur', evt: FocusEvent): void
  (e: 'clear'): void
}>()

defineSlots<{
  prefix(props: Record<string, never>): unknown
  suffix(props: Record<string, never>): unknown
}>()

const currentValue = computed(() => props.value ?? props.modelValue ?? '')

const wrapperClasses = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-input-wrapper',
        `sg-input-wrapper-${props.size}`,
        props.loading ? 'sg-input-wrapper-loading' : '',
        props.readOnly ? 'sg-input-wrapper-readonly' : '',
        props.status ? `sg-input-wrapper-status-${props.status}` : '',
      ]
        .filter(Boolean)
        .join(' '),
)

const inputClasses = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-input',
        `sg-input-${props.size}`,
        props.readOnly ? 'sg-input-readonly' : '',
        props.status ? `sg-input-status-${props.status}` : '',
      ]
        .filter(Boolean)
        .join(' '),
)

function onInput(e: Event) {
  const target = e.target as HTMLInputElement
  emit('update:modelValue', target.value)
  emit('change', target.value)
}

function onFocus(e: FocusEvent) {
  emit('focus', e)
}

function onBlur(e: FocusEvent) {
  emit('blur', e)
}

function clear() {
  emit('update:modelValue', '')
  emit('change', '')
  emit('clear')
}

const showClear = computed(
  () => props.allowClear && !props.disabled && !props.readOnly && !!currentValue.value,
)

const slots = useSlots()
const hasPrefix = computed(() => Boolean(slots.prefix))
const hasSuffix = computed(() => Boolean(slots.suffix))

const cfg = useConfig()
const clearLabel = computed(() => cfg.value.locale?.input?.clear ?? 'Clear')
</script>

<template>
  <span :class="wrapperClasses">
    <span v-if="hasPrefix" class="sg-input-prefix">
      <slot name="prefix" />
    </span>
    <input
      :id="id"
      :type="type"
      :class="inputClasses"
      :value="currentValue"
      :placeholder="placeholder"
      :disabled="disabled || loading"
      :readonly="readOnly"
      :aria-readonly="readOnly || undefined"
      :aria-invalid="ariaInvalid ?? (status === 'error' || undefined)"
      :aria-required="ariaRequired"
      :aria-describedby="ariaDescribedby"
      @input="onInput"
      @focus="onFocus"
      @blur="onBlur"
    />
    <button
      v-if="showClear"
      type="button"
      class="sg-input-clear"
      :aria-label="clearLabel"
      @click="clear"
    >
      ×
    </button>
    <span v-if="loading && !unstyled" class="sg-spin sg-spin-small" aria-hidden="true" />
    <span v-if="hasSuffix" class="sg-input-suffix">
      <slot name="suffix" />
    </span>
  </span>
</template>
