// packages/react/src/components/ui/InputNumber.tsx
import React from 'react'
import { Spin } from './Spin'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps, SizableProps } from '../../types'

/** Props for the InputNumber component. */
export interface InputNumberProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Controlled numeric value. */
  value?: number
  /** Uncontrolled initial value. */
  defaultValue?: number
  /** Lower bound applied on change and via stepper. */
  min?: number
  /** Upper bound applied on change and via stepper. */
  max?: number
  /** Amount added or subtracted by the stepper buttons. @default 1 */
  step?: number
  /** Decimal places enforced after clamping. */
  precision?: number
  /** Placeholder when the field has no value. */
  placeholder?: string
  /** Called with the clamped number or null when the field is cleared. */
  onChange?: (value: number | null) => void
  /** Called when the input loses focus. */
  onBlur?: () => void
}

/** Numeric field with +/- controls, optional bounds, precision, and loading state. */
export function InputNumber({
  value,
  defaultValue,
  min,
  max,
  step = 1,
  precision,
  disabled: disabledProp,
  loading,
  placeholder,
  size: sizeProp,
  onChange,
  onBlur,
  className,
  style,
  unstyled,
}: InputNumberProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const disabled = disabledProp ?? config.disabled ?? false

  const [internalValue, setInternalValue] = React.useState<number | null>(
    value ?? defaultValue ?? null
  )
  const currentValue = value ?? internalValue

  const clamp = (v: number): number => {
    let result = v
    if (min !== undefined && result < min) result = min
    if (max !== undefined && result > max) result = max
    if (precision !== undefined) result = Number(result.toFixed(precision))
    return result
  }

  const update = (v: number | null) => {
    const clamped = v !== null ? clamp(v) : null
    setInternalValue(clamped)
    onChange?.(clamped)
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const raw = e.target.value
    if (raw === '' || raw === '-') {
      setInternalValue(null)
      onChange?.(null)
      return
    }
    const num = Number(raw)
    if (!isNaN(num)) update(num)
  }

  const increment = () => {
    if (disabled || loading) return
    update((currentValue ?? 0) + step)
  }

  const decrement = () => {
    if (disabled || loading) return
    update((currentValue ?? 0) - step)
  }

  const wrapperClass = unstyled
    ? className ?? ''
    : [
        'sg-input-number',
        `sg-input-number-${size}`,
        loading ? 'sg-input-number-loading' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')

  return (
    <span className={wrapperClass} style={style}>
      <button
        className={unstyled ? '' : 'sg-input-number-btn sg-input-number-minus'}
        onClick={decrement}
        disabled={disabled || loading || (min !== undefined && (currentValue ?? 0) <= min)}
        tabIndex={-1}
      >
        −
      </button>
      <input
        type="text"
        inputMode="numeric"
        role="spinbutton"
        aria-valuemin={min}
        aria-valuemax={max}
        aria-valuenow={currentValue ?? undefined}
        className={unstyled ? '' : 'sg-input-number-input'}
        value={currentValue ?? ''}
        placeholder={placeholder}
        disabled={disabled || loading}
        onChange={handleChange}
        onBlur={onBlur}
      />
      <button
        className={unstyled ? '' : 'sg-input-number-btn sg-input-number-plus'}
        onClick={increment}
        disabled={disabled || loading || (max !== undefined && (currentValue ?? 0) >= max)}
        tabIndex={-1}
      >
        +
      </button>
      {loading && <Spin size="small" unstyled={unstyled} />}
    </span>
  )
}

// packages/vue/src/components/ui/InputNumber.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useConfigWithDefaults } from './ConfigProvider.vue'

export interface InputNumberProps {
  /** v-model binding (Vue idiom). */
  modelValue?: number | null
  /** Compat alias for `modelValue`. */
  value?: number | null
  /** Initial value when uncontrolled. */
  defaultValue?: number
  /** Lower bound. */
  min?: number
  /** Upper bound. */
  max?: number
  /** Stepper increment. */
  step?: number
  /** Decimal precision. */
  precision?: number
  /** Placeholder text. */
  placeholder?: string
  /** Disables editing. */
  disabled?: boolean
  /** Shows a loading spinner. */
  loading?: boolean
  /** Size token. */
  size?: 'small' | 'middle' | 'large'
  /** Strips built-in styling. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<InputNumberProps>(), {
  step: 1,
  size: 'middle',
  disabled: undefined,
  loading: false,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: number | null): void
  (e: 'change', value: number | null): void
  (e: 'blur'): void
}>()

const { resolvedDisabled } = useConfigWithDefaults({ disabled: props.disabled }, {})

const initial: number | null = props.modelValue ?? props.value ?? props.defaultValue ?? null
const internalValue = ref<number | null>(initial)

watch(
  () => props.modelValue ?? props.value,
  (v) => {
    if (v !== undefined) internalValue.value = v
  },
)

const currentValue = computed<number | null>(
  () => (props.modelValue ?? props.value ?? internalValue.value) as number | null,
)

const wrapperClass = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-input-number',
        `sg-input-number-${props.size}`,
        props.loading ? 'sg-input-number-loading' : '',
      ]
        .filter(Boolean)
        .join(' '),
)

function clamp(v: number): number {
  let result = v
  if (props.min !== undefined && result < props.min) result = props.min
  if (props.max !== undefined && result > props.max) result = props.max
  if (props.precision !== undefined) result = Number(result.toFixed(props.precision))
  return result
}

function update(v: number | null) {
  const next = v !== null ? clamp(v) : null
  internalValue.value = next
  emit('update:modelValue', next)
  emit('change', next)
}

function onInput(e: Event) {
  const raw = (e.target as HTMLInputElement).value
  if (raw === '' || raw === '-') {
    internalValue.value = null
    emit('update:modelValue', null)
    emit('change', null)
    return
  }
  const num = Number(raw)
  if (!isNaN(num)) update(num)
}

function increment() {
  if (resolvedDisabled.value || props.loading) return
  update((currentValue.value ?? 0) + props.step)
}

function decrement() {
  if (resolvedDisabled.value || props.loading) return
  update((currentValue.value ?? 0) - props.step)
}

const minDisabled = computed(
  () => props.min !== undefined && (currentValue.value ?? 0) <= props.min,
)
const maxDisabled = computed(
  () => props.max !== undefined && (currentValue.value ?? 0) >= props.max,
)
</script>

<template>
  <span :class="wrapperClass">
    <button
      :class="unstyled ? '' : 'sg-input-number-btn sg-input-number-minus'"
      :disabled="resolvedDisabled || loading || minDisabled"
      tabindex="-1"
      @click="decrement"
    >
      −
    </button>
    <input
      type="text"
      inputmode="numeric"
      role="spinbutton"
      :aria-valuemin="min"
      :aria-valuemax="max"
      :aria-valuenow="currentValue ?? undefined"
      :class="unstyled ? '' : 'sg-input-number-input'"
      :value="currentValue ?? ''"
      :placeholder="placeholder"
      :disabled="resolvedDisabled || loading"
      @input="onInput"
      @blur="emit('blur')"
    />
    <button
      :class="unstyled ? '' : 'sg-input-number-btn sg-input-number-plus'"
      :disabled="resolvedDisabled || loading || maxDisabled"
      tabindex="-1"
      @click="increment"
    >
      +
    </button>
    <span v-if="loading && !unstyled" class="sg-spin sg-spin-small" aria-hidden="true" />
  </span>
</template>
