// packages/react/src/components/ui/PinInput.tsx
import { useState, useRef, useCallback, useId } from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps, SizableProps } from '../../types'

/** Props for the multi-cell PIN or OTP code input. */
export interface PinInputProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Number of character cells. @default 6 */
  length?: number
  /** Controlled combined string value (padded/truncated to `length`). */
  value?: string
  /** Initial combined string when uncontrolled. @default '' */
  defaultValue?: string
  /** Use password masking for each cell. @default false */
  mask?: boolean
  /** Allowed character set per cell. @default 'numeric' */
  type?: 'numeric' | 'alphanumeric'
  /** Placeholder shown in empty styled cells. @default '○' */
  placeholder?: string
  /** Focus the first cell on mount. @default false */
  autoFocus?: boolean
  /** Fired once all cells are filled (non-space characters). */
  onComplete?: (value: string) => void
  /** Fired on every change with the trimmed combined value. */
  onChange?: (value: string) => void
  /** Accessible name for the input group. @default 'PIN input' */
  'aria-label'?: string
}

/**
 * Fixed-length segmented input for PINs or one-time codes, with paste and arrow-key navigation.
 */
export function PinInput({
  length = 6,
  value,
  defaultValue = '',
  mask = false,
  type = 'numeric',
  placeholder = '○',
  autoFocus = false,
  size: sizeProp,
  disabled: disabledProp,
  loading,
  onComplete,
  onChange,
  className,
  style,
  unstyled,
  'aria-label': ariaLabelProp,
}: PinInputProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const disabled = disabledProp ?? config.disabled ?? false
  const ariaLabel = ariaLabelProp ?? config.locale?.pinInput?.ariaLabel ?? 'PIN input'
  const id = useId()

  const pad = (s: string) => s.padEnd(length, '').slice(0, length)
  const [internal, setInternal] = useState(() => pad(defaultValue))
  const current = value !== undefined ? pad(value) : internal
  const refs = useRef<(HTMLInputElement | null)[]>([])

  const pattern = type === 'numeric' ? /^\d$/ : /^[a-zA-Z0-9]$/

  const update = useCallback(
    (next: string) => {
      setInternal(next)
      onChange?.(next.replace(/\s/g, ''))
      const trimmed = next.replace(/\s/g, '')
      if (trimmed.length === length) onComplete?.(trimmed)
    },
    [onChange, onComplete, length],
  )

  const focusAt = (i: number) => {
    if (i >= 0 && i < length) refs.current[i]?.focus()
  }

  const handleChange = (index: number, char: string) => {
    if (!pattern.test(char)) return
    const arr = current.split('')
    arr[index] = char
    update(arr.join(''))
    focusAt(index + 1)
  }

  const handleKeyDown = (index: number, e: React.KeyboardEvent) => {
    if (e.key === 'Backspace') {
      e.preventDefault()
      const arr = current.split('')
      if (arr[index] !== ' ') {
        arr[index] = ' '
        update(arr.join(''))
      } else {
        focusAt(index - 1)
      }
    } else if (e.key === 'ArrowLeft') {
      focusAt(index - 1)
    } else if (e.key === 'ArrowRight') {
      focusAt(index + 1)
    }
  }

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault()
    const pasted = e.clipboardData.getData('text').slice(0, length)
    const arr = current.split('')
    let cursor = 0
    for (const ch of pasted) {
      if (pattern.test(ch) && cursor < length) {
        arr[cursor] = ch
        cursor++
      }
    }
    update(arr.join(''))
    focusAt(Math.min(cursor, length - 1))
  }

  if (unstyled) {
    return (
      <div className={className} style={style} role="group" aria-label={ariaLabel}>
        {Array.from({ length }, (_, i) => (
          <input
            key={`${id}-${i}`}
            ref={(el) => {
              refs.current[i] = el
            }}
            type={mask ? 'password' : 'text'}
            inputMode={type === 'numeric' ? 'numeric' : 'text'}
            maxLength={1}
            value={current[i] === ' ' ? '' : current[i]}
            disabled={disabled || loading}
            autoFocus={autoFocus && i === 0}
            onChange={(e) => handleChange(i, e.target.value)}
            onKeyDown={(e) => handleKeyDown(i, e)}
            onPaste={handlePaste}
            onFocus={(e) => e.target.select()}
          />
        ))}
      </div>
    )
  }

  const wrapperClasses = [
    'sg-pin-input',
    `sg-pin-input-${size}`,
    disabled ? 'sg-pin-input-disabled' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={wrapperClasses} style={style} role="group" aria-label={ariaLabel}>
      {Array.from({ length }, (_, i) => {
        const filled = current[i] !== ' ' && current[i] !== undefined
        return (
          <input
            key={`${id}-${i}`}
            ref={(el) => {
              refs.current[i] = el
            }}
            className={[
              'sg-pin-input-cell',
              `sg-pin-input-cell-${size}`,
              filled ? 'sg-pin-input-cell-filled' : '',
            ]
              .filter(Boolean)
              .join(' ')}
            type={mask ? 'password' : 'text'}
            inputMode={type === 'numeric' ? 'numeric' : 'text'}
            maxLength={1}
            placeholder={placeholder}
            value={current[i] === ' ' ? '' : current[i]}
            disabled={disabled || loading}
            autoFocus={autoFocus && i === 0}
            onChange={(e) => handleChange(i, e.target.value)}
            onKeyDown={(e) => handleKeyDown(i, e)}
            onPaste={handlePaste}
            onFocus={(e) => e.target.select()}
          />
        )
      })}
    </div>
  )
}

// packages/vue/src/components/ui/PinInput.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import type { CSSProperties } from 'vue'
import type { SizeType } from '../../types'
import type { PinInputLocale } from '../../types'
import { useConfig, useConfigWithDefaults } from './ConfigProvider.vue'

export interface PinInputProps {
  length?: number
  modelValue?: string
  value?: string
  defaultValue?: string
  mask?: boolean
  type?: 'numeric' | 'alphanumeric'
  placeholder?: string
  autoFocus?: boolean
  size?: SizeType
  disabled?: boolean
  loading?: boolean
  unstyled?: boolean
  style?: CSSProperties
  'aria-label'?: string
}

const props = withDefaults(defineProps<PinInputProps>(), {
  length: 6,
  mask: false,
  type: 'numeric',
  placeholder: '○',
  autoFocus: false,
})

const emit = defineEmits<{
  (e: 'update:modelValue', v: string): void
  (e: 'change', v: string): void
  (e: 'complete', v: string): void
}>()

const { resolvedSize, resolvedDisabled } = useConfigWithDefaults(props, {})
const cfg = useConfig()

const lp = computed<PinInputLocale>(() => ({
  ariaLabel: 'PIN input',
  ...cfg.value.locale?.pinInput,
}))

const len = computed(() => props.length)

function padCompact(s: string): string {
  const compact = s.replace(/\s/g, '').slice(0, len.value)
  const chars = compact.split('')
  while (chars.length < len.value) chars.push(' ')
  return chars.join('')
}

function ensureCells(s: string): string[] {
  const a = s.split('')
  while (a.length < len.value) a.push(' ')
  return a.slice(0, len.value)
}

const isControlled = computed(() => props.modelValue !== undefined || props.value !== undefined)

const internal = ref(padCompact(props.defaultValue ?? ''))

const current = computed(() => {
  if (isControlled.value) {
    return padCompact(String(props.modelValue ?? props.value ?? ''))
  }
  return internal.value
})

const pattern = computed(() => (props.type === 'numeric' ? /^\d$/ : /^[a-zA-Z0-9]$/))

/**
 * Imperative-only DOM ref bag. Plain array (not `ref`) because the cells are
 * never read from a render or computed — they are only used to invoke
 * `.focus()`. Wrapping the bag in `ref` previously caused Vue to detect a
 * mutation during render (each `bindRef` set `cellRefs.value`) and threw the
 * "Maximum recursive updates exceeded" warning. See
 * `docs/_streams/decisions/T-Vue-Cleanup.md`.
 */
const cellRefs: (HTMLInputElement | null)[] = []

function bindRef(el: unknown, i: number) {
  cellRefs[i] = (el as HTMLInputElement) ?? null
}

function focusAt(i: number) {
  if (i >= 0 && i < len.value) cellRefs[i]?.focus()
}

function commit(joined: string) {
  const j = ensureCells(joined).join('')
  if (!isControlled.value) internal.value = j
  const trimmed = j.replace(/\s/g, '')
  emit('update:modelValue', trimmed)
  emit('change', trimmed)
  if (trimmed.length === len.value) emit('complete', trimmed)
}

function handleChange(index: number, char: string) {
  if (!pattern.value.test(char)) return
  const arr = ensureCells(current.value)
  arr[index] = char
  commit(arr.join(''))
  focusAt(index + 1)
}

function handleKeyDown(index: number, e: KeyboardEvent) {
  if (e.key === 'Backspace') {
    e.preventDefault()
    const arr = ensureCells(current.value)
    if (arr[index] !== ' ') {
      arr[index] = ' '
      commit(arr.join(''))
    } else {
      focusAt(index - 1)
    }
  } else if (e.key === 'ArrowLeft') {
    focusAt(index - 1)
  } else if (e.key === 'ArrowRight') {
    focusAt(index + 1)
  }
}

function handlePaste(e: ClipboardEvent) {
  e.preventDefault()
  const pasted = (e.clipboardData?.getData('text') ?? '').slice(0, len.value)
  const arr = ensureCells(current.value)
  let cursor = 0
  for (const ch of pasted) {
    if (pattern.value.test(ch) && cursor < len.value) {
      arr[cursor] = ch
      cursor++
    }
  }
  commit(arr.join(''))
  focusAt(Math.min(cursor, len.value - 1))
}

function cellDisplay(i: number): string {
  const c = current.value[i]
  return c === ' ' || c === undefined ? '' : c
}

const wrapperClasses = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-pin-input',
        `sg-pin-input-${resolvedSize.value}`,
        resolvedDisabled.value ? 'sg-pin-input-disabled' : '',
      ]
        .filter(Boolean)
        .join(' '),
)

const disabledEff = computed(() => resolvedDisabled.value || !!props.loading)

const ariaLabelEff = computed(() => props['aria-label'] ?? lp.value.ariaLabel!)

/** Template iterator: 0 .. length-1 */
const indices = computed(() => Array.from({ length: len.value }, (_, i) => i))
</script>

<template>
  <div
    :class="unstyled ? '' : wrapperClasses"
    :style="style"
    role="group"
    :aria-label="ariaLabelEff"
  >
    <template v-for="i in indices" :key="i">
      <input
        v-if="unstyled"
        :ref="(el) => bindRef(el, i)"
        :type="mask ? 'password' : 'text'"
        :inputmode="type === 'numeric' ? 'numeric' : 'text'"
        maxlength="1"
        :value="cellDisplay(i)"
        :disabled="disabledEff"
        :autofocus="autoFocus && i === 0"
        @input="handleChange(i, ($event.target as HTMLInputElement).value)"
        @keydown="handleKeyDown(i, $event)"
        @paste="handlePaste"
        @focus="($event.target as HTMLInputElement).select()"
      />
      <input
        v-else
        :ref="(el) => bindRef(el, i)"
        :class="
          [
            'sg-pin-input-cell',
            `sg-pin-input-cell-${resolvedSize}`,
            cellDisplay(i) ? 'sg-pin-input-cell-filled' : '',
          ]
            .filter(Boolean)
            .join(' ')
        "
        :type="mask ? 'password' : 'text'"
        :inputmode="type === 'numeric' ? 'numeric' : 'text'"
        maxlength="1"
        :placeholder="placeholder"
        :value="cellDisplay(i)"
        :disabled="disabledEff"
        :autofocus="autoFocus && i === 0"
        @input="handleChange(i, ($event.target as HTMLInputElement).value)"
        @keydown="handleKeyDown(i, $event)"
        @paste="handlePaste"
        @focus="($event.target as HTMLInputElement).select()"
      />
    </template>
  </div>
</template>
