// packages/react/src/components/ui/Radio.tsx
import React from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps } from '../../types'
import { Spin } from './Spin'

/** One selectable option in a radio group. */
export interface RadioOption {
  /** Visible label for the option. */
  label: string
  /** Value emitted when this option is selected. */
  value: string | number
  /** Disables this option regardless of group-level disabled state. */
  disabled?: boolean
}

/** Props for the RadioGroup component. */
export interface RadioGroupProps extends BaseComponentProps, InteractiveProps {
  /** Controlled selected value. */
  value?: string | number
  /** Uncontrolled initial selected value. */
  defaultValue?: string | number
  /** Options rendered as radio controls. */
  options: RadioOption[]
  /** Stacks options horizontally or vertically. @default 'horizontal' */
  direction?: 'horizontal' | 'vertical'
  /** Called when the selected value changes. */
  onChange?: (value: string | number) => void
}

/** Mutually exclusive radio options in a horizontal or vertical group. */
export function RadioGroup({
  value,
  defaultValue,
  options,
  direction = 'horizontal',
  disabled: disabledProp,
  loading,
  onChange,
  className,
  style,
  unstyled,
}: RadioGroupProps) {
  const config = useConfig()
  const disabled = disabledProp ?? config.disabled ?? false

  const [internalValue, setInternalValue] = React.useState(value ?? defaultValue)
  const currentValue = value ?? internalValue

  const groupClass = unstyled
    ? (className ?? '')
    : [
        'sg-radio-group',
        `sg-radio-group-${direction}`,
        loading ? 'sg-radio-group-loading' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')

  return (
    <div className={groupClass} role="radiogroup" style={style}>
      {options.map((opt) => (
        <label
          key={opt.value}
          className={
            unstyled
              ? ''
              : [
                  'sg-radio',
                  currentValue === opt.value ? 'sg-radio-checked' : '',
                  opt.disabled || disabled || loading ? 'sg-radio-disabled' : '',
                ]
                  .filter(Boolean)
                  .join(' ')
          }
        >
          <input
            type="radio"
            role="radio"
            aria-checked={currentValue === opt.value}
            className={unstyled ? '' : 'sg-radio-input'}
            checked={currentValue === opt.value}
            disabled={opt.disabled || disabled || loading}
            onChange={() => {
              setInternalValue(opt.value)
              onChange?.(opt.value)
            }}
          />
          {!unstyled && <span className="sg-radio-box" aria-hidden="true" />}
          <span className={unstyled ? '' : 'sg-radio-label'}>{opt.label}</span>
          {loading && currentValue === opt.value && <Spin size="small" unstyled={unstyled} />}
        </label>
      ))}
    </div>
  )
}

// packages/vue/src/components/ui/Radio.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useConfigWithDefaults } from './ConfigProvider.vue'

export interface RadioOption {
  label: string
  value: string | number
  disabled?: boolean
}

export interface RadioGroupProps {
  /** v-model binding (Vue idiom). */
  modelValue?: string | number
  /** Compat alias for `modelValue`. */
  value?: string | number
  /** Initial value when uncontrolled. */
  defaultValue?: string | number
  /** Options rendered as radio controls. */
  options: RadioOption[]
  /** Stack direction. */
  direction?: 'horizontal' | 'vertical'
  /** Disables all options. */
  disabled?: boolean
  /** Shows a loading spinner next to the selected option and disables interaction. */
  loading?: boolean
  /** Strips built-in styling. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<RadioGroupProps>(), {
  modelValue: undefined,
  value: undefined,
  defaultValue: undefined,
  direction: 'horizontal',
  disabled: undefined,
  loading: false,
  unstyled: false,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: string | number): void
  (e: 'change', value: string | number): void
}>()

const { resolvedDisabled } = useConfigWithDefaults({ disabled: props.disabled }, {})

const internal = ref<string | number | undefined>(
  props.modelValue ?? props.value ?? props.defaultValue,
)

watch(
  () => props.modelValue ?? props.value,
  (v) => {
    if (v !== undefined) internal.value = v
  },
)

const current = computed(() => props.modelValue ?? props.value ?? internal.value)

function select(opt: RadioOption) {
  if (opt.disabled || resolvedDisabled.value || props.loading) return
  internal.value = opt.value
  emit('update:modelValue', opt.value)
  emit('change', opt.value)
}

const groupClass = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-radio-group',
        `sg-radio-group-${props.direction}`,
        props.loading ? 'sg-radio-group-loading' : '',
      ]
        .filter(Boolean)
        .join(' '),
)

// Inputs are addressed via the wrapper to keep templates clean (one ref per
// option). Vue 3's `:checked` binding lands as a DOM attribute, not a property,
// which leaves the radio dot unpainted on the very first mount. Push the
// state through the property by hand after the patch settles.
const wrapperRef = ref<HTMLDivElement | null>(null)

function syncInputs() {
  const el = wrapperRef.value
  if (!el) return
  const inputs = el.querySelectorAll<HTMLInputElement>('input[type="radio"]')
  inputs.forEach((input, idx) => {
    const opt = props.options[idx]
    if (!opt) return
    const desired = current.value === opt.value
    if (input.checked !== desired) input.checked = desired
  })
}

watch([() => current.value, () => props.options], () => syncInputs(), { flush: 'post' })
onMounted(syncInputs)
</script>

<template>
  <div ref="wrapperRef" :class="groupClass" role="radiogroup">
    <label
      v-for="opt in options"
      :key="opt.value"
      :class="
        unstyled
          ? ''
          : [
              'sg-radio',
              current === opt.value ? 'sg-radio-checked' : '',
              opt.disabled || resolvedDisabled || loading ? 'sg-radio-disabled' : '',
            ]
              .filter(Boolean)
              .join(' ')
      "
    >
      <input
        type="radio"
        role="radio"
        :class="unstyled ? '' : 'sg-radio-input'"
        :aria-checked="current === opt.value"
        :checked="current === opt.value"
        :disabled="opt.disabled || resolvedDisabled || loading"
        @change="select(opt)"
      />
      <span v-if="!unstyled" class="sg-radio-box" aria-hidden="true" />
      <span :class="unstyled ? '' : 'sg-radio-label'">{{ opt.label }}</span>
      <span
        v-if="loading && current === opt.value && !unstyled"
        class="sg-spin sg-spin-small"
        aria-hidden="true"
      />
    </label>
  </div>
</template>
