// packages/react/src/components/ui/Rate.tsx
import React from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps } from '../../types'

/** Props for the Rate component. */
export interface RateProps extends BaseComponentProps, InteractiveProps {
  /** Controlled rating value. */
  value?: number
  /** Uncontrolled initial rating. @default 0 */
  defaultValue?: number
  /** Number of rating symbols. @default 5 */
  count?: number
  /** Allows selecting half steps between stars. */
  allowHalf?: boolean
  /** Custom node rendered for each rating symbol. @default '★' */
  character?: React.ReactNode
  /** Called when the rating value changes. */
  onChange?: (value: number) => void
}

/** Star-style rating with hover preview, half steps, and keyboard adjustment. */
export function Rate({
  value,
  defaultValue = 0,
  count = 5,
  disabled: disabledProp,
  allowHalf,
  character = '★',
  onChange,
  className,
  style,
  unstyled,
}: RateProps) {
  const config = useConfig()
  const disabled = disabledProp ?? config.disabled
  const rateLocale = config.locale?.rate
  const ariaLabel = rateLocale?.ariaLabel ?? 'Rating'
  const starLabel = rateLocale?.star ?? ((n: number) => `${n} star${n > 1 ? 's' : ''}`)

  const [internalValue, setInternalValue] = React.useState(value ?? defaultValue)
  const [hoverValue, setHoverValue] = React.useState<number | null>(null)
  const currentValue = value ?? internalValue
  const displayValue = hoverValue ?? currentValue

  const handleClick = (starValue: number) => {
    if (disabled) return
    const next = currentValue === starValue ? 0 : starValue
    setInternalValue(next)
    onChange?.(next)
  }

  const handleStarClick = (starIndex: number, clientX: number, rect: DOMRect) => {
    if (disabled) return
    if (!allowHalf) {
      handleClick(starIndex)
      return
    }
    const isLeftHalf = clientX - rect.left < rect.width / 2
    handleClick(isLeftHalf ? starIndex - 0.5 : starIndex)
  }

  const handleStarHover = (starIndex: number, clientX: number, rect: DOMRect) => {
    if (disabled) return
    if (!allowHalf) {
      setHoverValue(starIndex)
      return
    }
    const isLeftHalf = clientX - rect.left < rect.width / 2
    setHoverValue(isLeftHalf ? starIndex - 0.5 : starIndex)
  }

  const handleKeyDown = (e: React.KeyboardEvent, _starIndex: number) => {
    if (disabled) return
    if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
      e.preventDefault()
      const next = Math.min(count, allowHalf ? currentValue + 0.5 : currentValue + 1)
      handleClick(next)
    } else if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
      e.preventDefault()
      const next = Math.max(0, allowHalf ? currentValue - 0.5 : currentValue - 1)
      handleClick(next)
    }
  }

  const wrapperClass = unstyled
    ? (className ?? '')
    : ['sg-rate', disabled ? 'sg-rate-disabled' : '', className].filter(Boolean).join(' ')

  return (
    <div className={wrapperClass} style={style} role="radiogroup" aria-label={ariaLabel}>
      {Array.from({ length: count }, (_, i) => {
        const starIndex = i + 1
        const isFull = displayValue >= starIndex
        const isHalf = allowHalf && displayValue >= starIndex - 0.5 && displayValue < starIndex

        return (
          <span
            key={i}
            className={
              unstyled
                ? ''
                : [
                    'sg-rate-star',
                    isFull ? 'sg-rate-star-full' : '',
                    isHalf ? 'sg-rate-star-half' : '',
                  ]
                    .filter(Boolean)
                    .join(' ')
            }
            role="radio"
            aria-checked={isFull}
            aria-label={starLabel(starIndex)}
            tabIndex={disabled ? -1 : 0}
            onClick={(e) =>
              handleStarClick(starIndex, e.clientX, e.currentTarget.getBoundingClientRect())
            }
            onKeyDown={(e) => handleKeyDown(e, starIndex)}
            onMouseMove={(e) =>
              handleStarHover(starIndex, e.clientX, e.currentTarget.getBoundingClientRect())
            }
            onMouseLeave={() => !disabled && setHoverValue(null)}
          >
            {character}
          </span>
        )
      })}
    </div>
  )
}

// packages/vue/src/components/ui/Rate.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useConfig } from './ConfigProvider.vue'

export interface RateProps {
  /** v-model binding (Vue idiom). */
  modelValue?: number
  /** Compat alias for `modelValue`. */
  value?: number
  /** Initial value when uncontrolled. */
  defaultValue?: number
  /** Number of rating symbols. */
  count?: number
  /** Allows half steps. */
  allowHalf?: boolean
  /** Custom character (defaults to ★). Prefer the `character` slot for nodes. */
  character?: string
  /** Disables interaction. */
  disabled?: boolean
  /** Strips built-in styling. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<RateProps>(), {
  defaultValue: 0,
  count: 5,
  allowHalf: false,
  character: '★',
  disabled: false,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: number): void
  (e: 'change', value: number): void
}>()

const cfg = useConfig()
const rateLocale = computed(() => cfg.value.locale?.rate)
const ariaLabel = computed(() => rateLocale.value?.ariaLabel ?? 'Rating')
const starLabel = (n: number) => {
  const fn = rateLocale.value?.star
  if (typeof fn === 'function') return fn(n)
  return `${n} star${n > 1 ? 's' : ''}`
}

const internal = ref<number>(props.modelValue ?? props.value ?? props.defaultValue)
const hoverValue = ref<number | null>(null)

watch(
  () => props.modelValue ?? props.value,
  (v) => {
    if (v !== undefined) internal.value = v
  },
)

const current = computed(() => props.modelValue ?? props.value ?? internal.value)
const display = computed(() => hoverValue.value ?? current.value)

function emitValue(v: number) {
  internal.value = v
  emit('update:modelValue', v)
  emit('change', v)
}

function clickStar(starIndex: number, e: MouseEvent) {
  if (props.disabled) return
  if (!props.allowHalf) {
    emitValue(current.value === starIndex ? 0 : starIndex)
    return
  }
  const target = e.currentTarget as HTMLElement
  const rect = target.getBoundingClientRect()
  const isLeftHalf = e.clientX - rect.left < rect.width / 2
  const v = isLeftHalf ? starIndex - 0.5 : starIndex
  emitValue(current.value === v ? 0 : v)
}

function hoverStar(starIndex: number, e: MouseEvent) {
  if (props.disabled) return
  if (!props.allowHalf) {
    hoverValue.value = starIndex
    return
  }
  const target = e.currentTarget as HTMLElement
  const rect = target.getBoundingClientRect()
  const isLeftHalf = e.clientX - rect.left < rect.width / 2
  hoverValue.value = isLeftHalf ? starIndex - 0.5 : starIndex
}

function onKey(_starIndex: number, e: KeyboardEvent) {
  if (props.disabled) return
  if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
    e.preventDefault()
    emitValue(Math.min(props.count, props.allowHalf ? current.value + 0.5 : current.value + 1))
  } else if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
    e.preventDefault()
    emitValue(Math.max(0, props.allowHalf ? current.value - 0.5 : current.value - 1))
  }
}

const wrapperClass = computed(() =>
  props.unstyled
    ? ''
    : ['sg-rate', props.disabled ? 'sg-rate-disabled' : ''].filter(Boolean).join(' '),
)

function classFor(starIndex: number) {
  const isFull = display.value >= starIndex
  const isHalf = props.allowHalf && display.value >= starIndex - 0.5 && display.value < starIndex
  return ['sg-rate-star', isFull ? 'sg-rate-star-full' : '', isHalf ? 'sg-rate-star-half' : '']
    .filter(Boolean)
    .join(' ')
}
</script>

<template>
  <div :class="wrapperClass" role="radiogroup" :aria-label="ariaLabel">
    <span
      v-for="i in count"
      :key="i"
      :class="unstyled ? '' : classFor(i)"
      role="radio"
      :aria-checked="display >= i"
      :aria-label="starLabel(i)"
      :tabindex="disabled ? -1 : 0"
      @click="(e) => clickStar(i, e)"
      @mousemove="(e) => hoverStar(i, e)"
      @mouseleave="!disabled && (hoverValue = null)"
      @keydown="(e) => onKey(i, e)"
    >
      <slot name="character" :index="i" :value="display"
        ><slot>{{ character }}</slot></slot
      >
    </span>
  </div>
</template>
