// packages/react/src/components/ui/Spin.tsx
import React from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, SizableProps } from '../../types'

/** Props for loading spinner, overlay, and optional content blur. */
export interface SpinProps extends BaseComponentProps, SizableProps {
  /** When `true`, shows the loading state (subject to `delay`). @default true */
  spinning?: boolean
  /** Milliseconds to wait before showing the spinner after `spinning` becomes true. */
  delay?: number
  /** Optional text below the indicator. */
  tip?: string
  /** When `true`, covers the viewport instead of inline or wrapping children. */
  fullscreen?: boolean
  /** Custom spinner node; defaults to a styled status element. */
  indicator?: React.ReactNode
  /** When set, shows an overlay with blur on this content while loading. */
  children?: React.ReactNode
}

/**
 * Loading indicator with optional delay, tip, fullscreen mode, and child overlay.
 */
export function Spin({
  spinning = true,
  size: sizeProp,
  delay,
  tip,
  fullscreen,
  indicator,
  children,
  className,
  style,
  unstyled,
}: SpinProps) {
  const config = useConfig()
  const resolvedSize = sizeProp ?? config.size ?? 'middle'

  const [visible, setVisible] = React.useState(delay ? false : spinning)

  React.useEffect(() => {
    if (!delay) {
      setVisible(spinning)
      return
    }

    if (spinning) {
      const timer = setTimeout(() => setVisible(true), delay)
      return () => clearTimeout(timer)
    }

    setVisible(false)
  }, [spinning, delay])

  if (!visible && !children) return null
  if (!visible && children) return <>{children}</>

  const spinSizeClass = resolvedSize === 'middle' ? 'default' : resolvedSize
  const spinClasses = unstyled
    ? (className ?? '')
    : ['sg-spin', `sg-spin-${spinSizeClass}`, className].filter(Boolean).join(' ')

  const spinElement = indicator ?? (
    <span
      className={spinClasses}
      style={style}
      role="status"
      aria-live="polite"
      aria-label={config.locale?.spin?.loading ?? 'Loading'}
    />
  )

  if (fullscreen) {
    return (
      <div className={unstyled ? '' : 'sg-spin-fullscreen'}>
        <div className={unstyled ? '' : 'sg-spin-fullscreen-inner'}>
          {spinElement}
          {tip && <div className={unstyled ? '' : 'sg-spin-tip'}>{tip}</div>}
        </div>
      </div>
    )
  }

  if (!children) {
    return (
      <span className={unstyled ? '' : 'sg-spin-standalone'} style={style}>
        {spinElement}
        {tip && <div className={unstyled ? '' : 'sg-spin-tip'}>{tip}</div>}
      </span>
    )
  }

  return (
    <div className={unstyled ? '' : 'sg-spin-container'} style={style}>
      <div className={unstyled ? '' : 'sg-spin-overlay'}>
        {spinElement}
        {tip && <div className={unstyled ? '' : 'sg-spin-tip'}>{tip}</div>}
      </div>
      <div className={visible ? (unstyled ? '' : 'sg-spin-blur') : ''}>{children}</div>
    </div>
  )
}

// packages/vue/src/components/ui/Spin.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, useSlots, watch } from 'vue'
import { useConfig, useConfigWithDefaults } from './ConfigProvider.vue'
import type { SizeType } from '../../types'

export interface SpinProps {
  /** When `true`, shows the loading state (subject to `delay`). @default true */
  spinning?: boolean
  /** Component size variant. */
  size?: SizeType
  /** Milliseconds to wait before showing the spinner after `spinning` becomes true. */
  delay?: number
  /** Optional text below the indicator. */
  tip?: string
  /** When `true`, covers the viewport instead of inline or wrapping children. */
  fullscreen?: boolean
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<SpinProps>(), {
  spinning: true,
  fullscreen: false,
})

defineSlots<{
  default(props: Record<string, never>): unknown
  indicator(props: Record<string, never>): unknown
}>()

const { resolvedSize } = useConfigWithDefaults({ size: undefined }, {})
const realSize = computed<SizeType>(() => props.size ?? resolvedSize.value)

const cfg = useConfig()
const loadingLabel = computed(() => cfg.value.locale?.spin?.loading ?? 'Loading')

const visible = ref(props.delay ? false : props.spinning)
let timer: ReturnType<typeof setTimeout> | undefined

watch(
  () => [props.spinning, props.delay] as const,
  ([s, d]) => {
    if (timer) clearTimeout(timer)
    if (!d) {
      visible.value = !!s
      return
    }
    if (s) {
      timer = setTimeout(() => {
        visible.value = true
      }, d)
    } else {
      visible.value = false
    }
  },
  { immediate: true },
)

onBeforeUnmount(() => {
  if (timer) clearTimeout(timer)
})

const spinSizeClass = computed(() => (realSize.value === 'middle' ? 'default' : realSize.value))
const spinClasses = computed(() => (props.unstyled ? '' : `sg-spin sg-spin-${spinSizeClass.value}`))

const slots = useSlots()
const hasChildren = computed(() => Boolean(slots.default))
const hasIndicator = computed(() => Boolean(slots.indicator))
</script>

<template>
  <template v-if="!visible && !hasChildren" />
  <template v-else-if="!visible && hasChildren">
    <slot />
  </template>
  <div v-else-if="fullscreen" :class="unstyled ? '' : 'sg-spin-fullscreen'">
    <div :class="unstyled ? '' : 'sg-spin-fullscreen-inner'">
      <slot v-if="hasIndicator" name="indicator" />
      <span
        v-else
        :class="spinClasses"
        role="status"
        aria-live="polite"
        :aria-label="loadingLabel"
      />
      <div v-if="tip" :class="unstyled ? '' : 'sg-spin-tip'">{{ tip }}</div>
    </div>
  </div>
  <span v-else-if="!hasChildren" :class="unstyled ? '' : 'sg-spin-standalone'">
    <slot v-if="hasIndicator" name="indicator" />
    <span v-else :class="spinClasses" role="status" aria-live="polite" :aria-label="loadingLabel" />
    <div v-if="tip" :class="unstyled ? '' : 'sg-spin-tip'">{{ tip }}</div>
  </span>
  <div v-else :class="unstyled ? '' : 'sg-spin-container'">
    <div :class="unstyled ? '' : 'sg-spin-overlay'">
      <slot v-if="hasIndicator" name="indicator" />
      <span
        v-else
        :class="spinClasses"
        role="status"
        aria-live="polite"
        :aria-label="loadingLabel"
      />
      <div v-if="tip" :class="unstyled ? '' : 'sg-spin-tip'">{{ tip }}</div>
    </div>
    <div :class="visible && !unstyled ? 'sg-spin-blur' : ''">
      <slot />
    </div>
  </div>
</template>
