// packages/react/src/components/ui/Tabs.tsx
import React, { useState } from 'react'
import { Spin } from './Spin'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, SizableProps } from '../../types'

/** Configuration for one tab: label, panel content, and optional states. */
export interface TabItem {
  /** Unique key used for selection and ARIA. */
  key: string
  /** Tab label in the tab list. */
  label: React.ReactNode
  /** Panel body shown when this tab is active. */
  children: React.ReactNode
  /** When true, the tab cannot be activated. */
  disabled?: boolean
  /** When true, shows a spinner and blocks activation until cleared. */
  loading?: boolean
}

/** Props for the tab list and associated single visible panel. */
export interface TabsProps extends BaseComponentProps, SizableProps {
  /**
   * Visual chrome: `card` — bordered strip with the active tab attached to the
   * panel (classic desktop tabs). `line` — minimal underline indicator only.
   * @default 'card'
   */
  type?: 'line' | 'card'
  /** Tab definitions including labels and panel content. */
  items: TabItem[]
  /** Controlled active tab key. */
  activeKey?: string
  /** Initial active tab when `activeKey` is not controlled. */
  defaultActiveKey?: string
  /** Called when the active tab changes after user interaction. */
  onChange?: (key: string) => void
}

/**
 * Tabbed interface with keyboard navigation between tabs and one visible panel.
 * Resolves initial active key from props, then first item, when uncontrolled.
 */
export function Tabs({
  type: typeProp,
  items,
  activeKey,
  defaultActiveKey,
  onChange,
  size: sizeProp,
  className,
  style,
  unstyled,
}: TabsProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const type = typeProp ?? 'card'
  const [internalKey, setInternalKey] = useState(
    activeKey ?? defaultActiveKey ?? items[0]?.key ?? ''
  )
  const currentKey = activeKey ?? internalKey
  const activeItem = items.find((i) => i.key === currentKey)

  const handleClick = (key: string, disabled?: boolean, loading?: boolean) => {
    if (disabled || loading) return
    setInternalKey(key)
    onChange?.(key)
  }

  if (unstyled) {
    return (
      <div className={className} style={style}>
        <div role="tablist">
          {items.map((item) => (
            <button
              key={item.key}
              role="tab"
              aria-selected={item.key === currentKey}
              disabled={item.disabled || item.loading}
              onClick={() => handleClick(item.key, item.disabled, item.loading)}
            >
              {item.label}
              {item.loading && <Spin size="small" unstyled />}
            </button>
          ))}
        </div>
        <div role="tabpanel">{activeItem?.children}</div>
      </div>
    )
  }

  return (
    <div
      className={[
        'sg-tabs',
        `sg-tabs-${size}`,
        type === 'line' ? 'sg-tabs-line' : 'sg-tabs-card',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      style={style}
    >
      <div className="sg-tabs-nav" role="tablist">
        {items.map((item) => (
          <div
            key={item.key}
            role="tab"
            aria-selected={item.key === currentKey}
            className={[
              'sg-tabs-tab',
              item.key === currentKey ? 'sg-tabs-tab-active' : '',
              item.disabled ? 'sg-tabs-tab-disabled' : '',
              item.loading ? 'sg-tabs-tab-loading' : '',
            ]
              .filter(Boolean)
              .join(' ')}
            tabIndex={item.key === currentKey ? 0 : -1}
            onClick={() => handleClick(item.key, item.disabled, item.loading)}
            onKeyDown={(e) => {
              const enabledItems = items.filter((i) => !i.disabled && !i.loading)
              if (enabledItems.length === 0) return
              const curIdx = enabledItems.findIndex((i) => i.key === item.key)
              if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
                e.preventDefault()
                const next = enabledItems[(curIdx + 1) % enabledItems.length]
                if (next) handleClick(next.key)
              } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
                e.preventDefault()
                const prev = enabledItems[(curIdx - 1 + enabledItems.length) % enabledItems.length]
                if (prev) handleClick(prev.key)
              } else if (e.key === 'Home') {
                e.preventDefault()
                handleClick(enabledItems[0].key)
              } else if (e.key === 'End') {
                e.preventDefault()
                handleClick(enabledItems[enabledItems.length - 1].key)
              }
            }}
          >
            {item.label}
            {item.loading && <Spin size="small" unstyled={unstyled} />}
          </div>
        ))}
      </div>
      <div className="sg-tabs-content" role="tabpanel">
        {activeItem?.children}
      </div>
    </div>
  )
}

// packages/vue/src/components/ui/Tabs.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useConfigWithDefaults } from './ConfigProvider.vue'
import type { SizeType } from '../../types'

export interface TabItem {
  /** Unique key used for selection and ARIA. */
  key: string
  /** Tab label in the tab list. */
  label: string
  /** Panel body shown when this tab is active. */
  content?: string
  /** When true, the tab cannot be activated. */
  disabled?: boolean
  /** When true, shows a spinner and blocks activation until cleared. */
  loading?: boolean
}

export interface TabsProps {
  /** Visual chrome. @default 'card' */
  type?: 'line' | 'card'
  /** Tab definitions. */
  items: TabItem[]
  /** Controlled active tab key. */
  activeKey?: string
  /** Initial active tab when uncontrolled. */
  defaultActiveKey?: string
  /** Component size variant. */
  size?: SizeType
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<TabsProps>(), {
  type: 'card',
})

const emit = defineEmits<{
  (e: 'change', key: string): void
}>()

defineSlots<{
  default(props: { activeKey: string }): unknown
  tab(props: { item: TabItem }): unknown
  panel(props: { item: TabItem }): unknown
}>()

const { resolvedSize } = useConfigWithDefaults({ size: undefined }, {})
const realSize = computed<SizeType>(() => props.size ?? resolvedSize.value)

const internal = ref(props.activeKey ?? props.defaultActiveKey ?? props.items[0]?.key ?? '')
const currentKey = computed(() => props.activeKey ?? internal.value)
const activeItem = computed(() => props.items.find((i) => i.key === currentKey.value))

function setKey(key: string, disabled?: boolean, loading?: boolean) {
  if (disabled || loading) return
  internal.value = key
  emit('change', key)
}

function onKeyDown(e: KeyboardEvent, item: TabItem) {
  const enabled = props.items.filter((i) => !i.disabled && !i.loading)
  if (enabled.length === 0) return
  const cur = enabled.findIndex((i) => i.key === item.key)
  if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
    e.preventDefault()
    const next = enabled[(cur + 1) % enabled.length]
    if (next) setKey(next.key)
  } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
    e.preventDefault()
    const prev = enabled[(cur - 1 + enabled.length) % enabled.length]
    if (prev) setKey(prev.key)
  } else if (e.key === 'Home') {
    e.preventDefault()
    setKey(enabled[0].key)
  } else if (e.key === 'End') {
    e.preventDefault()
    setKey(enabled[enabled.length - 1].key)
  }
}

const rootClasses = computed(() =>
  [
    'sg-tabs',
    `sg-tabs-${realSize.value}`,
    props.type === 'line' ? 'sg-tabs-line' : 'sg-tabs-card',
  ].join(' '),
)
</script>

<template>
  <div v-if="unstyled">
    <div role="tablist">
      <button
        v-for="item in items"
        :key="item.key"
        type="button"
        role="tab"
        :aria-selected="item.key === currentKey"
        :disabled="item.disabled || item.loading"
        @click="setKey(item.key, item.disabled, item.loading)"
      >
        <slot name="tab" :item="item">{{ item.label }}</slot>
        <span v-if="item.loading" class="sg-spin sg-spin-small" aria-hidden="true" />
      </button>
    </div>
    <div role="tabpanel">
      <slot v-if="activeItem" name="panel" :item="activeItem">
        {{ activeItem.content }}
      </slot>
      <slot :activeKey="currentKey" />
    </div>
  </div>
  <div v-else :class="rootClasses">
    <div class="sg-tabs-nav" role="tablist">
      <div
        v-for="item in items"
        :key="item.key"
        role="tab"
        :aria-selected="item.key === currentKey"
        :class="[
          'sg-tabs-tab',
          item.key === currentKey ? 'sg-tabs-tab-active' : '',
          item.disabled ? 'sg-tabs-tab-disabled' : '',
          item.loading ? 'sg-tabs-tab-loading' : '',
        ]"
        :tabindex="item.key === currentKey ? 0 : -1"
        @click="setKey(item.key, item.disabled, item.loading)"
        @keydown="onKeyDown($event, item)"
      >
        <slot name="tab" :item="item">{{ item.label }}</slot>
        <span v-if="item.loading && !unstyled" class="sg-spin sg-spin-small" aria-hidden="true" />
      </div>
    </div>
    <div class="sg-tabs-content" role="tabpanel">
      <slot v-if="activeItem" name="panel" :item="activeItem">
        {{ activeItem.content }}
      </slot>
      <slot :activeKey="currentKey" />
    </div>
  </div>
</template>
