// packages/react/src/components/ui/Textarea.tsx
import React from 'react'
import { Spin } from './Spin'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps, SizableProps } from '../../types'

/** Props for the multiline text field with optional character count and loading overlay. */
export interface TextareaProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Controlled value; when omitted, uses internal state seeded by `defaultValue`. */
  value?: string
  /** Initial value when uncontrolled. */
  defaultValue?: string
  /** Placeholder shown when empty. */
  placeholder?: string
  /** Visible row count on the native textarea. @default 4 */
  rows?: number
  /** Hard cap on input length enforced in the change handler. */
  maxLength?: number
  /** Shows current length (and `maxLength` when set) beside the field in styled mode. */
  showCount?: boolean
  /** DOM id forwarded to the underlying `<textarea>`. */
  id?: string
  /** Exposes invalid state to assistive technologies. */
  'aria-invalid'?: boolean | 'false' | 'true' | 'grammar' | 'spelling'
  /** Connects the textarea to description / error nodes for assistive technologies. */
  'aria-describedby'?: string
  /** Marks the field as required for assistive technologies. */
  'aria-required'?: boolean | 'false' | 'true'
  /** Emits the full string on each change. */
  onChange?: (value: string) => void
  /** Passed through to the textarea blur event. */
  onBlur?: () => void
  /** Passed through to the textarea focus event. */
  onFocus?: () => void
}

/**
 * Styled textarea with configurable rows, optional character count, and loading state from shared interactive props.
 */
export function Textarea({
  value,
  defaultValue,
  placeholder,
  rows = 4,
  maxLength,
  showCount,
  disabled: disabledProp,
  loading,
  size: sizeProp,
  onChange,
  onBlur,
  onFocus,
  id,
  'aria-invalid': ariaInvalid,
  'aria-describedby': ariaDescribedBy,
  'aria-required': ariaRequired,
  className,
  style,
  unstyled,
}: TextareaProps) {
  const config = useConfig()
  const disabled = disabledProp ?? config.disabled
  const size = sizeProp ?? config.size ?? 'middle'

  const [internalValue, setInternalValue] = React.useState(value ?? defaultValue ?? '')
  const currentValue = value ?? internalValue

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const v = e.target.value
    if (maxLength && v.length > maxLength) return
    setInternalValue(v)
    onChange?.(v)
  }

  const wrapperClass = unstyled
    ? className ?? ''
    : ['sg-textarea-wrapper', `sg-textarea-${size}`, loading ? 'sg-textarea-wrapper-loading' : '', className]
        .filter(Boolean)
        .join(' ')

  return (
    <div className={wrapperClass} style={style}>
      <textarea
        id={id}
        className={unstyled ? '' : 'sg-input sg-textarea'}
        value={currentValue}
        placeholder={placeholder}
        rows={rows}
        disabled={disabled || loading}
        aria-disabled={disabled || loading}
        aria-invalid={ariaInvalid}
        aria-describedby={ariaDescribedBy}
        aria-required={ariaRequired}
        onChange={handleChange}
        onBlur={onBlur}
        onFocus={onFocus}
      />
      {loading && <Spin size="small" unstyled={unstyled} />}
      {showCount && !unstyled && (
        <span className="sg-textarea-count">
          {currentValue.length}{maxLength ? ` / ${maxLength}` : ''}
        </span>
      )}
    </div>
  )
}

// packages/vue/src/components/ui/Textarea.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useConfigWithDefaults } from './ConfigProvider.vue'

export interface TextareaProps {
  /** v-model binding (Vue idiom). */
  modelValue?: string
  /** Compat alias for `modelValue`. */
  value?: string
  /** Initial value when uncontrolled. */
  defaultValue?: string
  /** Placeholder shown when empty. */
  placeholder?: string
  /** Visible row count. */
  rows?: number
  /** Hard cap on input length. */
  maxLength?: number
  /** Shows current length below the field. */
  showCount?: boolean
  /** DOM id. */
  id?: string
  /** Disables editing. */
  disabled?: boolean
  /** Shows a loading spinner. */
  loading?: boolean
  /** Size token. */
  size?: 'small' | 'middle' | 'large'
  /** Strips built-in styling. */
  unstyled?: boolean
  /** Exposes invalid state to assistive technologies. */
  ariaInvalid?: boolean | 'false' | 'true' | 'grammar' | 'spelling'
  /** Connects the textarea to description / error nodes for assistive technologies. */
  ariaDescribedby?: string
  /** Marks the field as required for assistive technologies. */
  ariaRequired?: boolean | 'false' | 'true'
}

const props = withDefaults(defineProps<TextareaProps>(), {
  rows: 4,
  size: 'middle',
  disabled: undefined,
  loading: false,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'change', value: string): void
  (e: 'blur'): void
  (e: 'focus'): void
}>()

const { resolvedDisabled } = useConfigWithDefaults({ disabled: props.disabled }, {})

const internalValue = ref(props.modelValue ?? props.value ?? props.defaultValue ?? '')

watch(
  () => props.modelValue ?? props.value,
  (v) => {
    if (v !== undefined) internalValue.value = v
  },
)

const currentValue = computed(() => props.modelValue ?? props.value ?? internalValue.value)

const wrapperClass = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-textarea-wrapper',
        `sg-textarea-${props.size}`,
        props.loading ? 'sg-textarea-wrapper-loading' : '',
      ]
        .filter(Boolean)
        .join(' '),
)

function onInput(e: Event) {
  const target = e.target as HTMLTextAreaElement
  let v = target.value
  if (props.maxLength && v.length > props.maxLength) {
    v = v.slice(0, props.maxLength)
  }
  internalValue.value = v
  emit('update:modelValue', v)
  emit('change', v)
}
</script>

<template>
  <div :class="wrapperClass">
    <textarea
      :id="id"
      :class="unstyled ? '' : 'sg-input sg-textarea'"
      :value="currentValue"
      :placeholder="placeholder"
      :rows="rows"
      :disabled="resolvedDisabled || loading"
      :aria-disabled="resolvedDisabled || loading"
      :aria-invalid="ariaInvalid"
      :aria-describedby="ariaDescribedby"
      :aria-required="ariaRequired"
      @input="onInput"
      @blur="emit('blur')"
      @focus="emit('focus')"
    />
    <span v-if="loading && !unstyled" class="sg-spin sg-spin-small" aria-hidden="true" />
    <span v-if="showCount && !unstyled" class="sg-textarea-count">
      {{ currentValue.length }}{{ maxLength ? ` / ${maxLength}` : '' }}
    </span>
  </div>
</template>
