// packages/react/src/components/ui/Button.tsx
import React from 'react'
import { Spin } from './Spin'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps, SizableProps } from '../../types'

/** Props for the Button component. */
export interface ButtonProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Visual style variant. @default 'default' */
  type?: 'default' | 'primary' | 'dashed' | 'text' | 'link'
  /** Native HTML button type attribute. @default 'button' */
  htmlType?: 'button' | 'submit' | 'reset'
  /**
   * Visually flags a destructive action. Combines with `type` (e.g. a
   * `danger` `primary` button is solid red, a `danger` `text` is red text).
   * Adds the `sg-button-danger` modifier class.
   * @default false
   */
  danger?: boolean
  /** Stretches the button to fill its parent container. @default false */
  block?: boolean
  /** Click event handler. */
  onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void
  /** Button content. */
  children?: React.ReactNode
}

/** General-purpose button with multiple visual variants, sizes, and loading state. */
export function Button({
  type = 'default',
  size: sizeProp,
  disabled: disabledProp,
  loading,
  htmlType = 'button',
  danger = false,
  block = false,
  onClick,
  children,
  className,
  style,
  unstyled,
}: ButtonProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const disabled = disabledProp ?? config.disabled ?? false

  const classes = unstyled
    ? className ?? ''
    : [
        'sg-button',
        `sg-button-${type}`,
        `sg-button-${size}`,
        danger ? 'sg-button-danger' : '',
        block ? 'sg-button-block' : '',
        loading ? 'sg-button-loading' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')

  return (
    <button
      type={htmlType}
      className={classes}
      style={style}
      disabled={disabled || loading}
      aria-disabled={disabled || loading}
      aria-busy={loading}
      onClick={onClick}
    >
      {loading && <Spin size="small" unstyled={unstyled} />}
      {children}
    </button>
  )
}

// packages/vue/src/components/Button/Button.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface ButtonProps {
  /** Visual style variant. */
  type?: 'default' | 'primary' | 'dashed' | 'text' | 'link'
  /** Size token. */
  size?: 'small' | 'middle' | 'large'
  /** Native HTML button type attribute. */
  htmlType?: 'button' | 'submit' | 'reset'
  /** Visually flags a destructive action. */
  danger?: boolean
  /** Stretches the button to fill its parent container. */
  block?: boolean
  /** Disables the button. */
  disabled?: boolean
  /** Shows a loading spinner and disables interaction. */
  loading?: boolean
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<ButtonProps>(), {
  type: 'default',
  size: 'middle',
  htmlType: 'button',
  danger: false,
  block: false,
  disabled: false,
  loading: false,
  unstyled: false,
})

const emit = defineEmits<{
  (e: 'click', evt: MouseEvent): void
}>()

defineSlots<{
  default(props: Record<string, never>): unknown
  icon(props: Record<string, never>): unknown
}>()

const classes = computed(() => {
  if (props.unstyled) return ''
  return [
    'sg-button',
    `sg-button-${props.type}`,
    `sg-button-${props.size}`,
    props.danger ? 'sg-button-danger' : '',
    props.block ? 'sg-button-block' : '',
    props.loading ? 'sg-button-loading' : '',
  ]
    .filter(Boolean)
    .join(' ')
})

const isDisabled = computed(() => props.disabled || props.loading)

function handleClick(evt: MouseEvent) {
  if (isDisabled.value) {
    evt.preventDefault()
    evt.stopPropagation()
    return
  }
  emit('click', evt)
}
</script>

<template>
  <button
    :type="htmlType"
    :class="classes"
    :disabled="isDisabled"
    :aria-disabled="isDisabled"
    :aria-busy="loading || undefined"
    @click="handleClick"
  >
    <span v-if="loading && !unstyled" class="sg-spin sg-spin-small" aria-hidden="true" />
    <slot name="icon" />
    <slot />
  </button>
</template>
