// packages/react/src/components/complex/Field.tsx
import React, { useEffect, useId, useRef } from 'react'
import { useFormContext } from './FormContext'
import { useField } from '../../hooks/useField'
import { Input } from '../ui/Input'
import { Textarea } from '../ui/Textarea'
import { Tooltip } from '../ui/Tooltip'
import { Spin } from '../ui/Spin'
import { useConfig } from '../ConfigProvider'
import type { UseFieldReturn } from '../../hooks/useField'
import type { Rule } from '@skygraph/core'
import type { BaseComponentProps } from '../../types'

/** Props for a single named field with validation, layout, and optional custom control. */
export interface FieldProps extends BaseComponentProps {
  /** Registered path in the form store. */
  name: string
  /** Visible label text; layout comes from {@link FormContext}. */
  label?: string
  /** When `true`, prepends a required rule in addition to `rules`. */
  required?: boolean
  /** Validation rules for this field.
   * @default []
   */
  rules?: Rule[]
  /** Rules that produce warnings without failing validation. */
  warningRules?: Rule[]
  /** Re-validates this field when any listed field changes. */
  dependencies?: string[]
  /** When `true`, the field renders nothing (values can remain registered). */
  hidden?: boolean
  /** Disables the control; falls back to form context `disabled`. */
  disabled?: boolean
  /** Placeholder for the built-in `Input` / `Textarea`. */
  placeholder?: string
  /** Built-in control type when `children` is not provided.
   * @default 'text'
   */
  type?: 'text' | 'email' | 'password' | 'number' | 'textarea'
  /** Helper text shown below the control when there are no errors/warnings. */
  help?: React.ReactNode
  /** Supplementary content below the control area. */
  extra?: React.ReactNode
  /** Tooltip title wrapping the label text. */
  tooltip?: string
  /** Custom control, render prop, or omit for default input/textarea. */
  children?: React.ReactNode | ((field: UseFieldReturn) => React.ReactNode)
  // New props
  /** Renders only the control (validation wiring) without layout chrome. */
  noStyle?: boolean
  /** Maps raw change values before committing to the store. */
  normalize?: (value: unknown, prevValue: unknown) => unknown
  /** Custom extractor for control events (reserved for controlled wrappers). */
  getValueFromEvent?: (...args: unknown[]) => unknown
  /** Prop name on the child that holds the value (for custom controls). */
  valuePropName?: string
  /** Stops after the first failing rule when validating. */
  validateFirst?: boolean
  /** Manual validation status badge; overrides engine-derived status when set. */
  validateStatus?: 'success' | 'warning' | 'error' | 'validating'
  /** Shows feedback icons when the field has been touched. */
  hasFeedback?: boolean
  /** Keeps value on unregister; overrides form-level `preserve` when set. */
  preserve?: boolean
  /** Overrides form `labelCol` for this field in horizontal layout. */
  labelCol?: {
    /** Column span (out of 24). */
    span?: number
    /** Column offset (out of 24). */
    offset?: number
  }
  /** Overrides form `wrapperCol` for this field in horizontal layout. */
  wrapperCol?: {
    /** Column span (out of 24). */
    span?: number
    /** Column offset (out of 24). */
    offset?: number
  }
  /** Template variables merged into validation messages for this field. */
  messageVariables?: Record<string, string>
}

function FeedbackIcon({
  status,
  icons,
}: {
  status: 'success' | 'warning' | 'error' | 'validating' | undefined
  icons?: {
    success?: React.ReactNode
    warning?: React.ReactNode
    error?: React.ReactNode
    validating?: React.ReactNode
  }
}) {
  if (!status) return null

  const defaults: Record<string, React.ReactNode> = {
    validating: <Spin size="small" />,
    error: <span className="sg-field-feedback-icon sg-field-feedback-error">✕</span>,
    warning: <span className="sg-field-feedback-icon sg-field-feedback-warning">!</span>,
    success: <span className="sg-field-feedback-icon sg-field-feedback-success">✓</span>,
  }

  return <span className="sg-field-feedback">{icons?.[status] ?? defaults[status]}</span>
}

/**
 * Registers `name` with the form engine, renders label/help/errors, and either
 * a built-in input or custom `children` / render-prop control.
 */
export function Field({
  name,
  label,
  required,
  rules = [],
  warningRules,
  dependencies,
  hidden,
  disabled: fieldDisabled,
  unstyled,
  placeholder,
  type = 'text',
  help,
  extra,
  tooltip,
  children,
  noStyle,
  normalize,
  getValueFromEvent: _getValueFromEvent,
  validateFirst,
  validateStatus: manualStatus,
  hasFeedback,
  preserve,
  labelCol: fieldLabelCol,
  wrapperCol: fieldWrapperCol,
  messageVariables: _messageVariables,
}: FieldProps) {
  const ctx = useFormContext()
  const { core, form } = ctx
  const disabled = fieldDisabled ?? ctx.disabled
  const formLocale = useConfig().locale?.form
  const requiredMarker = formLocale?.required ?? '*'
  const optionalMarker = formLocale?.optional ?? '(optional)'
  const autoId = useId()
  const fieldId = `sg-field-${autoId.replace(/:/g, '')}-${name.replace(/\./g, '-')}`
  const helpId = `${fieldId}-help`
  const field = useField(core, form, name)
  const prevValueRef = useRef<unknown>(field.value)

  useEffect(() => {
    const allRules: Rule[] = [...rules]
    if (required) {
      allRules.unshift({ required: true })
    }
    form.register(name, {
      rules: allRules,
      warningRules,
      dependencies,
      validateFirst,
      label,
      preserve: preserve ?? ctx.preserve,
    })
    return () => form.unregister(name)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [name, form, required])

  if (hidden) return null

  const wrappedOnChange = normalize
    ? (v: unknown) => {
        const normalized = normalize(v, prevValueRef.current)
        prevValueRef.current = normalized
        field.onChange(normalized)
      }
    : field.onChange

  const effectiveStatus = manualStatus ?? field.status
  const hasErrors = field.errors.length > 0
  const hasWarnings = field.warnings.length > 0

  // Layout
  const layout = ctx.layout ?? 'vertical'
  const lCol = fieldLabelCol ?? ctx.labelCol
  const wCol = fieldWrapperCol ?? ctx.wrapperCol
  const labelAlign = ctx.labelAlign ?? 'right'

  const labelNode = label ? (
    <label
      htmlFor={fieldId}
      className="sg-field-label"
      style={
        layout === 'horizontal' && lCol?.offset
          ? { marginLeft: `${(lCol.offset / 24) * 100}%` }
          : undefined
      }
    >
      {tooltip ? (
        <Tooltip title={tooltip}>
          <span>{label}</span>
        </Tooltip>
      ) : (
        label
      )}
      {(required || ctx.requiredMark === true) && (
        <span className="sg-field-required">{requiredMarker}</span>
      )}
      {ctx.requiredMark === 'optional' && !required && (
        <span className="sg-field-optional">{optionalMarker}</span>
      )}
      {ctx.colon && ':'}
    </label>
  ) : null

  const errorNodes = hasErrors ? (
    <div id={helpId} className="sg-field-error" role="alert">
      {field.errors.map((e, i) => (
        <div key={i}>{e}</div>
      ))}
    </div>
  ) : null

  const warningNodes =
    hasWarnings && !hasErrors ? (
      <div id={helpId} className="sg-field-warning">
        {field.warnings.map((w, i) => (
          <div key={i}>{w}</div>
        ))}
      </div>
    ) : null

  const helpNode =
    errorNodes ??
    warningNodes ??
    (help ? (
      <div id={helpId} className="sg-field-help">
        {help}
      </div>
    ) : null)
  const describedBy = helpNode ? helpId : undefined

  const extraNode = extra ? <div className="sg-field-extra">{extra}</div> : null

  const feedbackIcon =
    hasFeedback && field.touched ? (
      <FeedbackIcon status={effectiveStatus} icons={ctx.feedbackIcons} />
    ) : null

  // Render children
  const renderControl = () => {
    if (typeof children === 'function') {
      return (
        <>
          {children({ ...field, onChange: wrappedOnChange })}
          {feedbackIcon}
        </>
      )
    }

    if (children) {
      return (
        <>
          {children}
          {feedbackIcon}
        </>
      )
    }

    const inputElement =
      type === 'textarea' ? (
        <Textarea
          id={fieldId}
          value={(field.value as string) ?? ''}
          onChange={(v) => wrappedOnChange(v)}
          onBlur={field.onBlur}
          disabled={disabled}
          placeholder={placeholder}
          unstyled={unstyled}
          aria-invalid={hasErrors || undefined}
          aria-required={required || undefined}
          aria-describedby={describedBy}
        />
      ) : (
        <Input
          id={fieldId}
          type={type}
          value={(field.value as string) ?? ''}
          onChange={(v) => wrappedOnChange(type === 'number' ? Number(v) : v)}
          onBlur={field.onBlur}
          disabled={disabled}
          placeholder={placeholder}
          unstyled={unstyled}
          aria-invalid={hasErrors || undefined}
          aria-required={required || undefined}
          aria-describedby={describedBy}
        />
      )

    return (
      <>
        {inputElement}
        {feedbackIcon}
      </>
    )
  }

  // noStyle — just validation, no wrapper
  if (noStyle) {
    return <>{renderControl()}</>
  }

  // unstyled — minimal structure
  if (unstyled) {
    return (
      <>
        {labelNode}
        {renderControl()}
        {helpNode}
        {extraNode}
      </>
    )
  }

  // Horizontal layout with grid
  if (layout === 'horizontal' && lCol) {
    const labelSpan = lCol.span ?? 6
    const wrapperSpan = wCol?.span ?? 24 - labelSpan
    const labelPct = `${(labelSpan / 24) * 100}%`
    const wrapperPct = `${(wrapperSpan / 24) * 100}%`

    return (
      <div
        className={[
          'sg-field',
          'sg-field-horizontal',
          hasErrors ? 'sg-field-has-error' : '',
          hasWarnings && !hasErrors ? 'sg-field-has-warning' : '',
          effectiveStatus ? `sg-field-status-${effectiveStatus}` : '',
        ]
          .filter(Boolean)
          .join(' ')}
        data-field-name={name}
      >
        <div
          className="sg-field-label-wrap"
          style={{
            width: labelPct,
            textAlign: labelAlign,
          }}
        >
          {labelNode}
        </div>
        <div className="sg-field-control-wrap" style={{ width: wrapperPct }}>
          <div className="sg-field-control">{renderControl()}</div>
          {helpNode}
          {extraNode}
        </div>
      </div>
    )
  }

  // Default vertical / inline layout
  const fieldClasses = [
    'sg-field',
    hasErrors ? 'sg-field-has-error' : '',
    hasWarnings && !hasErrors ? 'sg-field-has-warning' : '',
    effectiveStatus ? `sg-field-status-${effectiveStatus}` : '',
  ]

  return (
    <div className={fieldClasses.filter(Boolean).join(' ')} data-field-name={name}>
      {labelNode}
      <div className="sg-field-control">{renderControl()}</div>
      {helpNode}
      {extraNode}
    </div>
  )
}

// packages/vue/src/components/complex/Form/Field.vue
<script setup lang="ts">
import { computed, inject, onBeforeUnmount, useSlots, watch } from 'vue'
import { useField } from '../../../composables/useField'
import { useConfig } from '../../ui/ConfigProvider.vue'
import { formContextKey } from './context'
import type { Rule, ValidationMode } from '@skygraph/core'

export interface FieldProps {
  /** Path of this field in the form store (required). */
  name: string
  /** Visible label text. */
  label?: string
  /** Validation rules. */
  rules?: Rule[]
  /** Warning rules — produce warnings without failing validation. */
  warningRules?: Rule[]
  /** When `true`, prepends a required rule in addition to `rules`. */
  required?: boolean
  /** Re-validates this field when any listed field changes. */
  dependencies?: string[]
  /** Events that trigger validation. */
  trigger?: ValidationMode | ValidationMode[]
  /** Helper text shown below the control when there are no errors / warnings. */
  help?: string
  /** Supplementary content below the control area. */
  extra?: string
  /** When `true`, value is preserved on unregister. */
  preserve?: boolean
  /** When `true`, the field renders nothing. */
  hidden?: boolean
  /** Disables the control; falls back to form context `disabled`. */
  disabled?: boolean
  /** Manual validation status badge. */
  validateStatus?: 'success' | 'warning' | 'error' | 'validating'
  /** Renders only the control without layout chrome. */
  noStyle?: boolean
  /** Maps raw change values before committing to the store. */
  normalize?: (value: unknown, prevValue: unknown) => unknown
  /** Stops after the first failing rule when validating. */
  validateFirst?: boolean
  /** Tooltip title wrapping the label text. */
  tooltip?: string
  /** Overrides form `labelCol` for this field in horizontal layout. */
  labelCol?: { span?: number; offset?: number }
  /** Overrides form `wrapperCol` for this field in horizontal layout. */
  wrapperCol?: { span?: number; offset?: number }
}

const props = withDefaults(defineProps<FieldProps>(), {
  rules: () => [],
  required: false,
  hidden: false,
  noStyle: false,
})

defineSlots<{
  default(props: {
    value: unknown
    onChange: (v: unknown) => void
    onBlur: () => void
    errors: string[]
    error: string | null
    warnings: string[]
    touched: boolean
    dirty: boolean
    validating: boolean
    status: string | undefined
  }): unknown
  label(props: Record<string, never>): unknown
}>()

const injected = inject(formContextKey, null)
if (!injected) {
  throw new Error('[skygraph/vue] <SgField> must be used inside an <SgForm>')
}
const ctx = injected

const field = useField(ctx.core, ctx.form, props.name)

const cfg = useConfig()
const requiredMarker = computed(() => cfg.value.locale?.form?.required ?? '*')
const optionalMarker = computed(() => cfg.value.locale?.form?.optional ?? '(optional)')
const showRequiredMark = computed(() => props.required || ctx.requiredMark === true)
const showOptionalMark = computed(() => ctx.requiredMark === 'optional' && !props.required)

const disabled = computed(() => props.disabled ?? ctx.disabled)

let prevValue: unknown = field.value.value
const wrappedOnChange = (v: unknown) => {
  if (props.normalize) {
    const normalized = props.normalize(v, prevValue)
    prevValue = normalized
    field.onChange(normalized)
  } else {
    prevValue = v
    field.onChange(v)
  }
}

function registerField() {
  const allRules: Rule[] = [...(props.rules ?? [])]
  if (props.required) {
    allRules.unshift({ required: true })
  }
  ctx.form.register(props.name, {
    rules: allRules,
    warningRules: props.warningRules,
    dependencies: props.dependencies,
    validateOn: Array.isArray(props.trigger) ? props.trigger[0] : props.trigger,
    validateFirst: props.validateFirst,
    label: props.label,
    preserve: props.preserve ?? ctx.preserve,
  })
}

registerField()

watch(
  () => [props.rules, props.required, props.warningRules, props.dependencies],
  () => {
    registerField()
  },
  { deep: true },
)

onBeforeUnmount(() => {
  ctx.form.unregister(props.name)
})

const hasErrors = computed(() => field.errors.value.length > 0)
const hasWarnings = computed(() => field.warnings.value.length > 0)
const effectiveStatus = computed(() => props.validateStatus ?? field.status.value)

const fieldClasses = computed(() =>
  [
    'sg-field',
    ctx.layout === 'horizontal' ? 'sg-field-horizontal' : '',
    hasErrors.value ? 'sg-field-has-error' : '',
    hasWarnings.value && !hasErrors.value ? 'sg-field-has-warning' : '',
    effectiveStatus.value ? `sg-field-status-${effectiveStatus.value}` : '',
  ]
    .filter(Boolean)
    .join(' '),
)

const slots = useSlots()
const hasLabelSlot = computed(() => Boolean(slots.label))

// ── Horizontal layout (24-col grid via labelCol / wrapperCol) ──────────
// Mirrors React `Field`: label and control each sit in their own flex
// column with explicit widths, and the error/help/extra nest *inside* the
// control column so they align under the input instead of spilling next to
// it (the old layout rendered label/control/error as three flex siblings).
const lCol = computed(() => props.labelCol ?? ctx.labelCol)
const wCol = computed(() => props.wrapperCol ?? ctx.wrapperCol)
const labelAlign = computed(() => ctx.labelAlign ?? 'right')
const isHorizontal = computed(() => ctx.layout === 'horizontal' && !!lCol.value)
const labelSpan = computed(() => lCol.value?.span ?? 6)
const wrapperSpan = computed(() => wCol.value?.span ?? 24 - labelSpan.value)
const labelPct = computed(() => `${(labelSpan.value / 24) * 100}%`)
const wrapperPct = computed(() => `${(wrapperSpan.value / 24) * 100}%`)
const labelOffsetStyle = computed(() =>
  ctx.layout === 'horizontal' && lCol.value?.offset
    ? { marginLeft: `${(lCol.value.offset / 24) * 100}%` }
    : undefined,
)
</script>

<template>
  <template v-if="!hidden">
    <template v-if="noStyle">
      <slot
        :value="field.value.value"
        :on-change="wrappedOnChange"
        :on-blur="field.onBlur"
        :errors="field.errors.value"
        :error="field.error.value"
        :warnings="field.warnings.value"
        :touched="field.touched.value"
        :dirty="field.dirty.value"
        :validating="field.validating.value"
        :status="effectiveStatus"
      />
    </template>
    <div v-else :class="fieldClasses" :data-field-name="name">
      <!-- Horizontal layout: label column + control column (error nests
           inside the control column so it aligns under the input). -->
      <template v-if="isHorizontal">
        <div class="sg-field-label-wrap" :style="{ width: labelPct, textAlign: labelAlign }">
          <label v-if="label || hasLabelSlot" class="sg-field-label" :style="labelOffsetStyle">
            <slot name="label">{{ label }}</slot>
            <span v-if="showRequiredMark" class="sg-field-required">{{ requiredMarker }}</span>
            <span v-else-if="showOptionalMark" class="sg-field-optional">{{ optionalMarker }}</span>
            <template v-if="ctx.colon">:</template>
          </label>
        </div>
        <div class="sg-field-control-wrap" :style="{ width: wrapperPct }">
          <div class="sg-field-control">
            <slot
              :value="field.value.value"
              :on-change="wrappedOnChange"
              :on-blur="field.onBlur"
              :errors="field.errors.value"
              :error="field.error.value"
              :warnings="field.warnings.value"
              :touched="field.touched.value"
              :dirty="field.dirty.value"
              :validating="field.validating.value"
              :status="effectiveStatus"
            >
              <input
                class="sg-input"
                type="text"
                :value="(field.value.value as string) ?? ''"
                :disabled="disabled"
                @input="(e) => wrappedOnChange((e.target as HTMLInputElement).value)"
                @blur="field.onBlur"
              />
            </slot>
          </div>
          <div v-if="hasErrors" class="sg-field-error" role="alert">
            <div v-for="(err, i) in field.errors.value" :key="i">{{ err }}</div>
          </div>
          <div v-else-if="hasWarnings" class="sg-field-warning">
            <div v-for="(w, i) in field.warnings.value" :key="i">{{ w }}</div>
          </div>
          <div v-else-if="help" class="sg-field-help">{{ help }}</div>
          <div v-if="extra" class="sg-field-extra">{{ extra }}</div>
        </div>
      </template>

      <!-- Vertical / inline layout -->
      <template v-else>
        <label v-if="label || hasLabelSlot" class="sg-field-label">
          <slot name="label">{{ label }}</slot>
          <span v-if="showRequiredMark" class="sg-field-required">{{ requiredMarker }}</span>
          <span v-else-if="showOptionalMark" class="sg-field-optional">{{ optionalMarker }}</span>
          <template v-if="ctx.colon">:</template>
        </label>
        <div class="sg-field-control">
          <slot
            :value="field.value.value"
            :on-change="wrappedOnChange"
            :on-blur="field.onBlur"
            :errors="field.errors.value"
            :error="field.error.value"
            :warnings="field.warnings.value"
            :touched="field.touched.value"
            :dirty="field.dirty.value"
            :validating="field.validating.value"
            :status="effectiveStatus"
          >
            <input
              class="sg-input"
              type="text"
              :value="(field.value.value as string) ?? ''"
              :disabled="disabled"
              @input="(e) => wrappedOnChange((e.target as HTMLInputElement).value)"
              @blur="field.onBlur"
            />
          </slot>
        </div>
        <div v-if="hasErrors" class="sg-field-error" role="alert">
          <div v-for="(err, i) in field.errors.value" :key="i">{{ err }}</div>
        </div>
        <div v-else-if="hasWarnings" class="sg-field-warning">
          <div v-for="(w, i) in field.warnings.value" :key="i">{{ w }}</div>
        </div>
        <div v-else-if="help" class="sg-field-help">{{ help }}</div>
        <div v-if="extra" class="sg-field-extra">{{ extra }}</div>
      </template>
    </div>
  </template>
</template>
