// packages/vue/src/components/ui/AutoComplete.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useConfigWithDefaults } from './ConfigProvider.vue'

export interface AutoCompleteOption {
  /** Optional display text — falls back to `value`. */
  label?: string
  /** Stored value emitted on select. */
  value: string
}

export interface AutoCompleteProps {
  /** v-model binding (Vue idiom). */
  modelValue?: string
  /** Compat alias for `modelValue`. */
  value?: string
  /** Initial value when uncontrolled. */
  defaultValue?: string
  /** Suggestion list; filtered by label against current input. */
  options: AutoCompleteOption[]
  /** Input placeholder text. */
  placeholder?: string
  /** Disables editing. */
  disabled?: boolean
  /** Shows a loading spinner and disables interaction. */
  loading?: boolean
  /** Size token. */
  size?: 'small' | 'middle' | 'large'
  /** Strips built-in styling. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<AutoCompleteProps>(), {
  disabled: undefined,
  loading: false,
  size: 'middle',
})

const { resolvedDisabled } = useConfigWithDefaults({ disabled: props.disabled }, {})

const isDisabled = computed(() => resolvedDisabled.value || props.loading)

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'change', value: string): void
  (e: 'search', value: string): void
  (e: 'select', value: string, option: AutoCompleteOption): void
  (e: 'blur'): void
}>()

const internal = ref<string>(props.modelValue ?? props.value ?? props.defaultValue ?? '')
watch(
  () => props.modelValue ?? props.value,
  (v) => {
    if (v !== undefined) internal.value = v
  },
)

const current = computed(() => props.modelValue ?? props.value ?? internal.value)
const open = ref(false)
const wrapperRef = ref<HTMLDivElement | null>(null)

const filtered = computed(() =>
  props.options.filter((o) =>
    (o.label ?? o.value).toLowerCase().includes((current.value ?? '').toLowerCase()),
  ),
)

function handleInput(e: Event) {
  const v = (e.target as HTMLInputElement).value
  internal.value = v
  emit('update:modelValue', v)
  emit('change', v)
  emit('search', v)
  open.value = true
}

function handleSelect(opt: AutoCompleteOption) {
  internal.value = opt.value
  emit('update:modelValue', opt.value)
  emit('change', opt.value)
  emit('select', opt.value, opt)
  open.value = false
}

function handleOutside(e: MouseEvent) {
  if (wrapperRef.value && !wrapperRef.value.contains(e.target as Node)) {
    open.value = false
  }
}

onMounted(() => document.addEventListener('mousedown', handleOutside))
onBeforeUnmount(() => document.removeEventListener('mousedown', handleOutside))

const wrapperClass = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-autocomplete',
        `sg-autocomplete-${props.size}`,
        props.loading ? 'sg-autocomplete-loading' : '',
      ]
        .filter(Boolean)
        .join(' '),
)
</script>

<template>
  <div ref="wrapperRef" :class="wrapperClass">
    <span :class="unstyled ? '' : 'sg-input-wrapper'">
      <input
        type="text"
        role="combobox"
        aria-autocomplete="list"
        :aria-expanded="open && filtered.length > 0"
        :class="unstyled ? '' : `sg-input sg-input-${size}`"
        :value="current"
        :placeholder="placeholder"
        :disabled="isDisabled"
        @input="handleInput"
        @focus="open = true"
        @blur="emit('blur')"
      />
      <span v-if="loading && !unstyled" class="sg-spin sg-spin-small" aria-hidden="true" />
    </span>
    <div v-if="open && filtered.length > 0" :class="unstyled ? '' : 'sg-autocomplete-dropdown'">
      <div
        v-for="opt in filtered"
        :key="opt.value"
        :class="unstyled ? '' : 'sg-autocomplete-option'"
        @mousedown="handleSelect(opt)"
      >
        {{ opt.label ?? opt.value }}
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/ui/AutoComplete.tsx
import React, { useState, useRef, useEffect } from 'react'
import { Spin } from './Spin'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps, SizableProps } from '../../types'

/** Suggestion row shown in the AutoComplete dropdown. */
export interface AutoCompleteOption {
  /** Text shown in the list; also used for client-side filtering. */
  label: string
  /** Value written to the input when the row is chosen. */
  value: string
}

/** Props for text input with filtered suggestions and optional callbacks. */
export interface AutoCompleteProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Controlled input value. */
  value?: string
  /** Initial value when uncontrolled. */
  defaultValue?: string
  /** Suggestion list; filtered by label against current input. */
  options: AutoCompleteOption[]
  /** Input placeholder text. */
  placeholder?: string
  /** Called when the typed value changes. */
  onChange?: (value: string) => void
  /** Called on each change with the current query string. */
  onSearch?: (query: string) => void
  /** Called when a suggestion is picked from the list. */
  onSelect?: (value: string, option: AutoCompleteOption) => void
  /** Called when the input loses focus. */
  onBlur?: () => void
}

/**
 * Text field with a dropdown of options filtered as the user types.
 * Opens the list on focus and filters by option label (case-insensitive).
 */
export function AutoComplete({
  value,
  defaultValue,
  options,
  placeholder,
  disabled: disabledProp,
  loading,
  size: sizeProp,
  onChange,
  onSearch,
  onSelect,
  onBlur,
  className,
  style,
  unstyled,
}: AutoCompleteProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const disabled = disabledProp ?? config.disabled ?? false

  const [internalValue, setInternalValue] = useState(value ?? defaultValue ?? '')
  const [open, setOpen] = useState(false)
  const ref = useRef<HTMLDivElement>(null)
  const currentValue = value ?? internalValue

  const filtered = options.filter((o) =>
    o.label.toLowerCase().includes(currentValue.toLowerCase())
  )

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const v = e.target.value
    setInternalValue(v)
    onChange?.(v)
    onSearch?.(v)
    setOpen(true)
  }

  const handleSelect = (opt: AutoCompleteOption) => {
    setInternalValue(opt.value)
    onChange?.(opt.value)
    onSelect?.(opt.value, opt)
    setOpen(false)
  }

  const wrapperClass = unstyled
    ? className ?? ''
    : ['sg-autocomplete', `sg-autocomplete-${size}`, loading ? 'sg-autocomplete-loading' : '', className]
        .filter(Boolean)
        .join(' ')

  return (
    <div className={wrapperClass} ref={ref} style={style}>
      <span className={unstyled ? '' : 'sg-input-wrapper'}>
        <input
          type="text"
          role="combobox"
          aria-autocomplete="list"
          aria-expanded={open && filtered.length > 0}
          className={unstyled ? '' : `sg-input sg-input-${size}`}
          value={currentValue}
          placeholder={placeholder}
          disabled={disabled || loading}
          onChange={handleChange}
          onFocus={() => setOpen(true)}
          onBlur={onBlur}
        />
        {loading && <Spin size="small" unstyled={unstyled} />}
      </span>
      {open && filtered.length > 0 && (
        <div className={unstyled ? '' : 'sg-autocomplete-dropdown'}>
          {filtered.map((opt) => (
            <div
              key={opt.value}
              className={unstyled ? '' : 'sg-autocomplete-option'}
              onMouseDown={() => handleSelect(opt)}
            >
              {opt.label}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
