// packages/vue/src/components/ui/Mentions.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import type { SizeType } from '../../types'
import { useConfigWithDefaults } from './ConfigProvider.vue'

export interface MentionOption {
  value: string
  label?: string
  disabled?: boolean
}

export interface MentionsProps {
  /** v-model binding (Vue idiom). */
  modelValue?: string
  /** Compat alias. */
  value?: string
  /** Initial value when uncontrolled. */
  defaultValue?: string
  /** Placeholder text. */
  placeholder?: string
  /** Mention prefix character(s). */
  prefix?: string | string[]
  /** Number of textarea rows. */
  rows?: number
  /** Mention suggestion options. */
  options?: MentionOption[]
  /** Vertical position of the suggestion dropdown relative to the field. */
  placement?: 'top' | 'bottom'
  /** Disables interaction. */
  disabled?: boolean
  /** Component size. */
  size?: SizeType
  /** Strips built-in styling. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<MentionsProps>(), {
  prefix: '@',
  rows: 3,
  options: () => [],
  placement: 'bottom',
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'change', value: string): void
  (e: 'search', text: string, prefix: string): void
  (e: 'select', option: MentionOption, prefix: string): void
}>()

const { resolvedSize, resolvedDisabled } = useConfigWithDefaults(props, {})

const internal = ref<string>(props.modelValue ?? props.value ?? props.defaultValue ?? '')
watch(
  () => props.modelValue ?? props.value,
  (v) => {
    if (v !== undefined) internal.value = v
  },
)
const current = computed(() => props.modelValue ?? props.value ?? internal.value)

const showSuggest = ref(false)
const search = ref('')
const activePrefix = ref('')
const startIndex = ref(0)
const activeIndex = ref(0)
const textareaRef = ref<HTMLTextAreaElement | null>(null)
const dropdownRef = ref<HTMLDivElement | null>(null)

const prefixes = computed(() => (Array.isArray(props.prefix) ? props.prefix : [props.prefix]))

function handleInput(e: Event) {
  const target = e.target as HTMLTextAreaElement
  const v = target.value
  internal.value = v
  emit('update:modelValue', v)
  emit('change', v)

  const pos = target.selectionStart ?? v.length
  const before = v.slice(0, pos)

  for (const p of prefixes.value) {
    const idx = before.lastIndexOf(p)
    if (idx >= 0) {
      const charBefore = idx > 0 ? before[idx - 1] : ' '
      if (charBefore === ' ' || charBefore === '\n' || idx === 0) {
        const between = before.slice(idx + p.length)
        if (!between.includes(' ')) {
          activePrefix.value = p
          search.value = between
          startIndex.value = idx
          showSuggest.value = true
          activeIndex.value = 0
          emit('search', between, p)
          return
        }
      }
    }
  }
  showSuggest.value = false
}

const filteredOptions = computed(() =>
  props.options.filter(
    (o) => !search.value || (o.label ?? o.value).toLowerCase().includes(search.value.toLowerCase()),
  ),
)

function selectOption(opt: MentionOption) {
  if (opt.disabled) return
  const v = current.value
  const before = v.slice(0, startIndex.value)
  const after = v.slice(startIndex.value + activePrefix.value.length + search.value.length)
  const insertText = `${activePrefix.value}${opt.value} `
  const newValue = before + insertText + after
  internal.value = newValue
  emit('update:modelValue', newValue)
  emit('change', newValue)
  emit('select', opt, activePrefix.value)
  showSuggest.value = false
  void nextTick(() => {
    if (textareaRef.value) {
      const newPos = before.length + insertText.length
      textareaRef.value.focus()
      textareaRef.value.setSelectionRange(newPos, newPos)
    }
  })
}

function handleKeyDown(e: KeyboardEvent) {
  if (!showSuggest.value || filteredOptions.value.length === 0) return
  if (e.key === 'ArrowDown') {
    e.preventDefault()
    activeIndex.value = (activeIndex.value + 1) % filteredOptions.value.length
  } else if (e.key === 'ArrowUp') {
    e.preventDefault()
    activeIndex.value =
      (activeIndex.value - 1 + filteredOptions.value.length) % filteredOptions.value.length
  } else if (e.key === 'Enter') {
    e.preventDefault()
    selectOption(filteredOptions.value[activeIndex.value])
  } else if (e.key === 'Escape') {
    showSuggest.value = false
  }
}

function onClickOutside(e: MouseEvent) {
  if (
    dropdownRef.value &&
    !dropdownRef.value.contains(e.target as Node) &&
    textareaRef.value &&
    !textareaRef.value.contains(e.target as Node)
  ) {
    showSuggest.value = false
  }
}

onMounted(() => {
  document.addEventListener('mousedown', onClickOutside)
})
onBeforeUnmount(() => {
  document.removeEventListener('mousedown', onClickOutside)
})

const wrapperCls = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-mentions',
        `sg-mentions-${resolvedSize.value}`,
        resolvedDisabled.value ? 'sg-mentions-disabled' : '',
      ]
        .filter(Boolean)
        .join(' '),
)
</script>

<template>
  <div :class="wrapperCls">
    <textarea
      ref="textareaRef"
      :class="unstyled ? '' : 'sg-input sg-textarea'"
      :value="current"
      :placeholder="placeholder"
      :rows="rows"
      :disabled="resolvedDisabled"
      @input="handleInput"
      @keydown="handleKeyDown"
    />
    <div
      v-if="showSuggest && filteredOptions.length"
      ref="dropdownRef"
      :class="unstyled ? '' : `sg-mentions-dropdown sg-mentions-dropdown-${placement}`"
      role="listbox"
    >
      <div
        v-for="(opt, i) in filteredOptions"
        :key="opt.value"
        :class="
          unstyled
            ? ''
            : [
                'sg-mentions-option',
                i === activeIndex ? 'sg-mentions-option-active' : '',
                opt.disabled ? 'sg-mentions-option-disabled' : '',
              ]
                .filter(Boolean)
                .join(' ')
        "
        role="option"
        :aria-selected="i === activeIndex"
        @mousedown.prevent="selectOption(opt)"
        @mouseenter="activeIndex = i"
      >
        {{ opt.label ?? opt.value }}
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/ui/Mentions.tsx
import React, { useState, useRef, useEffect, useMemo, useCallback } from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps, SizableProps } from '../../types'

/** One mention candidate in the suggestion list. */
export interface MentionOption {
  /** Text inserted after the trigger prefix when the row is chosen. */
  value: string
  /** Optional display string; defaults to value when omitted. */
  label?: string
}

/** Props for a textarea that shows mention suggestions after a prefix. */
export interface MentionsProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Controlled textarea value. */
  value?: string
  /** Initial value when uncontrolled. */
  defaultValue?: string
  /** Called when the textarea content changes. */
  onChange?: (value: string) => void
  /** Character(s) that start a mention (e.g. @ or #). */
  prefix?: string | string[]
  /** Suggestion list filtered by the text after the active prefix. */
  options?: MentionOption[]
  /** Vertical position of the suggestion dropdown relative to the field. */
  placement?: 'top' | 'bottom'
  /** Called with the current query and matched prefix while typing a mention. */
  onSearch?: (text: string, prefix: string) => void
  /** Called when a suggestion is inserted into the text. */
  onSelect?: (option: MentionOption, prefix: string) => void
  /** Textarea placeholder. */
  placeholder?: string
  /** Visible height of the textarea in rows. */
  rows?: number
}

interface MentionState {
  active: boolean
  prefix: string
  query: string
  startIndex: number
}

/**
 * Textarea with @-style mentions: shows a filtered list after a configured prefix.
 * Supports keyboard navigation (arrows, Enter, Escape) when the list is open.
 *
 * @default defaultValue - `''`
 * @default prefix - `'@'`
 * @default options - `[]`
 * @default placement - `'bottom'`
 * @default rows - `3`
 */
export function Mentions({
  value,
  defaultValue = '',
  onChange,
  prefix: prefixConfig = '@',
  options = [],
  placement = 'bottom',
  onSearch,
  onSelect,
  placeholder,
  rows = 3,
  disabled: disabledProp,
  size: sizeProp,
  className,
  style,
  unstyled,
}: MentionsProps) {
  const config = useConfig()
  const disabled = disabledProp ?? config.disabled
  const size = sizeProp ?? config.size ?? 'middle'

  const prefixes = useMemo(
    () => (Array.isArray(prefixConfig) ? prefixConfig : [prefixConfig]),
    [prefixConfig],
  )

  const [internalValue, setInternalValue] = useState(value ?? defaultValue)
  const currentValue = value ?? internalValue
  const [mentionState, setMentionState] = useState<MentionState | null>(null)
  const [activeIndex, setActiveIndex] = useState(0)
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const dropdownRef = useRef<HTMLDivElement>(null)

  const filteredOptions = useMemo(() => {
    if (!mentionState) return []
    const q = mentionState.query.toLowerCase()
    return options.filter((opt) => {
      const label = (opt.label ?? opt.value).toLowerCase()
      return label.includes(q)
    })
  }, [options, mentionState])

  const handleChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newValue = e.target.value
    setInternalValue(newValue)
    onChange?.(newValue)

    const cursorPos = e.target.selectionStart ?? 0
    const textBeforeCursor = newValue.slice(0, cursorPos)

    let foundMention: MentionState | null = null
    for (const p of prefixes) {
      const lastPrefixIdx = textBeforeCursor.lastIndexOf(p)
      if (lastPrefixIdx >= 0) {
        const charBefore = lastPrefixIdx > 0 ? textBeforeCursor[lastPrefixIdx - 1] : ' '
        if (charBefore === ' ' || charBefore === '\n' || lastPrefixIdx === 0) {
          const query = textBeforeCursor.slice(lastPrefixIdx + p.length)
          if (!query.includes(' ')) {
            foundMention = { active: true, prefix: p, query, startIndex: lastPrefixIdx }
            break
          }
        }
      }
    }

    if (foundMention) {
      setMentionState(foundMention)
      setActiveIndex(0)
      onSearch?.(foundMention.query, foundMention.prefix)
    } else {
      setMentionState(null)
    }
  }, [onChange, prefixes, onSearch])

  const insertMention = useCallback((option: MentionOption) => {
    if (!mentionState || !textareaRef.current) return
    const textarea = textareaRef.current
    const before = currentValue.slice(0, mentionState.startIndex)
    const after = currentValue.slice(mentionState.startIndex + mentionState.prefix.length + mentionState.query.length)
    const insertText = `${mentionState.prefix}${option.value} `
    const newValue = before + insertText + after

    setInternalValue(newValue)
    onChange?.(newValue)
    onSelect?.(option, mentionState.prefix)
    setMentionState(null)

    requestAnimationFrame(() => {
      const pos = before.length + insertText.length
      textarea.focus()
      textarea.setSelectionRange(pos, pos)
    })
  }, [mentionState, currentValue, onChange, onSelect])

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (!mentionState || filteredOptions.length === 0) return

    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setActiveIndex((i) => (i + 1) % filteredOptions.length)
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setActiveIndex((i) => (i - 1 + filteredOptions.length) % filteredOptions.length)
    } else if (e.key === 'Enter') {
      e.preventDefault()
      insertMention(filteredOptions[activeIndex])
    } else if (e.key === 'Escape') {
      setMentionState(null)
    }
  }, [mentionState, filteredOptions, activeIndex, insertMention])

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node) &&
          textareaRef.current && !textareaRef.current.contains(e.target as Node)) {
        setMentionState(null)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  const wrapperClass = unstyled
    ? className ?? ''
    : ['sg-mentions', `sg-mentions-${size}`, disabled ? 'sg-mentions-disabled' : '', className].filter(Boolean).join(' ')

  return (
    <div className={wrapperClass} style={{ ...style, position: 'relative' }}>
      <textarea
        ref={textareaRef}
        className={unstyled ? '' : 'sg-input sg-textarea'}
        value={currentValue}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        placeholder={placeholder}
        rows={rows}
        disabled={disabled}
      />
      {mentionState && filteredOptions.length > 0 && (
        <div
          ref={dropdownRef}
          className={unstyled ? '' : `sg-mentions-dropdown sg-mentions-dropdown-${placement}`}
          role="listbox"
        >
          {filteredOptions.map((opt, i) => (
            <div
              key={opt.value}
              className={unstyled ? '' : [
                'sg-mentions-option',
                i === activeIndex ? 'sg-mentions-option-active' : '',
              ].filter(Boolean).join(' ')}
              role="option"
              aria-selected={i === activeIndex}
              onClick={() => insertMention(opt)}
              onMouseEnter={() => setActiveIndex(i)}
            >
              {opt.label ?? opt.value}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
