// packages/vue/src/components/ui/Skeleton.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useConfig } from './ConfigProvider.vue'

export interface SkeletonAvatar {
  size?: number
  shape?: 'circle' | 'square'
}

export interface SkeletonTitle {
  width?: number | string
}

export interface SkeletonParagraph {
  rows?: number
  width?: Array<number | string>
}

export interface SkeletonProps {
  /** Enables a shimmering animation. @default false */
  active?: boolean
  /** Shows an avatar block; pass an object for `size` and `shape`. */
  avatar?: boolean | SkeletonAvatar
  /** Shows a title bar; pass an object for custom `width`. @default true */
  title?: boolean | SkeletonTitle
  /** Shows paragraph lines; pass an object for `rows` and per-line `width`. @default true */
  paragraph?: boolean | SkeletonParagraph
  /** When false, renders default slot instead of the skeleton. @default true */
  loading?: boolean
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<SkeletonProps>(), {
  active: false,
  title: true,
  paragraph: true,
  loading: true,
})

defineSlots<{
  default(props: Record<string, never>): unknown
}>()

const avatarSize = computed(() =>
  typeof props.avatar === 'object' ? (props.avatar.size ?? 40) : 40,
)
const avatarShape = computed(() =>
  typeof props.avatar === 'object' ? (props.avatar.shape ?? 'circle') : 'circle',
)
const titleWidth = computed<string | number>(() =>
  typeof props.title === 'object' ? (props.title.width ?? '38%') : '38%',
)
const rows = computed(() => (typeof props.paragraph === 'object' ? (props.paragraph.rows ?? 3) : 3))
const rowWidths = computed(() =>
  typeof props.paragraph === 'object' ? props.paragraph.width : undefined,
)

function getRowWidth(index: number, total: number): string | number {
  const widths = rowWidths.value
  if (widths && widths[index] !== undefined) return widths[index]
  if (index === total - 1) return '61%'
  return '100%'
}

function toCss(w: string | number): string {
  return typeof w === 'number' ? `${w}px` : w
}

const cfg = useConfig()
const loadingLabel = computed(() => cfg.value.locale?.skeleton?.loading ?? 'Loading')

const rootClasses = computed(() =>
  [
    'sg-skeleton',
    props.active ? 'sg-skeleton-active' : '',
    props.avatar ? 'sg-skeleton-with-avatar' : '',
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <slot v-if="!loading" />
  <div v-else-if="unstyled" aria-busy="true" :aria-label="loadingLabel">
    <div v-if="avatar" :style="{ width: `${avatarSize}px`, height: `${avatarSize}px` }" />
    <div>
      <div v-if="title" :style="{ width: toCss(titleWidth), height: '16px' }" />
      <template v-if="paragraph">
        <div
          v-for="i in rows"
          :key="i"
          :style="{ width: toCss(getRowWidth(i - 1, rows)), height: '16px' }"
        />
      </template>
    </div>
  </div>
  <div v-else :class="rootClasses" aria-busy="true" :aria-label="loadingLabel">
    <div v-if="avatar" class="sg-skeleton-header">
      <span
        :class="['sg-skeleton-avatar', `sg-skeleton-avatar-${avatarShape}`]"
        :style="{ width: `${avatarSize}px`, height: `${avatarSize}px` }"
      />
    </div>
    <div class="sg-skeleton-content">
      <div v-if="title" class="sg-skeleton-title" :style="{ width: toCss(titleWidth) }" />
      <ul v-if="paragraph" class="sg-skeleton-paragraph">
        <li v-for="i in rows" :key="i" :style="{ width: toCss(getRowWidth(i - 1, rows)) }" />
      </ul>
    </div>
  </div>
</template>

// packages/react/src/components/ui/Skeleton.tsx
import React from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps } from '../../types'

/** Props for the Skeleton loading placeholder layout. */
export interface SkeletonProps extends BaseComponentProps {
  /** Enables a shimmering animation on placeholders. @default false */
  active?: boolean
  /** Shows an avatar block; pass an object for `size` and `shape`. */
  avatar?: boolean | { size?: number; shape?: 'circle' | 'square' }
  /** Shows a title bar; pass an object for custom `width`. @default true */
  title?: boolean | { width?: number | string }
  /** Shows paragraph lines; pass an object for `rows` and per-line `width`. @default true */
  paragraph?: boolean | { rows?: number; width?: Array<number | string> }
  /** When false, renders `children` instead of the skeleton. @default true */
  loading?: boolean
  /** Real content shown when `loading` is false. */
  children?: React.ReactNode
}

/**
 * Placeholder UI while content loads; supports avatar, title, and paragraph blocks.
 */
export function Skeleton({
  active = false,
  avatar,
  title = true,
  paragraph = true,
  loading = true,
  children,
  className,
  style,
  unstyled,
}: SkeletonProps) {
  const loadingLabel = useConfig().locale?.skeleton?.loading ?? 'Loading'
  if (!loading) return <>{children}</>

  const avatarSize = typeof avatar === 'object' ? (avatar.size ?? 40) : 40
  const avatarShape = typeof avatar === 'object' ? (avatar.shape ?? 'circle') : 'circle'
  const titleWidth = typeof title === 'object' ? (title.width ?? '38%') : '38%'
  const rows = typeof paragraph === 'object' ? (paragraph.rows ?? 3) : 3
  const rowWidths = typeof paragraph === 'object' ? paragraph.width : undefined

  const getRowWidth = (index: number, total: number): string | number => {
    if (rowWidths && rowWidths[index] !== undefined) return rowWidths[index]
    if (index === total - 1) return '61%'
    return '100%'
  }

  if (unstyled) {
    return (
      <div className={className} style={style} aria-busy="true" aria-label={loadingLabel}>
        {avatar && <div style={{ width: avatarSize, height: avatarSize }} />}
        <div>
          {title && <div style={{ width: titleWidth, height: 16 }} />}
          {paragraph &&
            Array.from({ length: rows }, (_, i) => (
              <div key={i} style={{ width: getRowWidth(i, rows), height: 16 }} />
            ))}
        </div>
      </div>
    )
  }

  return (
    <div
      className={[
        'sg-skeleton',
        active ? 'sg-skeleton-active' : '',
        avatar ? 'sg-skeleton-with-avatar' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      style={style}
      aria-busy="true"
      aria-label={loadingLabel}
    >
      {avatar && (
        <div className="sg-skeleton-header">
          <span
            className={['sg-skeleton-avatar', `sg-skeleton-avatar-${avatarShape}`].join(' ')}
            style={{ width: avatarSize, height: avatarSize }}
          />
        </div>
      )}
      <div className="sg-skeleton-content">
        {title && (
          <div
            className="sg-skeleton-title"
            style={{ width: typeof titleWidth === 'number' ? `${titleWidth}px` : titleWidth }}
          />
        )}
        {paragraph && (
          <ul className="sg-skeleton-paragraph">
            {Array.from({ length: rows }, (_, i) => {
              const w = getRowWidth(i, rows)
              return <li key={i} style={{ width: typeof w === 'number' ? `${w}px` : w }} />
            })}
          </ul>
        )}
      </div>
    </div>
  )
}
