// packages/vue/src/components/ui/Tag.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import { useConfig } from './ConfigProvider.vue'

export interface TagProps {
  /** Preset semantic color or any CSS color string. @default 'default' */
  color?: 'default' | 'success' | 'error' | 'warning' | 'processing' | string
  /** Shows a close control when true. */
  closable?: boolean
  /** Whether to draw a border. @default true */
  bordered?: boolean
  /** Strips built-in styles when true. */
  unstyled?: boolean
}

const props = withDefaults(defineProps<TagProps>(), {
  color: 'default',
  bordered: true,
})

const emit = defineEmits<{
  (e: 'close'): void
}>()

defineSlots<{
  default(props: Record<string, never>): unknown
}>()

const PRESET = new Set(['default', 'success', 'error', 'warning', 'processing'])

const isPreset = computed(() => PRESET.has(props.color))

const classes = computed(() =>
  [
    'sg-tag',
    isPreset.value ? `sg-tag-${props.color}` : '',
    props.bordered ? '' : 'sg-tag-borderless',
  ]
    .filter(Boolean)
    .join(' '),
)

const customStyle = computed<CSSProperties | undefined>(() =>
  isPreset.value ? undefined : { background: props.color, borderColor: props.color, color: '#fff' },
)

const cfg = useConfig()
const closeLabel = computed(() => cfg.value.locale?.tag?.closeAriaLabel ?? 'Close')

function handleClose(e: Event) {
  e.stopPropagation()
  emit('close')
}
</script>

<template>
  <span v-if="unstyled">
    <slot />
    <span v-if="closable" role="button" @click="handleClose">×</span>
  </span>
  <span v-else :class="classes" :style="customStyle">
    <slot />
    <span
      v-if="closable"
      class="sg-tag-close"
      role="button"
      :aria-label="closeLabel"
      @click="handleClose"
    >
      ×
    </span>
  </span>
</template>

// packages/react/src/components/ui/Tag.tsx
import React from 'react'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, SizableProps } from '../../types'

/** Props for the Tag component (label with optional close control). */
export interface TagProps extends BaseComponentProps, SizableProps {
  /** Preset semantic color or any CSS color string for custom tags. @default 'default' */
  color?: 'default' | 'success' | 'error' | 'warning' | 'processing' | string
  /** Shows a close control when true. */
  closable?: boolean
  /** Called when the close control is activated. */
  onClose?: () => void
  /** Whether to show a border around the tag. @default true */
  bordered?: boolean
  /** Tag label content. */
  children: React.ReactNode
}

const presetColors = new Set(['default', 'success', 'error', 'warning', 'processing'])

/**
 * Inline label tag with optional preset colors and closable behavior.
 */
export function Tag({
  color = 'default',
  closable,
  onClose,
  bordered = true,
  children,
  className,
  style,
  unstyled,
}: TagProps) {
  const closeAriaLabel = useConfig().locale?.tag?.closeAriaLabel ?? 'Close'
  if (unstyled) {
    return (
      <span className={className} style={style}>
        {children}
        {closable && (
          <span onClick={onClose} role="button">
            ×
          </span>
        )}
      </span>
    )
  }

  const isPreset = presetColors.has(color)
  const classes = [
    'sg-tag',
    isPreset ? `sg-tag-${color}` : '',
    bordered ? '' : 'sg-tag-borderless',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  const customStyle: React.CSSProperties = isPreset
    ? { ...style }
    : { ...style, background: color, borderColor: color, color: '#fff' }

  return (
    <span className={classes} style={customStyle}>
      {children}
      {closable && (
        <span
          className="sg-tag-close"
          onClick={(e) => {
            e.stopPropagation()
            onClose?.()
          }}
          role="button"
          aria-label={closeAriaLabel}
        >
          ×
        </span>
      )}
    </span>
  )
}
