// packages/vue/src/components/ui/TimePicker.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useConfig } from './ConfigProvider.vue'

export interface TimePickerProps {
  /** v-model binding (Vue idiom). */
  modelValue?: string
  /** Compat alias for `modelValue`. */
  value?: string
  /** Initial value when uncontrolled. */
  defaultValue?: string
  /** Placeholder text. */
  placeholder?: string
  /** Display format. */
  format?: string
  /** Use 12-hour clock with AM/PM column. */
  use12Hours?: boolean
  /** Step between hour values. */
  hourStep?: number
  /** Step between minute values. */
  minuteStep?: number
  /** Step between second values. */
  secondStep?: number
  /** Show seconds column. */
  showSecond?: boolean
  /** Show "Now" button. */
  showNow?: boolean
  /** Show clear control. */
  allowClear?: boolean
  /** Controlled visibility of the dropdown. */
  open?: boolean
  /** Disables interaction. */
  disabled?: boolean
  /** Shows a loading spinner and disables interaction. */
  loading?: boolean
  /** Size token. */
  size?: 'small' | 'middle' | 'large'
  /** Strips built-in styling. */
  unstyled?: boolean
  /** Hour values to disable in the hour column. */
  disabledHours?: () => number[]
  /** Minute values to disable for the currently picked hour. */
  disabledMinutes?: (hour: number) => number[]
  /** Second values to disable for the currently picked hour + minute. */
  disabledSeconds?: (hour: number, minute: number) => number[]
  /**
   * Reserved for read-only input behavior (mirrors the React adapter; the
   * Vue trigger is already a non-editable button so this is a no-op kept
   * for parity).
   */
  inputReadOnly?: boolean
  /** Accessible name for the trigger button. */
  ariaLabel?: string
  /** Id(s) of the element(s) that label the trigger. */
  ariaLabelledby?: string
}

const props = withDefaults(defineProps<TimePickerProps>(), {
  placeholder: 'Select time',
  use12Hours: false,
  hourStep: 1,
  minuteStep: 1,
  secondStep: 1,
  showSecond: true,
  showNow: true,
  allowClear: true,
  size: 'middle',
  disabled: false,
  loading: false,
  open: undefined,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'change', value: string): void
  (e: 'openChange', open: boolean): void
}>()

function pad(n: number) {
  return String(n).padStart(2, '0')
}

function formatTime(h: number, m: number, s: number, fmt: string, use12: boolean): string {
  if (use12) {
    const period = h >= 12 ? 'PM' : 'AM'
    const h12 = h % 12 || 12
    return fmt
      .replace('hh', pad(h12))
      .replace('mm', pad(m))
      .replace('ss', pad(s))
      .replace('A', period)
  }
  return fmt.replace('HH', pad(h)).replace('mm', pad(m)).replace('ss', pad(s))
}

function parseTime(str: string): { h: number; m: number; s: number } | null {
  if (!str) return null
  const upper = str.toUpperCase()
  const isPM = upper.includes('PM')
  const cleaned = upper.replace(/(AM|PM)/g, '').trim()
  const parts = cleaned.split(':').map(Number)
  if (parts.some(isNaN)) return null
  let h = parts[0] ?? 0
  const m = parts[1] ?? 0
  const s = parts[2] ?? 0
  if (isPM && h < 12) h += 12
  if (!isPM && upper.includes('AM') && h === 12) h = 0
  return { h, m, s }
}

const cfg = useConfig()
const clearLabel = computed(() => cfg.value.locale?.input?.clear ?? 'Clear')
const nowLabel = computed(() => cfg.value.locale?.calendar?.now ?? 'Now')

const fmt = computed(
  () => props.format ?? (props.use12Hours ? 'hh:mm:ss A' : props.showSecond ? 'HH:mm:ss' : 'HH:mm'),
)
const internal = ref<string>(props.modelValue ?? props.value ?? props.defaultValue ?? '')
watch(
  () => props.modelValue ?? props.value,
  (v) => {
    if (v !== undefined) internal.value = v
  },
)
const current = computed(() => props.modelValue ?? props.value ?? internal.value)

const internalOpen = ref(false)
const isOpen = computed(() => props.open ?? internalOpen.value)

const parsed = computed(() => parseTime(current.value))
const hour = ref(parsed.value?.h ?? 0)
const minute = ref(parsed.value?.m ?? 0)
const second = ref(parsed.value?.s ?? 0)

watch(current, (v) => {
  const p = parseTime(v)
  if (p) {
    hour.value = p.h
    minute.value = p.m
    second.value = p.s
  }
})

const wrapperRef = ref<HTMLDivElement | null>(null)
const hourColRef = ref<HTMLDivElement | null>(null)
const minuteColRef = ref<HTMLDivElement | null>(null)
const secondColRef = ref<HTMLDivElement | null>(null)

const hours = computed(() => {
  const arr: number[] = []
  if (props.use12Hours) {
    for (let i = 1; i <= 12; i += props.hourStep) arr.push(i)
  } else {
    for (let i = 0; i < 24; i += props.hourStep) arr.push(i)
  }
  return arr
})
const minutes = computed(() => {
  const arr: number[] = []
  for (let i = 0; i < 60; i += props.minuteStep) arr.push(i)
  return arr
})
const seconds = computed(() => {
  const arr: number[] = []
  for (let i = 0; i < 60; i += props.secondStep) arr.push(i)
  return arr
})

const disabledHourSet = computed(() => new Set(props.disabledHours?.() ?? []))
const disabledMinuteSet = computed(() => new Set(props.disabledMinutes?.(hour.value) ?? []))
const disabledSecondSet = computed(
  () => new Set(props.disabledSeconds?.(hour.value, minute.value) ?? []),
)

const displayHour = computed(() => (props.use12Hours ? hour.value % 12 || 12 : hour.value))

function setOpen(v: boolean) {
  internalOpen.value = v
  emit('openChange', v)
}

function commit(h: number, m: number, s: number) {
  const str = formatTime(h, m, s, fmt.value, props.use12Hours)
  internal.value = str
  emit('update:modelValue', str)
  emit('change', str)
}

function setH(h: number) {
  if (disabledHourSet.value.has(props.use12Hours ? h : h)) return
  const real = props.use12Hours
    ? h === 12
      ? hour.value >= 12
        ? 12
        : 0
      : hour.value >= 12
        ? h + 12
        : h
    : h
  hour.value = real
  commit(real, minute.value, second.value)
}
function setM(m: number) {
  if (disabledMinuteSet.value.has(m)) return
  minute.value = m
  commit(hour.value, m, second.value)
}
function setS(s: number) {
  if (disabledSecondSet.value.has(s)) return
  second.value = s
  commit(hour.value, minute.value, s)
}

function handleNow() {
  const now = new Date()
  hour.value = now.getHours()
  minute.value = now.getMinutes()
  second.value = now.getSeconds()
  commit(hour.value, minute.value, second.value)
  setOpen(false)
}

function handleClear(e: MouseEvent) {
  e.stopPropagation()
  internal.value = ''
  emit('update:modelValue', '')
  emit('change', '')
}

function openDropdown() {
  if (props.disabled || props.loading) return
  setOpen(true)
}

function handleOutside(e: MouseEvent) {
  if (!isOpen.value) return
  if (wrapperRef.value && !wrapperRef.value.contains(e.target as Node)) {
    setOpen(false)
  }
}

function handleEscape(e: KeyboardEvent) {
  if (!isOpen.value) return
  if (e.key === 'Escape') setOpen(false)
}

onMounted(() => {
  document.addEventListener('mousedown', handleOutside)
  document.addEventListener('keydown', handleEscape)
})

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleOutside)
  document.removeEventListener('keydown', handleEscape)
})

function scrollActive(col: HTMLElement | null) {
  if (!col) return
  const active = col.querySelector('[data-active="true"]') as HTMLElement | null
  active?.scrollIntoView?.({ block: 'nearest' })
}

watch([isOpen, hour, minute, second], async () => {
  if (!isOpen.value) return
  await nextTick()
  scrollActive(hourColRef.value)
  scrollActive(minuteColRef.value)
  scrollActive(secondColRef.value)
})

const wrapperCls = computed(() =>
  props.unstyled
    ? ''
    : [
        'sg-timepicker',
        `sg-timepicker-${props.size}`,
        isOpen.value ? 'sg-timepicker-open' : '',
        props.disabled || props.loading ? 'sg-timepicker-disabled' : '',
        props.loading ? 'sg-timepicker-loading' : '',
      ]
        .filter(Boolean)
        .join(' '),
)

function setAm() {
  if (hour.value >= 12) {
    const h = hour.value - 12
    hour.value = h
    commit(h, minute.value, second.value)
  }
}
function setPm() {
  if (hour.value < 12) {
    const h = hour.value + 12
    hour.value = h
    commit(h, minute.value, second.value)
  }
}
</script>

<template>
  <div ref="wrapperRef" :class="wrapperCls">
    <div
      class="sg-timepicker-input"
      role="combobox"
      aria-haspopup="dialog"
      :aria-expanded="isOpen"
      :aria-disabled="disabled"
      :aria-label="ariaLabel"
      :aria-labelledby="ariaLabelledby"
      @click="openDropdown"
    >
      <span :class="current ? '' : 'sg-timepicker-placeholder'">{{ current || placeholder }}</span>
      <span class="sg-timepicker-suffix">
        <span v-if="loading && !unstyled" class="sg-spin sg-spin-small" aria-hidden="true" />
        <template v-else>
          <span
            v-if="allowClear && current"
            class="sg-timepicker-clear"
            role="button"
            :aria-label="clearLabel"
            @click="handleClear"
            >×</span
          >
          <svg
            class="sg-timepicker-icon"
            viewBox="0 0 16 16"
            width="14"
            height="14"
            fill="currentColor"
            aria-hidden="true"
          >
            <path
              d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm0 14.5A6.5 6.5 0 1 1 8 1.5a6.5 6.5 0 0 1 0 13zM8.5 4H7v5l4.25 2.5.75-1.23L8.5 8.25V4z"
            />
          </svg>
        </template>
      </span>
    </div>
    <div v-if="isOpen" class="sg-tp-dropdown">
      <div class="sg-tp-columns">
        <div ref="hourColRef" class="sg-tp-col">
          <div
            v-for="n in hours"
            :key="n"
            :data-active="n === displayHour"
            :data-disabled="disabledHourSet.has(n)"
            :class="[
              'sg-tp-cell',
              n === displayHour ? 'sg-tp-cell-active' : '',
              disabledHourSet.has(n) ? 'sg-tp-cell-disabled' : '',
            ]"
            :aria-disabled="disabledHourSet.has(n)"
            @click="setH(n)"
          >
            {{ pad(n) }}
          </div>
        </div>
        <div ref="minuteColRef" class="sg-tp-col">
          <div
            v-for="n in minutes"
            :key="n"
            :data-active="n === minute"
            :data-disabled="disabledMinuteSet.has(n)"
            :class="[
              'sg-tp-cell',
              n === minute ? 'sg-tp-cell-active' : '',
              disabledMinuteSet.has(n) ? 'sg-tp-cell-disabled' : '',
            ]"
            :aria-disabled="disabledMinuteSet.has(n)"
            @click="setM(n)"
          >
            {{ pad(n) }}
          </div>
        </div>
        <div v-if="showSecond" ref="secondColRef" class="sg-tp-col">
          <div
            v-for="n in seconds"
            :key="n"
            :data-active="n === second"
            :data-disabled="disabledSecondSet.has(n)"
            :class="[
              'sg-tp-cell',
              n === second ? 'sg-tp-cell-active' : '',
              disabledSecondSet.has(n) ? 'sg-tp-cell-disabled' : '',
            ]"
            :aria-disabled="disabledSecondSet.has(n)"
            @click="setS(n)"
          >
            {{ pad(n) }}
          </div>
        </div>
        <div v-if="use12Hours" class="sg-tp-col sg-tp-col-ampm">
          <div :class="['sg-tp-cell', hour < 12 ? 'sg-tp-cell-active' : '']" @click="setAm">AM</div>
          <div :class="['sg-tp-cell', hour >= 12 ? 'sg-tp-cell-active' : '']" @click="setPm">
            PM
          </div>
        </div>
      </div>
      <div v-if="showNow" class="sg-tp-footer">
        <button type="button" class="sg-tp-now-btn" @click="handleNow">{{ nowLabel }}</button>
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/ui/TimePicker.tsx
import React, { useState, useRef, useEffect, useMemo, useCallback } from 'react'
import { Spin } from './Spin'
import { useConfig } from '../ConfigProvider'
import type { BaseComponentProps, InteractiveProps, SizableProps } from '../../types'

// ── Helpers ──

function pad(n: number): string {
  return String(n).padStart(2, '0')
}

function formatTime(h: number, m: number, s: number, fmt: string, use12h: boolean): string {
  if (use12h) {
    const period = h >= 12 ? 'PM' : 'AM'
    const h12 = h % 12 || 12
    return fmt
      .replace('hh', pad(h12))
      .replace('mm', pad(m))
      .replace('ss', pad(s))
      .replace('A', period)
  }
  return fmt.replace('HH', pad(h)).replace('mm', pad(m)).replace('ss', pad(s))
}

function parseTime(str: string): { h: number; m: number; s: number } | null {
  if (!str) return null
  const upper = str.toUpperCase()
  const isPM = upper.includes('PM')
  const cleaned = upper.replace(/(AM|PM)/g, '').trim()
  const parts = cleaned.split(':').map(Number)
  if (parts.some(isNaN)) return null

  let h = parts[0] ?? 0
  const m = parts[1] ?? 0
  const s = parts[2] ?? 0

  if (isPM && h < 12) h += 12
  if (!isPM && upper.includes('AM') && h === 12) h = 0

  return { h, m, s }
}

// ── ScrollColumn ──

function ScrollColumn({
  items,
  value,
  disabledItems,
  onChange,
  unstyled,
}: {
  items: number[]
  value: number
  disabledItems?: Set<number>
  onChange: (v: number) => void
  unstyled?: boolean
}) {
  const colRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const el = colRef.current
    if (!el) return
    const active = el.querySelector('[data-active="true"]') as HTMLElement | null
    if (active?.scrollIntoView) {
      active.scrollIntoView({ block: 'nearest', behavior: 'smooth' })
    }
  }, [value])

  return (
    <div ref={colRef} className={unstyled ? '' : 'sg-tp-col'}>
      {items.map((n) => {
        const isDisabled = disabledItems?.has(n) ?? false
        const isActive = n === value
        const cls = unstyled
          ? ''
          : [
              'sg-tp-cell',
              isActive ? 'sg-tp-cell-active' : '',
              isDisabled ? 'sg-tp-cell-disabled' : '',
            ]
              .filter(Boolean)
              .join(' ')
        return (
          <div
            key={n}
            data-active={isActive}
            className={cls}
            onClick={() => !isDisabled && onChange(n)}
          >
            {pad(n)}
          </div>
        )
      })}
    </div>
  )
}

// ── Types ──

/** Props for a single time value picked via scroll columns and optional Now/Clear. */
export interface TimePickerProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Controlled time string matching the active format. */
  value?: string
  /** Initial time when uncontrolled. */
  defaultValue?: string
  /** Placeholder when the value is empty. */
  placeholder?: string
  /** Display format (HH/hh, mm, ss, A for 12h). */
  format?: string
  /** When true, use 12-hour clock with AM/PM column. */
  use12Hours?: boolean
  /** Step between hour values in the scroller. */
  hourStep?: number
  /** Step between minute values in the scroller. */
  minuteStep?: number
  /** Step between second values in the scroller. */
  secondStep?: number
  /** When true, show the seconds column. */
  showSecond?: boolean
  /** When true, show a Now button that sets current time and closes. */
  showNow?: boolean
  /** When true, show a clear control when a value exists. */
  allowClear?: boolean
  /** Hour values to disable in the hour column. */
  disabledHours?: () => number[]
  /** Minute values to disable for the given hour. */
  disabledMinutes?: (hour: number) => number[]
  /** Second values to disable for the given hour and minute. */
  disabledSeconds?: (hour: number, minute: number) => number[]
  /** Called when the time string changes. */
  onChange?: (timeString: string) => void
  /** Called when the dropdown opens or closes. */
  onOpenChange?: (open: boolean) => void
  /** Controlled visibility of the dropdown. */
  open?: boolean
  /** Reserved for read-only input behavior (currently unused in markup). */
  inputReadOnly?: boolean
  /**
   * Accessible name for the `role="combobox"` trigger. Wrapping the styled
   * trigger in a `<label>` does not associate (the trigger is not a form
   * element), so `aria-label` / `aria-labelledby` is the supported way to
   * give the control a name. Required for axe `aria-input-field-name`.
   */
  'aria-label'?: string
  /** Id(s) of the element(s) that label the trigger. Mirrors `aria-label`. */
  'aria-labelledby'?: string
}

/** Props for two side-by-side TimePicker panels as a start/end range. */
export interface TimeRangePickerProps extends BaseComponentProps, InteractiveProps, SizableProps {
  /** Controlled start and end time strings. */
  value?: [string, string]
  /** Initial range when uncontrolled. */
  defaultValue?: [string, string]
  /** Placeholders for start and end fields. */
  placeholder?: [string, string]
  /** Shared display format for both pickers. */
  format?: string
  /** When true, both panels use 12-hour mode. */
  use12Hours?: boolean
  /** Shared hour step for both panels. */
  hourStep?: number
  /** Shared minute step for both panels. */
  minuteStep?: number
  /** Shared second step for both panels. */
  secondStep?: number
  /** When true, show seconds on both panels. */
  showSecond?: boolean
  /** When true, show a clear control when either side has a value. */
  allowClear?: boolean
  /** Node between start and end labels. */
  separator?: React.ReactNode
  /** Called when either start or end time changes. */
  onChange?: (timeStrings: [string, string]) => void
  /** Called when the combined dropdown opens or closes. */
  onOpenChange?: (open: boolean) => void
  /** Controlled visibility of the range dropdown. */
  open?: boolean
}

// ═══════════════════════════════════════════════════════
// TimePicker
// ═══════════════════════════════════════════════════════

/**
 * Scroll-column time picker with optional 12h mode, disabled slots, and Now/Clear.
 * Value is a formatted string; format defaults from use12Hours and showSecond.
 *
 * @default placeholder - `'Select time'`
 * @default use12Hours - `false`
 * @default hourStep - `1`
 * @default minuteStep - `1`
 * @default secondStep - `1`
 * @default showSecond - `true`
 * @default showNow - `true`
 * @default allowClear - `true`
 * @default inputReadOnly - `false`
 */
export function TimePicker({
  value,
  defaultValue,
  placeholder = 'Select time',
  format: formatProp,
  use12Hours = false,
  hourStep = 1,
  minuteStep = 1,
  secondStep = 1,
  showSecond = true,
  showNow = true,
  allowClear = true,
  disabledHours,
  disabledMinutes,
  disabledSeconds,
  disabled: disabledProp,
  loading,
  size: sizeProp,
  onChange,
  onOpenChange,
  open: openProp,
  inputReadOnly: _inputReadOnly = false,
  className,
  style,
  unstyled,
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledBy,
}: TimePickerProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const disabled = disabledProp ?? config.disabled ?? false
  const nowLabel = config.locale?.calendar?.now ?? 'Now'
  const clearLabel = config.locale?.input?.clear ?? 'Clear'

  const fmt = formatProp ?? (use12Hours ? 'hh:mm:ss A' : showSecond ? 'HH:mm:ss' : 'HH:mm')

  const [internalValue, setInternalValue] = useState(value ?? defaultValue ?? '')
  const [internalOpen, setInternalOpen] = useState(false)
  const currentValue = value !== undefined ? value : internalValue
  const isOpen = openProp ?? internalOpen

  const parsed = useMemo(() => parseTime(currentValue), [currentValue])
  const [hour, setHour] = useState(parsed?.h ?? 0)
  const [minute, setMinute] = useState(parsed?.m ?? 0)
  const [second, setSecond] = useState(parsed?.s ?? 0)

  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handle = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setInternalOpen(false)
        onOpenChange?.(false)
      }
    }
    document.addEventListener('mousedown', handle)
    return () => document.removeEventListener('mousedown', handle)
  }, [onOpenChange])

  useEffect(() => {
    const p = parseTime(currentValue)
    if (p) {
      setHour(p.h)
      setMinute(p.m)
      setSecond(p.s)
    }
  }, [currentValue])

  const hours = useMemo(() => {
    const arr: number[] = []
    if (use12Hours) {
      for (let i = 1; i <= 12; i += hourStep) arr.push(i)
    } else {
      for (let i = 0; i < 24; i += hourStep) arr.push(i)
    }
    return arr
  }, [hourStep, use12Hours])

  const minutes = useMemo(() => {
    const arr: number[] = []
    for (let i = 0; i < 60; i += minuteStep) arr.push(i)
    return arr
  }, [minuteStep])

  const seconds = useMemo(() => {
    const arr: number[] = []
    for (let i = 0; i < 60; i += secondStep) arr.push(i)
    return arr
  }, [secondStep])

  const disHours = useMemo(() => new Set(disabledHours?.() ?? []), [disabledHours])
  const disMinutes = useMemo(() => new Set(disabledMinutes?.(hour) ?? []), [disabledMinutes, hour])
  const disSecs = useMemo(
    () => new Set(disabledSeconds?.(hour, minute) ?? []),
    [disabledSeconds, hour, minute],
  )

  const commitTime = useCallback(
    (h: number, m: number, s: number) => {
      const str = formatTime(h, m, s, fmt, use12Hours)
      setInternalValue(str)
      onChange?.(str)
    },
    [fmt, use12Hours, onChange],
  )

  const handleHourChange = (h: number) => {
    const realH = use12Hours ? (h === 12 ? (hour >= 12 ? 12 : 0) : hour >= 12 ? h + 12 : h) : h
    setHour(realH)
    commitTime(realH, minute, second)
  }

  const handleMinuteChange = (m: number) => {
    setMinute(m)
    commitTime(hour, m, second)
  }

  const handleSecondChange = (s: number) => {
    setSecond(s)
    commitTime(hour, minute, s)
  }

  const handleNow = () => {
    const now = new Date()
    const h = now.getHours(),
      m = now.getMinutes(),
      s = now.getSeconds()
    setHour(h)
    setMinute(m)
    setSecond(s)
    commitTime(h, m, s)
    setInternalOpen(false)
    onOpenChange?.(false)
  }

  const handleClear = (e: React.MouseEvent) => {
    e.stopPropagation()
    setInternalValue('')
    onChange?.('')
  }

  const openDropdown = () => {
    if (disabled || loading) return
    setInternalOpen(true)
    onOpenChange?.(true)
  }

  const displayHour = use12Hours ? hour % 12 || 12 : hour

  const wrapperCls = unstyled
    ? (className ?? '')
    : [
        'sg-timepicker',
        `sg-timepicker-${size}`,
        isOpen ? 'sg-timepicker-open' : '',
        disabled ? 'sg-timepicker-disabled' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')

  return (
    <div className={wrapperCls} ref={ref} style={style}>
      <div
        className={unstyled ? '' : 'sg-timepicker-input'}
        onClick={openDropdown}
        role="combobox"
        aria-haspopup="dialog"
        aria-expanded={isOpen}
        aria-disabled={disabled}
        aria-label={ariaLabel}
        aria-labelledby={ariaLabelledBy}
      >
        <span
          className={
            unstyled ? '' : currentValue ? 'sg-timepicker-value' : 'sg-timepicker-placeholder'
          }
        >
          {currentValue || placeholder}
        </span>
        <span className={unstyled ? '' : 'sg-timepicker-suffix'}>
          {loading ? (
            <Spin size="small" unstyled={unstyled} />
          ) : (
            <>
              {allowClear && currentValue && (
                <span
                  className={unstyled ? '' : 'sg-timepicker-clear'}
                  role="button"
                  aria-label={clearLabel}
                  onClick={handleClear}
                >
                  &times;
                </span>
              )}
              <svg
                className={unstyled ? '' : 'sg-timepicker-icon-svg'}
                viewBox="0 0 16 16"
                width="14"
                height="14"
                fill="currentColor"
              >
                <path d="M8 0a8 8 0 110 16A8 8 0 018 0zm0 1a7 7 0 100 14A7 7 0 008 1zm.5 3v4.5l3 1.5-.5 1-3.5-1.75V4h1z" />
              </svg>
            </>
          )}
        </span>
      </div>

      {isOpen && (
        <div className={unstyled ? '' : 'sg-tp-dropdown'}>
          <div className={unstyled ? '' : 'sg-tp-columns'}>
            <ScrollColumn
              items={hours}
              value={displayHour}
              disabledItems={disHours}
              onChange={handleHourChange}
              unstyled={unstyled}
            />
            <ScrollColumn
              items={minutes}
              value={minute}
              disabledItems={disMinutes}
              onChange={handleMinuteChange}
              unstyled={unstyled}
            />
            {showSecond && (
              <ScrollColumn
                items={seconds}
                value={second}
                disabledItems={disSecs}
                onChange={handleSecondChange}
                unstyled={unstyled}
              />
            )}
            {use12Hours && (
              <div className={unstyled ? '' : 'sg-tp-col sg-tp-col-ampm'}>
                <div
                  className={unstyled ? '' : `sg-tp-cell${hour < 12 ? ' sg-tp-cell-active' : ''}`}
                  onClick={() => {
                    if (hour >= 12) {
                      const h = hour - 12
                      setHour(h)
                      commitTime(h, minute, second)
                    }
                  }}
                >
                  AM
                </div>
                <div
                  className={unstyled ? '' : `sg-tp-cell${hour >= 12 ? ' sg-tp-cell-active' : ''}`}
                  onClick={() => {
                    if (hour < 12) {
                      const h = hour + 12
                      setHour(h)
                      commitTime(h, minute, second)
                    }
                  }}
                >
                  PM
                </div>
              </div>
            )}
          </div>
          {showNow && (
            <div className={unstyled ? '' : 'sg-tp-footer'}>
              <button className={unstyled ? '' : 'sg-tp-now-btn'} onClick={handleNow}>
                {nowLabel}
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// Attach TimeRangePicker for Ant-like API: TimePicker.RangePicker
/**
 * Range control hosting two TimePicker instances for independent start and end times.
 * Shares format, steps, and 12h setting; inner panels stay open while the range is open.
 *
 * @default placeholder - `['Start', 'End']`
 * @default use12Hours - `false`
 * @default hourStep - `1`
 * @default minuteStep - `1`
 * @default secondStep - `1`
 * @default showSecond - `true`
 * @default allowClear - `true`
 * @default separator - `'→'`
 */
export function TimeRangePicker({
  value,
  defaultValue,
  placeholder = ['Start', 'End'],
  format: formatProp,
  use12Hours = false,
  hourStep = 1,
  minuteStep = 1,
  secondStep = 1,
  showSecond = true,
  allowClear = true,
  separator = '→',
  disabled: disabledProp,
  loading,
  size: sizeProp,
  onChange,
  onOpenChange,
  open: openProp,
  className,
  style,
  unstyled,
}: TimeRangePickerProps) {
  const config = useConfig()
  const size = sizeProp ?? config.size ?? 'middle'
  const disabled = disabledProp ?? config.disabled ?? false
  const clearLabel = config.locale?.input?.clear ?? 'Clear'

  const fmt = formatProp ?? (use12Hours ? 'hh:mm:ss A' : showSecond ? 'HH:mm:ss' : 'HH:mm')

  const [internalValue, setInternalValue] = useState<[string, string]>(
    value ?? defaultValue ?? ['', ''],
  )
  const [internalOpen, setInternalOpen] = useState(false)
  const currentValue = value ?? internalValue
  const isOpen = openProp ?? internalOpen

  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handle = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setInternalOpen(false)
        onOpenChange?.(false)
      }
    }
    document.addEventListener('mousedown', handle)
    return () => document.removeEventListener('mousedown', handle)
  }, [onOpenChange])

  const handleStartChange = (v: string) => {
    const next: [string, string] = [v, currentValue[1]]
    setInternalValue(next)
    onChange?.(next)
  }

  const handleEndChange = (v: string) => {
    const next: [string, string] = [currentValue[0], v]
    setInternalValue(next)
    onChange?.(next)
  }

  const handleClear = (e: React.MouseEvent) => {
    e.stopPropagation()
    const next: [string, string] = ['', '']
    setInternalValue(next)
    onChange?.(next)
  }

  const openDropdown = () => {
    if (disabled || loading) return
    setInternalOpen(true)
    onOpenChange?.(true)
  }

  const wrapperCls = unstyled
    ? (className ?? '')
    : [
        'sg-timepicker',
        'sg-timepicker-range',
        `sg-timepicker-${size}`,
        isOpen ? 'sg-timepicker-open' : '',
        disabled ? 'sg-timepicker-disabled' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')

  return (
    <div className={wrapperCls} ref={ref} style={style}>
      <div
        className={unstyled ? '' : 'sg-timepicker-input sg-timepicker-range-input'}
        onClick={openDropdown}
      >
        <span>{currentValue[0] || placeholder[0]}</span>
        <span className={unstyled ? '' : 'sg-timepicker-separator'}>{separator}</span>
        <span>{currentValue[1] || placeholder[1]}</span>
        <span className={unstyled ? '' : 'sg-timepicker-suffix'}>
          {allowClear && (currentValue[0] || currentValue[1]) && (
            <span
              className={unstyled ? '' : 'sg-timepicker-clear'}
              role="button"
              aria-label={clearLabel}
              onClick={handleClear}
            >
              &times;
            </span>
          )}
        </span>
      </div>

      {isOpen && (
        <div className={unstyled ? '' : 'sg-tp-dropdown sg-tp-dropdown-range'}>
          <div className={unstyled ? '' : 'sg-tp-range-panels'}>
            <TimePicker
              value={currentValue[0]}
              onChange={handleStartChange}
              format={fmt}
              use12Hours={use12Hours}
              hourStep={hourStep}
              minuteStep={minuteStep}
              secondStep={secondStep}
              showSecond={showSecond}
              showNow={false}
              open={true}
              unstyled={unstyled}
            />
            <TimePicker
              value={currentValue[1]}
              onChange={handleEndChange}
              format={fmt}
              use12Hours={use12Hours}
              hourStep={hourStep}
              minuteStep={minuteStep}
              secondStep={secondStep}
              showSecond={showSecond}
              showNow={false}
              open={true}
              unstyled={unstyled}
            />
          </div>
        </div>
      )}
    </div>
  )
}

;(TimePicker as unknown as { RangePicker: typeof TimeRangePicker }).RangePicker = TimeRangePicker
