// packages/react/src/components/complex/SchemaFormEditor/SchemaFormEditorSchemaView.tsx
import { useMemo } from 'react'
import type { CSSProperties } from 'react'
import { editorSchemaToJsonSchema } from './adapters/jsonSchema'
import type { SchemaEditorStore } from './useSchemaEditor'
import { useConfig } from '../../ConfigProvider'

export interface SchemaFormEditorSchemaViewProps {
  store: SchemaEditorStore
  className?: string
  style?: CSSProperties
  /** Output mode — formatted JSON or a TypeScript-friendly literal. */
  mode?: 'json' | 'ts'
}

export function SchemaFormEditorSchemaView({
  store,
  className,
  style,
  mode = 'json',
}: SchemaFormEditorSchemaViewProps) {
  const sfeLocale = useConfig().locale?.schemaFormEditor
  const text = useMemo(() => {
    const schema = editorSchemaToJsonSchema(store.state.schema)
    if (mode === 'ts') return `const schema = ${JSON.stringify(schema, null, 2)} as const`
    return JSON.stringify(schema, null, 2)
  }, [store.state.schema, mode])

  return (
    <pre
      className={['sg-sfe-schema-view', className].filter(Boolean).join(' ')}
      style={style}
      data-testid="sfe-schema-view"
      aria-label={sfeLocale?.schemaView ?? 'Generated JSON Schema'}
    >
      <code>{text}</code>
    </pre>
  )
}

// packages/vue/src/components/complex/SchemaFormEditor/SchemaFormEditorSchemaView.vue
<script setup lang="ts">
import { computed } from 'vue'
import { editorSchemaToJsonSchema } from './adapters/jsonSchema'
import { useConfig } from '../../ui/ConfigProvider.vue'
import type { SchemaEditorStore } from './useSchemaEditor'

export interface SchemaFormEditorSchemaViewProps {
  store: SchemaEditorStore
  mode?: 'json' | 'ts'
}

const props = withDefaults(defineProps<SchemaFormEditorSchemaViewProps>(), {
  mode: 'json',
})

const text = computed(() => {
  const schema = editorSchemaToJsonSchema(props.store.state.value.schema)
  if (props.mode === 'ts') return `const schema = ${JSON.stringify(schema, null, 2)} as const`
  return JSON.stringify(schema, null, 2)
})

const cfg = useConfig()
const schemaViewLabel = computed(
  () => cfg.value.locale?.schemaFormEditor?.schemaView ?? 'Generated JSON Schema',
)
</script>

<template>
  <pre
    class="sg-sfe-schema-view"
    data-testid="sfe-schema-view"
    :aria-label="schemaViewLabel"
  ><code>{{ text }}</code></pre>
</template>
