// packages/react/src/components/complex/SchemaFormEditor/SchemaFormEditor.tsx
import { useEffect, useMemo, useState } from 'react'
import type { CSSProperties } from 'react'
import { useSchemaEditor } from './useSchemaEditor'
import type { SchemaEditorStore, UseSchemaEditorOptions } from './useSchemaEditor'
import { SchemaFormEditorPalette } from './SchemaFormEditorPalette'
import type { PaletteItem } from './SchemaFormEditorPalette'
import { SchemaFormEditorCanvas } from './SchemaFormEditorCanvas'
import { SchemaFormEditorInspector } from './SchemaFormEditorInspector'
import { SchemaFormEditorSchemaView } from './SchemaFormEditorSchemaView'
import { createFieldFromPaletteType, editorSchemaToJsonSchema } from './adapters/jsonSchema'
import { SchemaForm } from '../SchemaForm'
import type { EditorSchema } from './types'
import { useConfig } from '../../ConfigProvider'

export interface SchemaFormEditorProps {
  /** Initial schema (uncontrolled). Use `setSchema` from a custom store for controlled use. */
  initialSchema?: EditorSchema
  /**
   * Externally-managed editor store. When provided, `initialSchema`,
   * `onChange` are ignored and the consumer drives the editor directly.
   */
  store?: SchemaEditorStore
  /** Override the default palette catalogue. */
  paletteItems?: PaletteItem[]
  /** Fires after every successful mutation with the new schema. */
  onChange?: (schema: EditorSchema) => void
  /** Empty-state CTA. */
  emptyText?: string
  /** Wrapper className (additive). */
  className?: string
  /** Wrapper inline style. */
  style?: CSSProperties
  /** Hide the bottom Preview / Schema toggle. Default is to show it. */
  hideSchemaView?: boolean
}

export function SchemaFormEditor({
  initialSchema,
  store: externalStore,
  paletteItems,
  onChange,
  emptyText,
  className,
  style,
  hideSchemaView,
}: SchemaFormEditorProps) {
  const sfeLocale = useConfig().locale?.schemaFormEditor
  const internalOptions: UseSchemaEditorOptions = { initialSchema, onChange }
  const internalStore = useSchemaEditor(internalOptions)
  const store = externalStore ?? internalStore
  const [bottomTab, setBottomTab] = useState<'preview' | 'schema'>('preview')

  // Allow Ctrl/Cmd + Z / Shift+Z keyboard shortcuts when the editor has focus.
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      const target = e.target as HTMLElement | null
      if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA')) return
      const ctrl = e.ctrlKey || e.metaKey
      if (!ctrl) return
      const k = e.key.toLowerCase()
      if (k === 'z' && !e.shiftKey) {
        e.preventDefault()
        store.undo()
      } else if ((k === 'z' && e.shiftKey) || k === 'y') {
        e.preventDefault()
        store.redo()
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [store])

  return (
    <div
      className={['sg-sfe', className].filter(Boolean).join(' ')}
      style={style}
      data-testid="schema-form-editor"
    >
      <div className="sg-sfe-toolbar" data-testid="sfe-toolbar">
        <span className="sg-sfe-toolbar-title">Schema Form Editor</span>
        <span style={{ flex: 1 }} />
        <button
          type="button"
          className="sg-sfe-toolbar-btn"
          data-testid="sfe-undo"
          aria-label={sfeLocale?.undo ?? 'Undo'}
          disabled={!store.state.canUndo}
          onClick={() => store.undo()}
        >
          Undo
        </button>
        <button
          type="button"
          className="sg-sfe-toolbar-btn"
          data-testid="sfe-redo"
          aria-label={sfeLocale?.redo ?? 'Redo'}
          disabled={!store.state.canRedo}
          onClick={() => store.redo()}
        >
          Redo
        </button>
      </div>

      <div className="sg-sfe-body">
        <SchemaFormEditorPalette
          items={paletteItems}
          onItemActivate={(type) => {
            const existingNames = store.state.schema.fields.map((f) => f.name)
            store.addField(createFieldFromPaletteType(type, existingNames))
          }}
        />
        <div className="sg-sfe-center">
          <SchemaFormEditorCanvas store={store} emptyText={emptyText} />
          {!hideSchemaView && (
            <div className="sg-sfe-bottom" data-testid="sfe-bottom">
              <div className="sg-sfe-tabs">
                <button
                  type="button"
                  className={['sg-sfe-tab', bottomTab === 'preview' ? 'sg-sfe-tab-active' : '']
                    .filter(Boolean)
                    .join(' ')}
                  data-testid="sfe-tab-preview"
                  onClick={() => setBottomTab('preview')}
                >
                  Preview
                </button>
                <button
                  type="button"
                  className={['sg-sfe-tab', bottomTab === 'schema' ? 'sg-sfe-tab-active' : '']
                    .filter(Boolean)
                    .join(' ')}
                  data-testid="sfe-tab-schema"
                  onClick={() => setBottomTab('schema')}
                >
                  Schema
                </button>
              </div>
              {bottomTab === 'preview' ? (
                <PreviewPane store={store} />
              ) : (
                <SchemaFormEditorSchemaView store={store} />
              )}
            </div>
          )}
        </div>
        <SchemaFormEditorInspector store={store} />
      </div>
    </div>
  )
}

function PreviewPane({ store }: { store: SchemaEditorStore }) {
  const fields = store.state.schema.fields
  const jsonSchema = useMemo(
    () => editorSchemaToJsonSchema(store.state.schema),
    [store.state.schema],
  )
  // Re-key the form when the schema fingerprint changes so defaults are picked
  // up after every mutation in the editor.
  const formKey = useMemo(
    () => fields.map((f) => `${f.id}:${f.name}:${f.type}`).join('|'),
    [fields],
  )

  if (fields.length === 0) {
    return (
      <div className="sg-sfe-preview-empty" data-testid="sfe-preview-empty">
        Drop fields onto the canvas to see a live preview.
      </div>
    )
  }

  return (
    <div className="sg-sfe-preview" data-testid="sfe-preview">
      <SchemaForm key={formKey} schema={jsonSchema} layout="vertical">
        <span />
      </SchemaForm>
    </div>
  )
}

// packages/vue/src/components/complex/SchemaFormEditor/SchemaFormEditor.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import SgSchemaForm from '../SchemaForm/SchemaForm.vue'
import SgSchemaFormEditorPalette from './SchemaFormEditorPalette.vue'
import SgSchemaFormEditorCanvas from './SchemaFormEditorCanvas.vue'
import SgSchemaFormEditorInspector from './SchemaFormEditorInspector.vue'
import SgSchemaFormEditorSchemaView from './SchemaFormEditorSchemaView.vue'
import { useSchemaEditor, type SchemaEditorStore } from './useSchemaEditor'
import { editorSchemaToJsonSchema, createFieldFromPaletteType } from './adapters/jsonSchema'
import { useConfig } from '../../ui/ConfigProvider.vue'
import type { PaletteItem } from './palette'
import type { EditorSchema } from './types'

export interface SchemaFormEditorProps {
  initialSchema?: EditorSchema
  store?: SchemaEditorStore
  paletteItems?: PaletteItem[]
  emptyText?: string
  hideSchemaView?: boolean
}

const props = defineProps<SchemaFormEditorProps>()

const emit = defineEmits<{
  (e: 'change', schema: EditorSchema): void
}>()

const internalStore = useSchemaEditor({
  initialSchema: props.initialSchema,
  onChange: (schema) => emit('change', schema),
})
const store = computed(() => props.store ?? internalStore)

const bottomTab = ref<'preview' | 'schema'>('preview')

const cfg = useConfig()
const undoLabel = computed(() => cfg.value.locale?.schemaFormEditor?.undo ?? 'Undo')
const redoLabel = computed(() => cfg.value.locale?.schemaFormEditor?.redo ?? 'Redo')

function handlePaletteActivate(type: ReturnType<typeof createFieldFromPaletteType>['type']) {
  const existingNames = store.value.state.value.schema.fields.map((f) => f.name)
  store.value.addField(createFieldFromPaletteType(type, existingNames))
}

function onKey(e: KeyboardEvent) {
  const target = e.target as HTMLElement | null
  if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA')) return
  const ctrl = e.ctrlKey || e.metaKey
  if (!ctrl) return
  const k = e.key.toLowerCase()
  if (k === 'z' && !e.shiftKey) {
    e.preventDefault()
    store.value.undo()
  } else if ((k === 'z' && e.shiftKey) || k === 'y') {
    e.preventDefault()
    store.value.redo()
  }
}

onMounted(() => window.addEventListener('keydown', onKey))
onBeforeUnmount(() => window.removeEventListener('keydown', onKey))

const previewSchema = computed(() => editorSchemaToJsonSchema(store.value.state.value.schema))
const previewFields = computed(() => store.value.state.value.schema.fields)
const previewKey = computed(() =>
  previewFields.value.map((f) => `${f.id}:${f.name}:${f.type}`).join('|'),
)
</script>

<template>
  <div class="sg-sfe" data-testid="schema-form-editor">
    <div class="sg-sfe-toolbar" data-testid="sfe-toolbar">
      <span class="sg-sfe-toolbar-title">Schema Form Editor</span>
      <span style="flex: 1" />
      <button
        type="button"
        class="sg-sfe-toolbar-btn"
        data-testid="sfe-undo"
        :aria-label="undoLabel"
        :disabled="!store.state.value.canUndo"
        @click="store.undo()"
      >
        {{ undoLabel }}
      </button>
      <button
        type="button"
        class="sg-sfe-toolbar-btn"
        data-testid="sfe-redo"
        :aria-label="redoLabel"
        :disabled="!store.state.value.canRedo"
        @click="store.redo()"
      >
        {{ redoLabel }}
      </button>
    </div>

    <div class="sg-sfe-body">
      <SgSchemaFormEditorPalette :items="paletteItems" @item-activate="handlePaletteActivate" />
      <div class="sg-sfe-center">
        <SgSchemaFormEditorCanvas :store="store" :empty-text="emptyText" />
        <div v-if="!hideSchemaView" class="sg-sfe-bottom" data-testid="sfe-bottom">
          <div class="sg-sfe-tabs">
            <button
              type="button"
              :class="['sg-sfe-tab', bottomTab === 'preview' ? 'sg-sfe-tab-active' : '']"
              data-testid="sfe-tab-preview"
              @click="bottomTab = 'preview'"
            >
              Preview
            </button>
            <button
              type="button"
              :class="['sg-sfe-tab', bottomTab === 'schema' ? 'sg-sfe-tab-active' : '']"
              data-testid="sfe-tab-schema"
              @click="bottomTab = 'schema'"
            >
              Schema
            </button>
          </div>
          <template v-if="bottomTab === 'preview'">
            <div
              v-if="previewFields.length === 0"
              class="sg-sfe-preview-empty"
              data-testid="sfe-preview-empty"
            >
              Drop fields onto the canvas to see a live preview.
            </div>
            <div v-else class="sg-sfe-preview" data-testid="sfe-preview">
              <SgSchemaForm :key="previewKey" :schema="previewSchema" layout="vertical">
                <span />
              </SgSchemaForm>
            </div>
          </template>
          <SgSchemaFormEditorSchemaView v-else :store="store" />
        </div>
      </div>
      <SgSchemaFormEditorInspector :store="store" />
    </div>
  </div>
</template>
