// packages/react/src/components/complex/List/List.tsx
import React from 'react'
import { Spin } from '../../ui/Spin'
import { Pagination } from '../../ui/Pagination'
import { Empty } from '../../ui/Empty'
import type { ListProps, ListItemProps, ListItemMetaProps } from './types'

function cls(...parts: (string | false | undefined | null)[]): string {
  return parts.filter(Boolean).join(' ')
}

function ListItemMeta({ avatar, title, description }: ListItemMetaProps) {
  return (
    <div className="sg-list-item-meta">
      {avatar && <div className="sg-list-item-meta-avatar">{avatar}</div>}
      <div className="sg-list-item-meta-content">
        {title && <h4 className="sg-list-item-meta-title">{title}</h4>}
        {description && <div className="sg-list-item-meta-description">{description}</div>}
      </div>
    </div>
  )
}

function ListItemComponent({ children, actions, extra, className, style }: ListItemProps) {
  return (
    <div className={cls('sg-list-item', className)} style={style}>
      <div className="sg-list-item-main">
        <div className="sg-list-item-content">{children}</div>
        {actions && actions.length > 0 && (
          <ul className="sg-list-item-actions">
            {actions.map((action, i) => (
              <li key={i} className="sg-list-item-action">
                {action}
              </li>
            ))}
          </ul>
        )}
      </div>
      {extra && <div className="sg-list-item-extra">{extra}</div>}
    </div>
  )
}

type ListItemType = typeof ListItemComponent & { Meta: typeof ListItemMeta }

const Item = ListItemComponent as ListItemType
Item.Meta = ListItemMeta

function ListInner<T = any>({
  dataSource,
  renderItem,
  header,
  footer,
  loading = false,
  loadMore,
  pagination,
  grid,
  size = 'default',
  split = true,
  bordered = false,
  locale,
  className,
  style,
  unstyled,
  virtual,
  selectable,
  selectedKeys: controlledSelectedKeys,
  defaultSelectedKeys,
  onSelectionChange,
  multiSelect = false,
  draggable,
  onReorder,
  hoverable = true,
  onItemClick,
  rowClassName,
  classNames: slotCls,
  styles: slotSty,
}: ListProps<T>) {
  const sCls = slotCls ?? {}
  const sSty = slotSty ?? {}
  const [internalPage, setInternalPage] = React.useState(1)
  const [internalSelectedKeys, setInternalSelectedKeys] = React.useState<number[]>(
    () => defaultSelectedKeys ?? [],
  )
  const [dragIndex, setDragIndex] = React.useState<number | null>(null)
  const [dropIndex, setDropIndex] = React.useState<number | null>(null)
  const [scrollTop, setScrollTop] = React.useState(0)
  const virtualRef = React.useRef<HTMLDivElement>(null)

  const selectedKeys = controlledSelectedKeys ?? internalSelectedKeys

  const pageSize = pagination ? (pagination.pageSize ?? 10) : dataSource.length
  const currentPage = pagination ? (pagination.current ?? internalPage) : 1
  const total = pagination ? (pagination.total ?? dataSource.length) : dataSource.length

  const paginatedData = React.useMemo(() => {
    if (!pagination) return dataSource
    const start = (currentPage - 1) * pageSize
    return dataSource.slice(start, start + pageSize)
  }, [dataSource, pagination, currentPage, pageSize])

  const handlePageChange = (page: number) => {
    setInternalPage(page)
    if (pagination) {
      pagination.onChange?.(page, pageSize)
    }
  }

  const handleItemClick = React.useCallback(
    (item: T, index: number, e: React.MouseEvent) => {
      onItemClick?.(item, index)

      if (!selectable) return

      let next: number[]
      if (multiSelect && (e.ctrlKey || e.metaKey)) {
        if (selectedKeys.includes(index)) {
          next = selectedKeys.filter((k) => k !== index)
        } else {
          next = [...selectedKeys, index]
        }
      } else {
        next = selectedKeys.includes(index) ? [] : [index]
      }

      setInternalSelectedKeys(next)
      onSelectionChange?.(
        next,
        next.map((k) => dataSource[k]),
      )
    },
    [selectable, multiSelect, selectedKeys, dataSource, onItemClick, onSelectionChange],
  )

  const handleDragStart = React.useCallback(
    (e: React.DragEvent, index: number) => {
      if (!draggable) return
      setDragIndex(index)
      e.dataTransfer.effectAllowed = 'move'
    },
    [draggable],
  )

  const handleDragOver = React.useCallback(
    (e: React.DragEvent, index: number) => {
      if (!draggable || dragIndex === null) return
      e.preventDefault()
      setDropIndex(index)
    },
    [draggable, dragIndex],
  )

  const handleDrop = React.useCallback(
    (e: React.DragEvent, index: number) => {
      e.preventDefault()
      if (dragIndex === null || dragIndex === index) {
        setDragIndex(null)
        setDropIndex(null)
        return
      }
      onReorder?.(dragIndex, index)
      setDragIndex(null)
      setDropIndex(null)
    },
    [dragIndex, onReorder],
  )

  const handleDragEnd = React.useCallback(() => {
    setDragIndex(null)
    setDropIndex(null)
  }, [])

  const handleVirtualScroll = React.useCallback(() => {
    if (virtualRef.current) {
      setScrollTop(virtualRef.current.scrollTop)
    }
  }, [])

  const emptyText = locale?.emptyText ?? 'No Data'

  const gridStyle = React.useMemo((): React.CSSProperties | undefined => {
    if (!grid) return undefined
    const cols = grid.column ?? 1
    // Базовое значение кладём в отдельную переменную, чтобы media-override на
    // корне (`--sg-list-grid-columns`) мог перебить её через наследование CSS-переменных
    // и не пришлось использовать `!important`.
    return {
      ['--sg-list-grid-base-columns' as string]: `repeat(${cols}, 1fr)`,
      gap: grid.gutter ? `${grid.gutter}px` : undefined,
    } as React.CSSProperties
  }, [grid])

  const gridResponsiveClass = React.useMemo(() => {
    if (!grid) return ''
    const parts: string[] = []
    if (grid.xs) parts.push(`sg-list-grid-xs-${grid.xs}`)
    if (grid.sm) parts.push(`sg-list-grid-sm-${grid.sm}`)
    if (grid.md) parts.push(`sg-list-grid-md-${grid.md}`)
    if (grid.lg) parts.push(`sg-list-grid-lg-${grid.lg}`)
    return parts.join(' ')
  }, [grid])

  const renderItemWrapper = React.useCallback(
    (item: T, index: number, extraStyle?: React.CSSProperties) => {
      const isSelected = selectable && selectedKeys.includes(index)
      const isDragging = dragIndex === index
      const isDropTarget = dropIndex === index && dragIndex !== index
      const extraCls =
        typeof rowClassName === 'function' ? rowClassName(item, index) : (rowClassName ?? '')

      const itemCls = cls(
        'sg-list-item',
        selectable && 'sg-list-item-selectable',
        isSelected && 'sg-list-item-selected',
        hoverable && 'sg-list-item-hoverable',
        isDragging && 'sg-list-item-dragging',
        isDropTarget && 'sg-list-item-drop-target',
        sCls.item,
        extraCls,
      )

      return (
        <div
          key={index}
          className={itemCls || undefined}
          style={extraStyle ? { ...sSty.item, ...extraStyle } : sSty.item}
          onClick={(e) => handleItemClick(item, index, e)}
          draggable={draggable}
          onDragStart={(e) => handleDragStart(e, index)}
          onDragOver={(e) => handleDragOver(e, index)}
          onDrop={(e) => handleDrop(e, index)}
          onDragEnd={handleDragEnd}
          onDragLeave={() => setDropIndex(null)}
        >
          {draggable && <span className="sg-list-drag-handle">⠿</span>}
          {renderItem(item, index)}
        </div>
      )
    },
    [
      selectable,
      selectedKeys,
      hoverable,
      dragIndex,
      dropIndex,
      draggable,
      rowClassName,
      handleItemClick,
      handleDragStart,
      handleDragOver,
      handleDrop,
      handleDragEnd,
      renderItem,
      sCls.item,
      sSty.item,
    ],
  )

  /**
   * Virtual scroll rendering.
   *
   * Каждая видимая строка позиционируется абсолютно на своём `top = index * itemHeight`
   * с фиксированной высотой `itemHeight`. Это даёт стабильную верстку независимо
   * от внутренних паддингов `.sg-list-item` и от того, оборачивает ли пользователь
   * содержимое в `<List.Item>` или возвращает голый `<div>`.
   *
   * Старый рендер (поток items внутри одного `position: absolute` блока) ломался,
   * когда фактическая высота строки не совпадала с `itemHeight` — overscan вылезал
   * за scroll-область, scroll-позиция не сходилась.
   */
  const renderVirtualList = React.useCallback(() => {
    if (!virtual) return null
    const { itemHeight, height, overscan = 5 } = virtual
    const totalHeight = paginatedData.length * itemHeight
    const startIndex = Math.max(0, Math.floor(scrollTop / itemHeight) - overscan)
    const visibleCount = Math.ceil(height / itemHeight) + overscan * 2
    const endIndex = Math.min(paginatedData.length, startIndex + visibleCount)

    return (
      <div
        ref={virtualRef}
        className="sg-list-virtual-container"
        style={{ height, overflow: 'auto', position: 'relative' }}
        onScroll={handleVirtualScroll}
      >
        <div style={{ height: totalHeight, position: 'relative' }}>
          {paginatedData.slice(startIndex, endIndex).map((item, i) => {
            const realIndex = startIndex + i
            return renderItemWrapper(item, realIndex, {
              position: 'absolute',
              top: realIndex * itemHeight,
              left: 0,
              right: 0,
              height: itemHeight,
              boxSizing: 'border-box',
              alignItems: 'center',
            })
          })}
        </div>
      </div>
    )
  }, [virtual, paginatedData, scrollTop, handleVirtualScroll, renderItemWrapper])

  if (unstyled) {
    return (
      <div className={className} style={style}>
        {header}
        {loading ? (
          <Spin unstyled />
        ) : paginatedData.length === 0 ? (
          <div>{emptyText}</div>
        ) : virtual ? (
          renderVirtualList()
        ) : (
          <div className={grid ? 'sg-list-items' : undefined} style={gridStyle}>
            {paginatedData.map((item, i) => renderItemWrapper(item, i))}
          </div>
        )}
        {loadMore}
        {pagination && (
          <Pagination
            unstyled
            current={currentPage}
            total={total}
            pageSize={pageSize}
            onChange={handlePageChange}
          />
        )}
        {footer}
      </div>
    )
  }

  const wrapperClass = cls(
    'sg-list',
    `sg-list-${size}`,
    split && 'sg-list-split',
    bordered && 'sg-list-bordered',
    loading && 'sg-list-loading',
    grid && 'sg-list-grid',
    selectable && 'sg-list-selectable',
    draggable && 'sg-list-draggable',
    virtual && 'sg-list-virtual',
    gridResponsiveClass,
    sCls.root,
    className,
  )

  return (
    <div className={wrapperClass} style={{ ...sSty.root, ...style }}>
      {header && (
        <div className={cls('sg-list-header', sCls.header)} style={sSty.header}>
          {header}
        </div>
      )}

      <Spin spinning={loading}>
        {paginatedData.length === 0 ? (
          <div className={cls('sg-list-empty', sCls.empty)} style={sSty.empty}>
            <Empty description={emptyText} />
          </div>
        ) : virtual ? (
          renderVirtualList()
        ) : (
          <div className={cls('sg-list-items', sCls.items)} style={{ ...gridStyle, ...sSty.items }}>
            {paginatedData.map((item, i) => renderItemWrapper(item, i))}
          </div>
        )}
      </Spin>

      {loadMore && <div className="sg-list-load-more">{loadMore}</div>}

      {pagination && (
        <div className={cls('sg-list-pagination', sCls.pagination)} style={sSty.pagination}>
          <Pagination
            current={currentPage}
            total={total}
            pageSize={pageSize}
            onChange={handlePageChange}
          />
        </div>
      )}

      {footer && (
        <div className={cls('sg-list-footer', sCls.footer)} style={sSty.footer}>
          {footer}
        </div>
      )}
    </div>
  )
}

type ListType = typeof ListInner & { Item: ListItemType }

/**
 * Renders a vertical or grid list with optional header, footer, pagination, loading,
 * virtual scroll, selection, and drag-and-drop reorder.
 * Use `List.Item` and `List.Item.Meta` for structured rows.
 */
export const List = ListInner as ListType
;(List as any).Item = Item

// packages/vue/src/components/complex/List/List.vue
<script setup lang="ts" generic="T">
import { computed, ref, useSlots } from 'vue'
import type { ListProps, ListClassNames, ListStyles } from './types'

const props = withDefaults(defineProps<ListProps<T>>(), {
  loading: false,
  pagination: false,
  size: 'default',
  split: true,
  bordered: false,
  unstyled: false,
  selectable: false,
  multiSelect: false,
  draggable: false,
  hoverable: true,
  defaultSelectedKeys: () => [],
})

const emit = defineEmits<{
  /** Fires when selection changes. */
  (e: 'selectionChange', keys: number[], items: T[]): void
  /** Fires after items are reordered via drag. */
  (e: 'reorder', fromIndex: number, toIndex: number): void
  /** Fires on row click. */
  (e: 'itemClick', item: T, index: number): void
  /** Fires when pagination changes. */
  (e: 'pageChange', page: number, pageSize: number): void
}>()

defineSlots<{
  default(props: { item: T; index: number }): unknown
  header(props: Record<string, never>): unknown
  footer(props: Record<string, never>): unknown
  loadMore(props: Record<string, never>): unknown
}>()

const slots = useSlots()

const sCls = computed<ListClassNames>(() => props.classNames ?? {})
const sSty = computed<ListStyles>(() => props.styles ?? {})

const internalPage = ref(1)
const internalSelectedKeys = ref<number[]>(props.defaultSelectedKeys ?? [])
const dragIndex = ref<number | null>(null)
const dropIndex = ref<number | null>(null)
const scrollTop = ref(0)
const virtualEl = ref<HTMLDivElement | null>(null)

const selectedKeys = computed<number[]>(() => props.selectedKeys ?? internalSelectedKeys.value)

const pageSize = computed(() =>
  props.pagination ? (props.pagination.pageSize ?? 10) : props.dataSource.length,
)
const currentPage = computed(() =>
  props.pagination ? (props.pagination.current ?? internalPage.value) : 1,
)
const total = computed(() =>
  props.pagination ? (props.pagination.total ?? props.dataSource.length) : props.dataSource.length,
)

const paginatedData = computed(() => {
  if (!props.pagination) return props.dataSource
  const start = (currentPage.value - 1) * pageSize.value
  return props.dataSource.slice(start, start + pageSize.value)
})

const pageCount = computed(() => Math.max(1, Math.ceil(total.value / pageSize.value)))

function changePage(page: number) {
  if (page < 1 || page > pageCount.value) return
  internalPage.value = page
  if (props.pagination) {
    props.pagination.onChange?.(page, pageSize.value)
  }
  emit('pageChange', page, pageSize.value)
}

function handleItemClick(item: T, index: number, e: MouseEvent) {
  emit('itemClick', item, index)
  if (!props.selectable) return

  let next: number[]
  if (props.multiSelect && (e.ctrlKey || e.metaKey)) {
    next = selectedKeys.value.includes(index)
      ? selectedKeys.value.filter((k) => k !== index)
      : [...selectedKeys.value, index]
  } else {
    next = selectedKeys.value.includes(index) ? [] : [index]
  }

  internalSelectedKeys.value = next
  emit(
    'selectionChange',
    next,
    next.map((k) => props.dataSource[k]),
  )
}

function handleDragStart(e: DragEvent, index: number) {
  if (!props.draggable) return
  dragIndex.value = index
  if (e.dataTransfer) e.dataTransfer.effectAllowed = 'move'
}

function handleDragOver(e: DragEvent, index: number) {
  if (!props.draggable || dragIndex.value === null) return
  e.preventDefault()
  dropIndex.value = index
}

function handleDrop(e: DragEvent, index: number) {
  e.preventDefault()
  if (dragIndex.value === null || dragIndex.value === index) {
    dragIndex.value = null
    dropIndex.value = null
    return
  }
  emit('reorder', dragIndex.value, index)
  dragIndex.value = null
  dropIndex.value = null
}

function handleDragEnd() {
  dragIndex.value = null
  dropIndex.value = null
}

function handleVirtualScroll() {
  if (virtualEl.value) {
    scrollTop.value = virtualEl.value.scrollTop
  }
}

const emptyText = computed(() => props.locale?.emptyText ?? 'No Data')

const gridStyle = computed<Record<string, string | number> | undefined>(() => {
  if (!props.grid) return undefined
  const cols = props.grid.column ?? 1
  const style: Record<string, string | number> = {
    '--sg-list-grid-base-columns': `repeat(${cols}, 1fr)`,
  }
  if (props.grid.gutter !== undefined) style.gap = `${props.grid.gutter}px`
  return style
})

const gridResponsiveClass = computed(() => {
  const grid = props.grid
  if (!grid) return ''
  const parts: string[] = []
  if (grid.xs) parts.push(`sg-list-grid-xs-${grid.xs}`)
  if (grid.sm) parts.push(`sg-list-grid-sm-${grid.sm}`)
  if (grid.md) parts.push(`sg-list-grid-md-${grid.md}`)
  if (grid.lg) parts.push(`sg-list-grid-lg-${grid.lg}`)
  return parts.join(' ')
})

interface VirtualSlice {
  startIndex: number
  endIndex: number
  offsetTop: number
  totalHeight: number
}

const virtualSlice = computed<VirtualSlice | null>(() => {
  if (!props.virtual) return null
  const { itemHeight, height, overscan = 5 } = props.virtual
  const totalHeight = paginatedData.value.length * itemHeight
  const startIndex = Math.max(0, Math.floor(scrollTop.value / itemHeight) - overscan)
  const visibleCount = Math.ceil(height / itemHeight) + overscan * 2
  const endIndex = Math.min(paginatedData.value.length, startIndex + visibleCount)
  const offsetTop = startIndex * itemHeight
  return { startIndex, endIndex, offsetTop, totalHeight }
})

function rowCls(item: T, index: number): string {
  const isSelected = props.selectable && selectedKeys.value.includes(index)
  const isDragging = dragIndex.value === index
  const isDropTarget = dropIndex.value === index && dragIndex.value !== index
  const extra =
    typeof props.rowClassName === 'function'
      ? props.rowClassName(item, index)
      : (props.rowClassName ?? '')

  return [
    'sg-list-item',
    props.selectable ? 'sg-list-item-selectable' : '',
    isSelected ? 'sg-list-item-selected' : '',
    props.hoverable ? 'sg-list-item-hoverable' : '',
    isDragging ? 'sg-list-item-dragging' : '',
    isDropTarget ? 'sg-list-item-drop-target' : '',
    sCls.value.item ?? '',
    extra,
  ]
    .filter(Boolean)
    .join(' ')
}

const wrapperClass = computed(() => {
  if (props.unstyled) return ''
  return [
    'sg-list',
    `sg-list-${props.size}`,
    props.split ? 'sg-list-split' : '',
    props.bordered ? 'sg-list-bordered' : '',
    props.loading ? 'sg-list-loading' : '',
    props.grid ? 'sg-list-grid' : '',
    props.selectable ? 'sg-list-selectable' : '',
    props.draggable ? 'sg-list-draggable' : '',
    gridResponsiveClass.value,
    sCls.value.root ?? '',
  ]
    .filter(Boolean)
    .join(' ')
})

const itemsContainerClass = computed(() =>
  ['sg-list-items', sCls.value.items ?? ''].filter(Boolean).join(' '),
)

defineExpose({
  /** Currently selected item indices (uncontrolled mode). */
  selectedKeys: internalSelectedKeys,
  /** Programmatically change the page. */
  changePage,
})
</script>

<template>
  <div :class="wrapperClass" :style="sSty.root">
    <div
      v-if="slots.header || header"
      :class="['sg-list-header', sCls.header].filter(Boolean).join(' ') || undefined"
      :style="sSty.header"
    >
      <slot name="header">{{ header }}</slot>
    </div>

    <div v-if="loading" class="sg-list-loading-indicator" role="status" aria-live="polite">
      <span v-if="!unstyled" class="sg-spin sg-spin-default" aria-label="Loading" />
    </div>

    <div
      v-else-if="paginatedData.length === 0"
      :class="['sg-list-empty', sCls.empty].filter(Boolean).join(' ') || undefined"
      :style="sSty.empty"
    >
      {{ emptyText }}
    </div>

    <div
      v-else-if="virtual && virtualSlice"
      ref="virtualEl"
      class="sg-list-virtual-container"
      :style="{ height: `${virtual.height}px`, overflow: 'auto' }"
      @scroll="handleVirtualScroll"
    >
      <div :style="{ height: `${virtualSlice.totalHeight}px`, position: 'relative' }">
        <div
          :style="{ position: 'absolute', top: `${virtualSlice.offsetTop}px`, left: 0, right: 0 }"
        >
          <div
            v-for="(item, i) in paginatedData.slice(virtualSlice.startIndex, virtualSlice.endIndex)"
            :key="virtualSlice.startIndex + i"
            :class="rowCls(item, virtualSlice.startIndex + i) || undefined"
            :style="sSty.item"
            :draggable="draggable"
            @click="(e: MouseEvent) => handleItemClick(item, virtualSlice!.startIndex + i, e)"
            @dragstart="(e: DragEvent) => handleDragStart(e, virtualSlice!.startIndex + i)"
            @dragover="(e: DragEvent) => handleDragOver(e, virtualSlice!.startIndex + i)"
            @drop="(e: DragEvent) => handleDrop(e, virtualSlice!.startIndex + i)"
            @dragend="handleDragEnd"
            @dragleave="dropIndex = null"
          >
            <span v-if="draggable" class="sg-list-drag-handle">⠿</span>
            <slot :item="item" :index="virtualSlice.startIndex + i" />
          </div>
        </div>
      </div>
    </div>

    <div
      v-else
      :class="grid || sCls.items ? itemsContainerClass : undefined"
      :style="grid ? { ...gridStyle, ...sSty.items } : sSty.items"
    >
      <div
        v-for="(item, i) in paginatedData"
        :key="i"
        :class="rowCls(item, i) || undefined"
        :style="sSty.item"
        :draggable="draggable"
        @click="(e: MouseEvent) => handleItemClick(item, i, e)"
        @dragstart="(e: DragEvent) => handleDragStart(e, i)"
        @dragover="(e: DragEvent) => handleDragOver(e, i)"
        @drop="(e: DragEvent) => handleDrop(e, i)"
        @dragend="handleDragEnd"
        @dragleave="dropIndex = null"
      >
        <span v-if="draggable" class="sg-list-drag-handle">⠿</span>
        <slot :item="item" :index="i" />
      </div>
    </div>

    <div v-if="slots.loadMore" class="sg-list-load-more">
      <slot name="loadMore" />
    </div>

    <div
      v-if="pagination"
      :class="['sg-list-pagination', sCls.pagination].filter(Boolean).join(' ') || undefined"
      :style="sSty.pagination"
    >
      <button
        type="button"
        class="sg-list-pagination-prev"
        :disabled="currentPage <= 1"
        @click="changePage(currentPage - 1)"
      >
        ‹
      </button>
      <span class="sg-list-pagination-info">{{ currentPage }} / {{ pageCount }}</span>
      <button
        type="button"
        class="sg-list-pagination-next"
        :disabled="currentPage >= pageCount"
        @click="changePage(currentPage + 1)"
      >
        ›
      </button>
    </div>

    <div
      v-if="slots.footer || footer"
      :class="['sg-list-footer', sCls.footer].filter(Boolean).join(' ') || undefined"
      :style="sSty.footer"
    >
      <slot name="footer">{{ footer }}</slot>
    </div>
  </div>
</template>
