// packages/react/src/components/complex/AutoField/AutoField.tsx
import React, { useMemo } from 'react'
import { useFormContext } from '../FormContext'
import { useConfig } from '../../ConfigProvider'
import type { BaseComponentProps, InteractiveProps } from '../../../types'

/** Supported input kinds for form field rendering and inference. */
export type FieldType =
  | 'string'
  | 'number'
  | 'boolean'
  | 'email'
  | 'url'
  | 'date'
  | 'time'
  | 'textarea'
  | 'select'
  | 'multiselect'
  | 'password'
  | 'color'
  | 'slider'
  | 'rate'
  | 'file'
  | 'switch'
  | 'radio'

/** Single choice label/value pair for select, multiselect, or radio fields. */
export interface AutoFieldOption {
  /** Display text for the option. */
  label: string
  /** Stored value when the option is selected. */
  value: string | number
}

/** Props for a form field that picks its control from field name, value shape, and `type`. */
export interface AutoFieldProps extends BaseComponentProps, InteractiveProps {
  /** Form field key used with `useFormContext`. */
  name: string
  /** Caption shown above the control (or inline for checkbox/switch). */
  label?: React.ReactNode
  /** Forces a control type; otherwise inferred from value and `options`. */
  type?: FieldType
  /** Options for select, multiselect, or radio types. */
  options?: AutoFieldOption[]
  /** Placeholder or empty-option label where applicable. */
  placeholder?: string
  /** Minimum numeric or range value. */
  min?: number
  /** Maximum numeric, range, or star rating count. */
  max?: number
  /** Step for number inputs and range sliders. */
  step?: number
  /** `accept` attribute for file inputs. */
  accept?: string
  /** Allows multiple files when type is `file`. */
  multiple?: boolean
}

/**
 * Renders an appropriate input for a form field based on `type`, options, and current value.
 * Reads and writes through `FormContext` using `name`.
 */
export function AutoField(props: AutoFieldProps) {
  const {
    name,
    label,
    type: forcedType,
    options,
    placeholder,
    disabled: disabledProp,
    className,
    style,
    min,
    max,
    step,
    accept,
    multiple,
  } = props
  const config = useConfig()
  const disabled = disabledProp ?? config.disabled
  const { form } = useFormContext()

  const value = form.getValue(name)
  const meta = form.getFieldState(name)

  const inferredType = useMemo((): FieldType => {
    if (forcedType) return forcedType
    if (options && options.length > 0) return 'select'
    if (typeof value === 'boolean') return 'boolean'
    if (typeof value === 'number') return 'number'
    if (typeof value === 'string') {
      if (value.includes('@')) return 'email'
      if (value.startsWith('http')) return 'url'
    }
    return 'string'
  }, [forcedType, options, value])

  const handleChange = (newValue: unknown) => {
    form.setValue(name, newValue)
  }

  const errorId = `${name}-error`
  const hasErrors = meta.errors.length > 0
  const hasWarnings = meta.warnings.length > 0

  const inputClass = [
    'sg-autofield-input',
    hasErrors ? 'sg-autofield-input-error' : hasWarnings ? 'sg-autofield-input-warning' : '',
  ]
    .filter(Boolean)
    .join(' ')

  function renderInput() {
    switch (inferredType) {
      case 'boolean':
      case 'switch':
        return (
          <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={!!value}
              onChange={(e) => handleChange(e.target.checked)}
              disabled={disabled}
              role={inferredType === 'switch' ? 'switch' : undefined}
            />
            {label}
          </label>
        )

      case 'number':
        return (
          <input
            type="number"
            value={value == null ? '' : String(value)}
            onChange={(e) => handleChange(e.target.value === '' ? null : Number(e.target.value))}
            onBlur={() => form.onFieldBlur(name)}
            placeholder={placeholder}
            disabled={disabled}
            min={min}
            max={max}
            step={step}
            className={inputClass}
            aria-invalid={hasErrors}
            aria-describedby={hasErrors ? errorId : undefined}
          />
        )

      case 'textarea':
        return (
          <textarea
            value={value == null ? '' : String(value)}
            onChange={(e) => handleChange(e.target.value)}
            onBlur={() => form.onFieldBlur(name)}
            placeholder={placeholder}
            disabled={disabled}
            className={`${inputClass} sg-autofield-input-textarea`}
            aria-invalid={hasErrors}
            aria-describedby={hasErrors ? errorId : undefined}
          />
        )

      case 'select':
        return (
          <select
            value={value == null ? '' : String(value)}
            onChange={(e) => handleChange(e.target.value)}
            disabled={disabled}
            className={inputClass}
            aria-invalid={hasErrors}
            aria-describedby={hasErrors ? errorId : undefined}
          >
            <option value="">{placeholder ?? '-- Select --'}</option>
            {options?.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
        )

      case 'multiselect':
        return (
          <select
            multiple
            value={Array.isArray(value) ? value.map(String) : []}
            onChange={(e) => {
              const selected = Array.from(e.target.selectedOptions, (o) => o.value)
              handleChange(selected)
            }}
            disabled={disabled}
            className={`${inputClass} sg-autofield-input-multiple`}
            aria-invalid={hasErrors}
            aria-describedby={hasErrors ? errorId : undefined}
          >
            {options?.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
        )

      case 'radio':
        return (
          <div role="radiogroup" style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            {options?.map((opt) => (
              <label
                key={opt.value}
                style={{ display: 'flex', alignItems: 'center', gap: 4, cursor: 'pointer' }}
              >
                <input
                  type="radio"
                  name={name}
                  value={opt.value}
                  checked={value === opt.value}
                  onChange={() => handleChange(opt.value)}
                  disabled={disabled}
                />
                {opt.label}
              </label>
            ))}
          </div>
        )

      case 'date':
        return (
          <input
            type="date"
            value={value == null ? '' : String(value)}
            onChange={(e) => handleChange(e.target.value)}
            disabled={disabled}
            className={inputClass}
            aria-invalid={hasErrors}
            aria-describedby={hasErrors ? errorId : undefined}
          />
        )

      case 'time':
        return (
          <input
            type="time"
            value={value == null ? '' : String(value)}
            onChange={(e) => handleChange(e.target.value)}
            disabled={disabled}
            className={inputClass}
            aria-invalid={hasErrors}
            aria-describedby={hasErrors ? errorId : undefined}
          />
        )

      case 'password':
        return (
          <input
            type="password"
            value={value == null ? '' : String(value)}
            onChange={(e) => handleChange(e.target.value)}
            onBlur={() => form.onFieldBlur(name)}
            placeholder={placeholder}
            disabled={disabled}
            className={inputClass}
            aria-invalid={hasErrors}
            aria-describedby={hasErrors ? errorId : undefined}
          />
        )

      case 'color':
        return (
          <input
            type="color"
            value={value == null ? '#000000' : String(value)}
            onChange={(e) => handleChange(e.target.value)}
            disabled={disabled}
            className={`${inputClass} sg-autofield-input-color`}
          />
        )

      case 'slider':
        return (
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <input
              type="range"
              value={value == null ? (min ?? 0) : Number(value)}
              onChange={(e) => handleChange(Number(e.target.value))}
              min={min ?? 0}
              max={max ?? 100}
              step={step ?? 1}
              disabled={disabled}
              style={{ flex: 1 }}
            />
            <span style={{ minWidth: 32, textAlign: 'right', fontSize: 14 }}>
              {String(value ?? min ?? 0)}
            </span>
          </div>
        )

      case 'rate': {
        const maxStars = max ?? 5
        const currentRate = typeof value === 'number' ? value : 0
        return (
          <div style={{ display: 'flex', gap: 2 }}>
            {Array.from({ length: maxStars }, (_, i) => (
              <button
                key={i}
                type="button"
                onClick={() => !disabled && handleChange(i + 1)}
                disabled={disabled}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: disabled ? 'default' : 'pointer',
                  fontSize: 20,
                  color:
                    i < currentRate
                      ? 'var(--sg-color-warning, #faad14)'
                      : 'var(--sg-color-border, #d9d9d9)',
                  padding: 0,
                }}
                aria-label={`${i + 1} star${i !== 0 ? 's' : ''}`}
              >
                ★
              </button>
            ))}
          </div>
        )
      }

      case 'file':
        return (
          <input
            type="file"
            accept={accept}
            multiple={multiple}
            onChange={(e) => {
              const files = e.target.files
              if (files) handleChange(multiple ? Array.from(files) : (files[0] ?? null))
            }}
            disabled={disabled}
            className={inputClass}
          />
        )

      case 'email':
      case 'url':
      case 'string':
      default:
        return (
          <input
            type={inferredType === 'email' ? 'email' : inferredType === 'url' ? 'url' : 'text'}
            value={value == null ? '' : String(value)}
            onChange={(e) => handleChange(e.target.value)}
            onBlur={() => form.onFieldBlur(name)}
            placeholder={placeholder}
            disabled={disabled}
            className={inputClass}
            aria-invalid={hasErrors}
            aria-describedby={hasErrors ? errorId : undefined}
          />
        )
    }
  }

  return (
    <div className={`sg-autofield ${className ?? ''}`} style={style}>
      {inferredType !== 'boolean' && inferredType !== 'switch' && label && (
        <label className="sg-autofield-label">{label}</label>
      )}
      {renderInput()}
      {hasErrors && (
        <span
          id={errorId}
          role="alert"
          style={{ color: 'var(--sg-color-error, #ff4d4f)', fontSize: 12 }}
        >
          {meta.errors.join('; ')}
        </span>
      )}
      {hasWarnings && !hasErrors && (
        <span style={{ color: 'var(--sg-color-warning, #faad14)', fontSize: 12 }}>
          {meta.warnings.join('; ')}
        </span>
      )}
    </div>
  )
}

// packages/vue/src/components/complex/SchemaForm/AutoField.vue
<script setup lang="ts">
import { computed, inject } from 'vue'
import { formContextKey } from '../Form/context'

export type FieldType =
  | 'string'
  | 'number'
  | 'boolean'
  | 'email'
  | 'url'
  | 'date'
  | 'time'
  | 'textarea'
  | 'select'
  | 'multiselect'
  | 'password'
  | 'color'
  | 'slider'
  | 'rate'
  | 'file'
  | 'switch'
  | 'radio'

export interface AutoFieldOption {
  label: string
  value: string | number
}

export interface AutoFieldProps {
  name: string
  label?: string
  type?: FieldType
  options?: AutoFieldOption[]
  placeholder?: string
  min?: number
  max?: number
  step?: number
  accept?: string
  multiple?: boolean
  disabled?: boolean
}

const props = defineProps<AutoFieldProps>()

const injected = inject(formContextKey, null)
if (!injected) {
  throw new Error('[skygraph/vue] <SgAutoField> must be used inside an <SgForm>')
}
const ctx = injected

const value = computed(() => ctx.form.getValue(props.name))
const meta = computed(() => ctx.form.getFieldState(props.name))

const inferredType = computed<FieldType>(() => {
  if (props.type) return props.type
  if (props.options && props.options.length > 0) return 'select'
  const v = value.value
  if (typeof v === 'boolean') return 'boolean'
  if (typeof v === 'number') return 'number'
  if (typeof v === 'string') {
    if (v.includes('@')) return 'email'
    if (v.startsWith('http')) return 'url'
  }
  return 'string'
})

const handleChange = (newValue: unknown) => {
  ctx.form.setValue(props.name, newValue)
}

const isDisabled = computed(() => props.disabled ?? ctx.disabled)

const hasErrors = computed(() => meta.value.errors.length > 0)
const hasWarnings = computed(() => meta.value.warnings.length > 0)
const errorId = computed(() => `${props.name}-error`)

const fieldStateClass = computed(() => ({
  'sg-autofield-input-error': hasErrors.value,
  'sg-autofield-input-warning': !hasErrors.value && hasWarnings.value,
}))
</script>

<template>
  <div class="sg-autofield">
    <label
      v-if="inferredType !== 'boolean' && inferredType !== 'switch' && label"
      class="sg-autofield-label"
    >
      {{ label }}
    </label>
    <template v-if="inferredType === 'boolean' || inferredType === 'switch'">
      <label style="display: flex; align-items: center; gap: 8px; cursor: pointer">
        <input
          type="checkbox"
          :checked="!!value"
          :disabled="isDisabled"
          :role="inferredType === 'switch' ? 'switch' : undefined"
          @change="(e) => handleChange((e.target as HTMLInputElement).checked)"
        />
        {{ label }}
      </label>
    </template>
    <input
      v-else-if="inferredType === 'number'"
      type="number"
      class="sg-autofield-input"
      :class="fieldStateClass"
      :value="value == null ? '' : String(value)"
      :placeholder="placeholder"
      :disabled="isDisabled"
      :min="min"
      :max="max"
      :step="step"
      :aria-invalid="hasErrors || undefined"
      :aria-describedby="hasErrors ? errorId : undefined"
      @input="
        (e) => {
          const raw = (e.target as HTMLInputElement).value
          handleChange(raw === '' ? null : Number(raw))
        }
      "
      @blur="ctx.form.onFieldBlur(name)"
    />
    <textarea
      v-else-if="inferredType === 'textarea'"
      class="sg-autofield-input sg-autofield-input-textarea"
      :class="fieldStateClass"
      :value="value == null ? '' : String(value)"
      :placeholder="placeholder"
      :disabled="isDisabled"
      :aria-invalid="hasErrors || undefined"
      :aria-describedby="hasErrors ? errorId : undefined"
      @input="(e) => handleChange((e.target as HTMLTextAreaElement).value)"
      @blur="ctx.form.onFieldBlur(name)"
    />
    <select
      v-else-if="inferredType === 'select'"
      class="sg-autofield-input"
      :class="fieldStateClass"
      :value="value == null ? '' : String(value)"
      :disabled="isDisabled"
      :aria-invalid="hasErrors || undefined"
      :aria-describedby="hasErrors ? errorId : undefined"
      @change="(e) => handleChange((e.target as HTMLSelectElement).value)"
    >
      <option value="">{{ placeholder ?? '-- Select --' }}</option>
      <option v-for="opt in options" :key="opt.value" :value="opt.value">
        {{ opt.label }}
      </option>
    </select>
    <select
      v-else-if="inferredType === 'multiselect'"
      multiple
      class="sg-autofield-input sg-autofield-input-multiple"
      :class="fieldStateClass"
      :value="Array.isArray(value) ? (value as (string | number)[]).map(String) : []"
      :disabled="isDisabled"
      :aria-invalid="hasErrors || undefined"
      @change="
        (e) => {
          const sel = Array.from((e.target as HTMLSelectElement).selectedOptions, (o) => o.value)
          handleChange(sel)
        }
      "
    >
      <option v-for="opt in options" :key="opt.value" :value="opt.value">
        {{ opt.label }}
      </option>
    </select>
    <div
      v-else-if="inferredType === 'radio'"
      role="radiogroup"
      style="display: flex; gap: 12px; flex-wrap: wrap"
    >
      <label
        v-for="opt in options"
        :key="opt.value"
        style="display: flex; align-items: center; gap: 4px; cursor: pointer"
      >
        <input
          type="radio"
          :name="name"
          :value="opt.value"
          :checked="value === opt.value"
          :disabled="isDisabled"
          @change="handleChange(opt.value)"
        />
        {{ opt.label }}
      </label>
    </div>
    <input
      v-else-if="inferredType === 'date'"
      type="date"
      class="sg-autofield-input"
      :class="fieldStateClass"
      :value="value == null ? '' : String(value)"
      :disabled="isDisabled"
      :aria-invalid="hasErrors || undefined"
      @input="(e) => handleChange((e.target as HTMLInputElement).value)"
    />
    <input
      v-else-if="inferredType === 'time'"
      type="time"
      class="sg-autofield-input"
      :class="fieldStateClass"
      :value="value == null ? '' : String(value)"
      :disabled="isDisabled"
      :aria-invalid="hasErrors || undefined"
      @input="(e) => handleChange((e.target as HTMLInputElement).value)"
    />
    <input
      v-else-if="inferredType === 'password'"
      type="password"
      class="sg-autofield-input"
      :class="fieldStateClass"
      :value="value == null ? '' : String(value)"
      :placeholder="placeholder"
      :disabled="isDisabled"
      :aria-invalid="hasErrors || undefined"
      @input="(e) => handleChange((e.target as HTMLInputElement).value)"
      @blur="ctx.form.onFieldBlur(name)"
    />
    <input
      v-else-if="inferredType === 'color'"
      type="color"
      class="sg-autofield-input sg-autofield-input-color"
      :value="value == null ? '#000000' : String(value)"
      :disabled="isDisabled"
      @input="(e) => handleChange((e.target as HTMLInputElement).value)"
    />
    <div v-else-if="inferredType === 'slider'" style="display: flex; align-items: center; gap: 8px">
      <input
        type="range"
        :value="value == null ? (min ?? 0) : Number(value)"
        :min="min ?? 0"
        :max="max ?? 100"
        :step="step ?? 1"
        :disabled="isDisabled"
        style="flex: 1"
        @input="(e) => handleChange(Number((e.target as HTMLInputElement).value))"
      />
      <span style="min-width: 32px; text-align: right; font-size: 14px">{{
        String(value ?? min ?? 0)
      }}</span>
    </div>
    <div v-else-if="inferredType === 'rate'" style="display: flex; gap: 2px">
      <button
        v-for="i in max ?? 5"
        :key="i"
        type="button"
        :disabled="isDisabled"
        :aria-label="`${i} star${i !== 1 ? 's' : ''}`"
        :style="{
          background: 'none',
          border: 'none',
          cursor: isDisabled ? 'default' : 'pointer',
          fontSize: '20px',
          color:
            i <= (typeof value === 'number' ? value : 0)
              ? 'var(--sg-color-warning, #faad14)'
              : 'var(--sg-color-border, #d9d9d9)',
          padding: 0,
        }"
        @click="!isDisabled && handleChange(i)"
      >
        ★
      </button>
    </div>
    <input
      v-else-if="inferredType === 'file'"
      type="file"
      class="sg-autofield-input"
      :class="fieldStateClass"
      :accept="accept"
      :multiple="multiple"
      :disabled="isDisabled"
      @change="
        (e) => {
          const files = (e.target as HTMLInputElement).files
          if (files) handleChange(multiple ? Array.from(files) : (files[0] ?? null))
        }
      "
    />
    <input
      v-else
      :type="inferredType === 'email' ? 'email' : inferredType === 'url' ? 'url' : 'text'"
      class="sg-autofield-input"
      :class="fieldStateClass"
      :value="value == null ? '' : String(value)"
      :placeholder="placeholder"
      :disabled="isDisabled"
      :aria-invalid="hasErrors || undefined"
      :aria-describedby="hasErrors ? errorId : undefined"
      @input="(e) => handleChange((e.target as HTMLInputElement).value)"
      @blur="ctx.form.onFieldBlur(name)"
    />
    <span
      v-if="hasErrors"
      :id="errorId"
      role="alert"
      style="color: var(--sg-color-error, #ff4d4f); font-size: 12px"
    >
      {{ meta.errors.join('; ') }}
    </span>
    <span v-else-if="hasWarnings" style="color: var(--sg-color-warning, #faad14); font-size: 12px">
      {{ meta.warnings.join('; ') }}
    </span>
  </div>
</template>
