// packages/vue/src/components/complex/Charts/AreaChart.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useChartSize } from '../../../composables/useChartSize'
import { printElement } from '../../../utils/print'
import { useConfig } from '../../ui/ConfigProvider.vue'
import {
  chartBounds,
  colorForSeries,
  resolveChartPadding,
  resolveChartAnimation,
  type BaseChartProps,
} from './types'
import ChartLegend from './ChartLegend.vue'
import ChartAxes from './ChartAxes.vue'
import ChartBrush, {
  resolveBrushConfig,
  type ChartBrushConfig,
  type ChartBrushRange,
} from './ChartBrush.vue'

interface AreaChartProps extends BaseChartProps {
  /** Stack series cumulatively. @default false */
  stacked?: boolean
  /** Fill opacity 0..1. @default 0.3 */
  fillOpacity?: number
  /** Stroke width. @default 2 */
  strokeWidth?: number
  /**
   * Brush for drag-selecting an X range. `true` — uncontrolled with empty
   * starting value; object — `ChartBrushConfig`.
   */
  brush?: boolean | ChartBrushConfig
}

const props = withDefaults(defineProps<AreaChartProps>(), {
  width: '100%',
  height: 200,
  unstyled: false,
  legend: false,
  stacked: false,
  fillOpacity: 0.3,
  strokeWidth: 2,
  fileName: 'chart',
})

const rootRef = ref<HTMLDivElement | null>(null)
const svgRef = ref<SVGSVGElement | null>(null)
const cfg = useConfig()
const chartLabel = computed(() => cfg.value.locale?.charts?.areaChart ?? 'Area chart')
const fallbackW = computed(() =>
  typeof props.width === 'number' && Number.isFinite(props.width) ? props.width : 600,
)
const fallbackH = computed(() =>
  typeof props.height === 'number' && Number.isFinite(props.height) ? props.height : 200,
)
const { size } = useChartSize(svgRef, { width: fallbackW.value, height: fallbackH.value })

const animation = computed(() => resolveChartAnimation(props.animate))

const stackedValues = computed(() => {
  if (!props.stacked) return null
  const stacks: number[][] = props.series.map(() => props.categories.map(() => 0))
  for (let ci = 0; ci < props.categories.length; ci++) {
    let acc = 0
    for (let si = 0; si < props.series.length; si++) {
      const v = props.series[si].values[ci]
      if (v == null) {
        stacks[si][ci] = acc
      } else {
        acc += v
        stacks[si][ci] = acc
      }
    }
  }
  return stacks
})

const bounds = computed(() => {
  if (props.stacked && stackedValues.value) {
    const last = stackedValues.value[stackedValues.value.length - 1]
    const max = Math.max(0, ...last)
    return { min: 0, max: max === 0 ? 1 : max }
  }
  const { min, max } = chartBounds(props.series.map((s) => s.values))
  return { min: Math.min(0, min), max: Math.max(0, max) }
})

const padding = computed(() =>
  resolveChartPadding(props.padding, props.yAxis, bounds.value.min, bounds.value.max),
)
const viewW = computed(() => size.value.width)
const viewH = computed(() => size.value.height)
const plotX = computed(() => padding.value[3])
const plotY = computed(() => padding.value[0])
const plotW = computed(() => Math.max(0, viewW.value - padding.value[3] - padding.value[1]))
const plotH = computed(() => Math.max(0, viewH.value - padding.value[0] - padding.value[2]))

const xCoord = (i: number) => {
  const n = props.categories.length
  if (n <= 1) return plotX.value
  return plotX.value + (plotW.value * i) / (n - 1)
}

const yCoord = (v: number) => {
  const { min, max } = bounds.value
  if (max === min) return plotY.value + plotH.value / 2
  return plotY.value + plotH.value * (1 - (v - min) / (max - min))
}

const baselineY = computed(() => yCoord(0))

const areaPaths = computed(() =>
  props.series.map((s, si) => {
    const color = colorForSeries(s, si)
    const upper: { x: number; y: number }[] = []
    const lower: { x: number; y: number }[] = []

    for (let ci = 0; ci < props.categories.length; ci++) {
      let topV: number | null
      let bottomY = baselineY.value
      if (props.stacked && stackedValues.value) {
        const cur = stackedValues.value[si][ci]
        const prev = si > 0 ? stackedValues.value[si - 1][ci] : 0
        topV = cur
        bottomY = yCoord(prev)
      } else {
        topV = s.values[ci] ?? null
      }
      if (topV == null) continue
      upper.push({ x: xCoord(ci), y: yCoord(topV) })
      lower.push({ x: xCoord(ci), y: bottomY })
    }
    if (upper.length === 0) return { id: s.id, color, label: s.label, areaPath: '', linePath: '' }
    const linePath = upper.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x},${p.y}`).join(' ')
    const reversedLower = [...lower].reverse()
    const areaPath = `${linePath} ${reversedLower.map((p) => `L${p.x},${p.y}`).join(' ')} Z`
    return { id: s.id, color, label: s.label, areaPath, linePath }
  }),
)

const brushConfig = computed(() => resolveBrushConfig(props.brush))
const isBrushControlled = computed(() => brushConfig.value != null && 'range' in brushConfig.value)
const internalBrushRange = ref<ChartBrushRange | null>(brushConfig.value?.defaultRange ?? null)
const effectiveBrushRange = computed<ChartBrushRange | null>(() =>
  isBrushControlled.value ? (brushConfig.value!.range ?? null) : internalBrushRange.value,
)
function handleBrushChange(next: ChartBrushRange | null) {
  if (!isBrushControlled.value) internalBrushRange.value = next
  brushConfig.value?.onRangeChange?.(next)
}

const areaAnimStyle = computed(() =>
  animation.value.enabled
    ? { '--sg-chart-anim-duration': `${animation.value.duration}ms` }
    : undefined,
)

defineExpose({
  print: (opts: { fileName?: string } = {}) => {
    const el = rootRef.value
    if (!el) return
    printElement(el, { fileName: opts.fileName ?? props.fileName ?? 'chart' })
  },
  exportSvg: () => {
    const svg = svgRef.value
    if (!svg) return null
    return new XMLSerializer().serializeToString(svg)
  },
})
</script>

<template>
  <div
    ref="rootRef"
    :class="[!props.unstyled && 'sg-chart sg-chart-area', props.className]"
    :style="{ width: typeof props.width === 'number' ? `${props.width}px` : props.width }"
    :data-animate="animation.enabled ? 'on' : 'off'"
  >
    <svg
      ref="svgRef"
      :viewBox="`0 0 ${viewW} ${viewH}`"
      :width="typeof props.width === 'number' ? props.width : '100%'"
      :height="props.height"
      role="img"
      :aria-label="chartLabel"
    >
      <ChartAxes
        :x="plotX"
        :y="plotY"
        :plotW="plotW"
        :plotH="plotH"
        :categories="props.categories"
        :yMin="bounds.min"
        :yMax="bounds.max"
        :xAxis="props.xAxis"
        :yAxis="props.yAxis"
        :unstyled="props.unstyled"
      />
      <g class="sg-chart-area-paths">
        <path
          v-for="a in areaPaths"
          :key="`${a.id}-area`"
          :class="[animation.enabled && !props.unstyled && 'sg-chart-area-animate']"
          :d="a.areaPath"
          :fill="a.color"
          :fill-opacity="props.fillOpacity"
          :data-series-id="a.id"
          :style="areaAnimStyle"
        />
        <path
          v-for="a in areaPaths"
          :key="`${a.id}-line`"
          :class="[animation.enabled && !props.unstyled && 'sg-chart-area-animate']"
          :d="a.linePath"
          :stroke="a.color"
          :stroke-width="props.strokeWidth"
          fill="none"
          vector-effect="non-scaling-stroke"
          :style="areaAnimStyle"
        />
      </g>
      <ChartBrush
        v-if="brushConfig"
        :plot-x="plotX"
        :plot-y="plotY"
        :plot-w="plotW"
        :plot-h="plotH"
        :category-count="props.categories.length"
        :range="effectiveBrushRange"
        :unstyled="props.unstyled"
        :fill="brushConfig.fill"
        :disabled="brushConfig.disabled"
        @change="handleBrushChange"
      />
    </svg>
    <ChartLegend v-if="props.legend" :series="props.series" :unstyled="props.unstyled" />
  </div>
</template>

// packages/react/src/components/complex/Charts/AreaChart.tsx
import { forwardRef, useMemo, useRef, useState, type CSSProperties, type ForwardedRef } from 'react'
import {
  chartBounds,
  chartDataKey,
  colorForSeries,
  resolveChartPadding,
  resolveChartAnimation,
} from './types'
import { ChartLegend } from './ChartLegend'
import { ChartAxes } from './ChartAxes'
import {
  ChartBrush,
  resolveBrushConfig,
  type ChartBrushConfig,
  type ChartBrushRange,
} from './ChartBrush'
import type { BaseChartProps } from './types'
import { useChartPrint, type ChartRef } from './chartRef'
import { useChartSize } from './useChartSize'
import { ChartHoverToolbar, resolveChartActions } from './ChartHoverToolbar'
import { makeChartContextMenuHandler, makeSeriesContextMenuHandler } from './chartContextMenu'
import { useConfig } from '../../ConfigProvider'

export interface AreaChartProps extends BaseChartProps {
  /** Stack series on top of each other (cumulative). @default false */
  stacked?: boolean
  /** Stroke width on the top edge. @default 2 */
  strokeWidth?: number
  /** Fill opacity (0..1). @default 0.25 */
  fillOpacity?: number
  /**
   * Brush для drag-выбора диапазона по X. `true` — uncontrolled с пустым
   * стартовым значением; объект — `ChartBrushConfig`. См. `ChartBrush`.
   */
  brush?: boolean | ChartBrushConfig
}

/**
 * Minimal SVG area chart. v0 — straight segments between points, optional
 * stacking. Responsive viewBox через `useChartSize`.
 */
function AreaChartInner(
  {
    categories,
    series,
    width = '100%',
    height = 200,
    className,
    style,
    unstyled = false,
    padding,
    stacked = false,
    strokeWidth = 2,
    fillOpacity = 0.25,
    legend = false,
    xAxis,
    yAxis,
    animate,
    brush,
    printable,
    actions,
    fileName,
    onSeriesContextMenu,
    onChartContextMenu,
  }: AreaChartProps,
  forwardedRef: ForwardedRef<ChartRef>,
) {
  const chartsLocale = useConfig().locale?.charts
  const { rootRef } = useChartPrint<Element>(forwardedRef, printable)
  const svgRef = useRef<SVGSVGElement | null>(null)

  // Effective values per series — for stacked, each series adds to the
  // running total (treating null as 0 for the stack base).
  const stackedValues = useMemo(() => {
    if (!stacked) return series.map((s) => [...s.values])
    const totals = new Array(categories.length).fill(0)
    return series.map((s) => {
      const out: (number | null)[] = []
      s.values.forEach((v, i) => {
        if (v === null || v === undefined) {
          out.push(null)
          return
        }
        totals[i] += v
        out.push(totals[i])
      })
      return out
    })
  }, [series, stacked, categories.length])

  const { min, max } = useMemo(() => chartBounds(stackedValues), [stackedValues])

  const baseline = Math.min(0, min)
  const top = Math.max(0, max)
  const span = top - baseline || 1

  const [pt, pr, pb, pl] = useMemo(
    () => resolveChartPadding(padding, yAxis, baseline, top),
    [padding, yAxis, baseline, top],
  )

  const fallbackW = typeof width === 'number' && Number.isFinite(width) ? width : 600
  const fallbackH = typeof height === 'number' && Number.isFinite(height) ? height : 200
  const measured = useChartSize<SVGSVGElement>(svgRef, { width: fallbackW, height: fallbackH })
  const viewW = measured.width
  const viewH = measured.height
  const plotW = Math.max(0, viewW - pl - pr)
  const plotH = Math.max(0, viewH - pt - pb)

  const xStep = categories.length > 1 ? plotW / (categories.length - 1) : 0
  function xFor(i: number) {
    return pl + i * xStep
  }
  function yFor(v: number) {
    return pt + ((top - v) / span) * plotH
  }
  const yBase = yFor(0)

  const wrapperClass = unstyled
    ? className
    : ['sg-chart', 'sg-chart-area', className].filter(Boolean).join(' ')

  const anim = resolveChartAnimation(animate)
  const animKey = useMemo(
    () => chartDataKey([categories, series.map((s) => s.values), stacked]),
    [categories, series, stacked],
  )
  const animStyle: CSSProperties | undefined = anim.enabled
    ? ({ ['--sg-chart-anim-duration' as string]: `${anim.duration}ms` } as CSSProperties)
    : undefined
  const animClass = anim.enabled && !unstyled ? 'sg-chart-area-animate' : undefined

  const brushConfig = resolveBrushConfig(brush)
  const isBrushControlled = brushConfig != null && 'range' in brushConfig
  const [internalBrushRange, setInternalBrushRange] = useState<ChartBrushRange | null>(
    brushConfig?.defaultRange ?? null,
  )
  const effectiveBrushRange = isBrushControlled ? (brushConfig!.range ?? null) : internalBrushRange
  const handleBrushChange = (next: ChartBrushRange | null) => {
    if (!isBrushControlled) setInternalBrushRange(next)
    brushConfig?.onRangeChange?.(next)
  }

  const brushReset = brushConfig
    ? () => {
        if (!isBrushControlled) setInternalBrushRange(null)
        brushConfig.onRangeChange?.(null)
      }
    : undefined
  const resolvedActions = resolveChartActions(actions, { fileName, brushReset })
  const [toolbarVisible, setToolbarVisible] = useState(false)
  const handleSvgContextMenu = makeChartContextMenuHandler(onChartContextMenu)

  const setSvgRef = (el: SVGSVGElement | null) => {
    svgRef.current = el
    if (!legend) (rootRef as React.MutableRefObject<Element | null>).current = el
  }

  const svg = (
    <svg
      ref={setSvgRef}
      className={wrapperClass}
      style={legend || resolvedActions ? undefined : style}
      width={width}
      height={height}
      viewBox={`0 0 ${viewW} ${viewH}`}
      role="img"
      aria-label={chartsLocale?.areaChart ?? 'Area chart'}
      onContextMenu={handleSvgContextMenu}
    >
      <ChartAxes
        plotX={pl}
        plotY={pt}
        plotW={plotW}
        plotH={plotH}
        min={baseline}
        max={top}
        categories={categories}
        xAxis={xAxis}
        yAxis={yAxis}
        unstyled={unstyled}
      />
      {series.map((s, sIdx) => {
        const color = colorForSeries(s, sIdx)
        const vals = stackedValues[sIdx]!
        // Build "area" polygon: top line forward, then close along baseline backward.
        const topPoints: [number, number][] = []
        vals.forEach((v, i) => {
          if (v === null || v === undefined) return
          topPoints.push([xFor(i), yFor(v)])
        })
        if (topPoints.length === 0) return null
        const first = topPoints[0]!
        const last = topPoints[topPoints.length - 1]!
        const areaPath = [
          `M ${first[0]} ${yBase}`,
          ...topPoints.map((p) => `L ${p[0]} ${p[1]}`),
          `L ${last[0]} ${yBase}`,
          'Z',
        ].join(' ')
        const linePath = topPoints
          .map((p, i) => (i === 0 ? `M ${p[0]} ${p[1]}` : `L ${p[0]} ${p[1]}`))
          .join(' ')
        const onSeriesCtx = makeSeriesContextMenuHandler(onSeriesContextMenu, {
          seriesId: s.id,
          seriesIndex: sIdx,
        })
        return (
          <g key={`${s.id}-${animKey}`} className={animClass} style={animStyle}>
            <path
              d={areaPath}
              fill={color}
              fillOpacity={fillOpacity}
              stroke="none"
              onContextMenu={onSeriesCtx}
            />
            <path
              d={linePath}
              fill="none"
              stroke={color}
              strokeWidth={strokeWidth}
              strokeLinecap="round"
              strokeLinejoin="round"
              vectorEffect="non-scaling-stroke"
              onContextMenu={onSeriesCtx}
            />
          </g>
        )
      })}
      {brushConfig && (
        <ChartBrush
          plotX={pl}
          plotY={pt}
          plotW={plotW}
          plotH={plotH}
          categoryCount={categories.length}
          range={effectiveBrushRange}
          onRangeChange={handleBrushChange}
          unstyled={unstyled}
          fill={brushConfig.fill}
          disabled={brushConfig.disabled}
        />
      )}
    </svg>
  )

  const needsWrapper = legend || !!resolvedActions
  if (!needsWrapper) return svg

  return (
    <div
      ref={legend ? (rootRef as React.RefObject<HTMLDivElement>) : undefined}
      className={unstyled ? undefined : 'sg-chart-wrapper'}
      style={style}
      onMouseEnter={resolvedActions ? () => setToolbarVisible(true) : undefined}
      onMouseLeave={resolvedActions ? () => setToolbarVisible(false) : undefined}
      onFocus={resolvedActions ? () => setToolbarVisible(true) : undefined}
      onBlur={resolvedActions ? () => setToolbarVisible(false) : undefined}
    >
      {resolvedActions && (
        <ChartHoverToolbar
          visible={toolbarVisible}
          actions={resolvedActions}
          fileName={fileName}
          getSvg={() => svgRef.current}
          brushReset={brushReset}
          unstyled={unstyled}
        />
      )}
      {svg}
      {legend && <ChartLegend series={series} />}
    </div>
  )
}

export const AreaChart = forwardRef<ChartRef, AreaChartProps>(AreaChartInner)
AreaChart.displayName = 'AreaChart'
