// packages/vue/src/components/complex/Charts/LineChart.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useChartSize } from '../../../composables/useChartSize'
import { printElement } from '../../../utils/print'
import { useConfig } from '../../ui/ConfigProvider.vue'
import {
  chartBounds,
  colorForSeries,
  resolveChartPadding,
  resolveChartAnimation,
  type BaseChartProps,
} from './types'
import ChartLegend from './ChartLegend.vue'
import ChartAxes from './ChartAxes.vue'
import ChartCrosshair, { type ChartCrosshairPoint } from './ChartCrosshair.vue'
import ChartBrush, {
  resolveBrushConfig,
  type ChartBrushConfig,
  type ChartBrushRange,
} from './ChartBrush.vue'

/**
 * Crosshair behaviour toggle for {@link LineChart}. When `true`, a vertical
 * guide line + per-series tooltip appears on hover.
 */
export type LineChartCrosshair =
  | boolean
  | {
      /** Custom formatter for tooltip numeric values. */
      valueFormatter?: (value: number) => string
    }

interface LineChartProps extends BaseChartProps {
  markers?: boolean
  strokeWidth?: number
  /**
   * Hover crosshair with vertical guide line and per-series tooltip.
   * @default false
   */
  crosshair?: LineChartCrosshair
  /**
   * Brush for drag-selecting an X range. `true` — uncontrolled with empty
   * starting value; object — `ChartBrushConfig`. See `ChartBrush`.
   */
  brush?: boolean | ChartBrushConfig
}

const props = withDefaults(defineProps<LineChartProps>(), {
  width: '100%',
  height: 200,
  unstyled: false,
  markers: true,
  strokeWidth: 2,
  legend: false,
  fileName: 'chart',
  crosshair: false,
})

const rootRef = ref<HTMLDivElement | null>(null)
const svgRef = ref<SVGSVGElement | null>(null)
const cfg = useConfig()
const chartLabel = computed(() => cfg.value.locale?.charts?.lineChart ?? 'Line chart')
const fallbackW = computed(() =>
  typeof props.width === 'number' && Number.isFinite(props.width) ? props.width : 600,
)
const fallbackH = computed(() =>
  typeof props.height === 'number' && Number.isFinite(props.height) ? props.height : 200,
)
const { size } = useChartSize(svgRef, { width: fallbackW.value, height: fallbackH.value })

const bounds = computed(() => chartBounds(props.series.map((s) => s.values)))
const padding = computed(() =>
  resolveChartPadding(props.padding, props.yAxis, bounds.value.min, bounds.value.max),
)
const viewW = computed(() => size.value.width)
const viewH = computed(() => size.value.height)
const plotX = computed(() => padding.value[3])
const plotY = computed(() => padding.value[0])
const plotW = computed(() => Math.max(0, viewW.value - padding.value[3] - padding.value[1]))
const plotH = computed(() => Math.max(0, viewH.value - padding.value[0] - padding.value[2]))
const animation = computed(() => resolveChartAnimation(props.animate))

const xCoord = (i: number) => {
  const n = props.categories.length
  if (n <= 1) return plotX.value
  return plotX.value + (plotW.value * i) / (n - 1)
}

const yCoord = (v: number) => {
  const { min, max } = bounds.value
  if (max === min) return plotY.value + plotH.value / 2
  return plotY.value + plotH.value * (1 - (v - min) / (max - min))
}

const lineSegments = computed(() =>
  props.series.map((s, i) => {
    const color = colorForSeries(s, i)
    const segments: string[] = []
    let current: string[] = []
    s.values.forEach((v, idx) => {
      if (v === null || v === undefined) {
        if (current.length > 0) {
          segments.push(current.join(' '))
          current = []
        }
      } else {
        const cmd = current.length === 0 ? 'M' : 'L'
        current.push(`${cmd}${xCoord(idx)},${yCoord(v)}`)
      }
    })
    if (current.length > 0) segments.push(current.join(' '))
    return { id: s.id, color, label: s.label, segments }
  }),
)

const groupAnimStyle = computed(() =>
  animation.value.enabled
    ? { '--sg-chart-anim-duration': `${animation.value.duration}ms` }
    : undefined,
)
function segmentAnimStyle(segCount: number, segIdx: number) {
  if (!animation.value.enabled) return undefined
  const d = animation.value.duration
  return {
    strokeDasharray: 1,
    strokeDashoffset: 1,
    animationDelay: `${(segIdx / Math.max(1, segCount)) * d}ms`,
    animationDuration: `${d / Math.max(1, segCount)}ms`,
  }
}

const markerPoints = computed(() =>
  props.series.flatMap((s, i) => {
    const color = colorForSeries(s, i)
    return s.values
      .map((v, idx) =>
        v == null ? null : { id: `${s.id}-${idx}`, color, x: xCoord(idx), y: yCoord(v) },
      )
      .filter(Boolean) as { id: string; color: string; x: number; y: number }[]
  }),
)

const crosshairEnabled = computed(() => props.crosshair !== false && props.categories.length > 0)
const crosshairFmt = computed(() =>
  typeof props.crosshair === 'object' && props.crosshair !== null
    ? props.crosshair.valueFormatter
    : undefined,
)
const hoverIdx = ref<number | null>(null)

function handleSvgMouseMove(e: MouseEvent) {
  if (!crosshairEnabled.value) return
  const svg = e.currentTarget as SVGSVGElement
  const rect = svg.getBoundingClientRect()
  if (rect.width === 0) return
  const localX = ((e.clientX - rect.left) / rect.width) * viewW.value
  const n = props.categories.length
  if (n === 1) {
    hoverIdx.value = 0
    return
  }
  const xStep = plotW.value / (n - 1)
  if (xStep <= 0) {
    hoverIdx.value = null
    return
  }
  const rawIdx = Math.round((localX - plotX.value) / xStep)
  if (rawIdx < 0 || rawIdx >= n) {
    hoverIdx.value = null
    return
  }
  hoverIdx.value = rawIdx
}

function handleSvgMouseLeave() {
  if (crosshairEnabled.value) hoverIdx.value = null
}

const crosshairPoints = computed<ChartCrosshairPoint[]>(() => {
  const idx = hoverIdx.value
  if (idx === null) return []
  const out: ChartCrosshairPoint[] = []
  props.series.forEach((s, sIdx) => {
    const v = s.values[idx]
    if (v === null || v === undefined) return
    out.push({
      label: s.label,
      value: v,
      color: colorForSeries(s, sIdx),
      y: yCoord(v),
    })
  })
  return out
})

const brushConfig = computed(() => resolveBrushConfig(props.brush))
const isBrushControlled = computed(() => brushConfig.value != null && 'range' in brushConfig.value)
const internalBrushRange = ref<ChartBrushRange | null>(brushConfig.value?.defaultRange ?? null)
const effectiveBrushRange = computed<ChartBrushRange | null>(() =>
  isBrushControlled.value ? (brushConfig.value!.range ?? null) : internalBrushRange.value,
)
function handleBrushChange(next: ChartBrushRange | null) {
  if (!isBrushControlled.value) internalBrushRange.value = next
  brushConfig.value?.onRangeChange?.(next)
}

defineExpose({
  print: (opts: { fileName?: string } = {}) => {
    const el = rootRef.value
    if (!el) return
    printElement(el, { fileName: opts.fileName ?? props.fileName ?? 'chart' })
  },
  exportSvg: () => {
    const svg = svgRef.value
    if (!svg) return null
    return new XMLSerializer().serializeToString(svg)
  },
})
</script>

<template>
  <div
    ref="rootRef"
    :class="[!props.unstyled && 'sg-chart sg-chart-line', props.className]"
    :style="{
      width: typeof props.width === 'number' ? `${props.width}px` : props.width,
    }"
    :data-animate="animation.enabled ? 'on' : 'off'"
  >
    <svg
      ref="svgRef"
      :viewBox="`0 0 ${viewW} ${viewH}`"
      :width="typeof props.width === 'number' ? props.width : '100%'"
      :height="props.height"
      role="img"
      :aria-label="chartLabel"
      @mousemove="crosshairEnabled ? handleSvgMouseMove($event) : undefined"
      @mouseleave="crosshairEnabled ? handleSvgMouseLeave() : undefined"
    >
      <ChartAxes
        :x="plotX"
        :y="plotY"
        :plotW="plotW"
        :plotH="plotH"
        :categories="props.categories"
        :yMin="bounds.min"
        :yMax="bounds.max"
        :xAxis="props.xAxis"
        :yAxis="props.yAxis"
        :unstyled="props.unstyled"
      />
      <g class="sg-chart-line-paths">
        <template v-for="ln in lineSegments" :key="ln.id">
          <g
            :class="[animation.enabled && !props.unstyled && 'sg-chart-line-animate']"
            :style="groupAnimStyle"
          >
            <path
              v-for="(seg, si) in ln.segments"
              :key="`${ln.id}-${si}`"
              :class="[animation.enabled && !props.unstyled && 'sg-chart-line-segment-animate']"
              :d="seg"
              :stroke="ln.color"
              :stroke-width="props.strokeWidth"
              pathLength="1"
              fill="none"
              vector-effect="non-scaling-stroke"
              :data-series-id="ln.id"
              :style="segmentAnimStyle(ln.segments.length, si)"
            />
          </g>
        </template>
      </g>
      <g v-if="props.markers" class="sg-chart-line-markers">
        <circle v-for="m in markerPoints" :key="m.id" :cx="m.x" :cy="m.y" r="3" :fill="m.color" />
      </g>
      <ChartCrosshair
        v-if="crosshairEnabled && hoverIdx !== null && crosshairPoints.length > 0"
        :x="xCoord(hoverIdx)"
        :plot-x="plotX"
        :plot-y="plotY"
        :plot-h="plotH"
        :plot-w="plotW"
        :category="props.categories[hoverIdx]"
        :points="crosshairPoints"
        :unstyled="props.unstyled"
        :value-formatter="crosshairFmt"
      />
      <ChartBrush
        v-if="brushConfig"
        :plot-x="plotX"
        :plot-y="plotY"
        :plot-w="plotW"
        :plot-h="plotH"
        :category-count="props.categories.length"
        :range="effectiveBrushRange"
        :unstyled="props.unstyled"
        :fill="brushConfig.fill"
        :disabled="brushConfig.disabled"
        @change="handleBrushChange"
      />
    </svg>
    <ChartLegend v-if="props.legend" :series="props.series" :unstyled="props.unstyled" />
  </div>
</template>

// packages/react/src/components/complex/Charts/LineChart.tsx
import { forwardRef, useMemo, useRef, useState, type CSSProperties, type ForwardedRef } from 'react'
import {
  chartBounds,
  chartDataKey,
  colorForSeries,
  resolveChartPadding,
  resolveChartAnimation,
} from './types'
import { ChartLegend } from './ChartLegend'
import { ChartAxes } from './ChartAxes'
import { ChartCrosshair, type ChartCrosshairPoint } from './ChartCrosshair'
import {
  ChartBrush,
  resolveBrushConfig,
  type ChartBrushConfig,
  type ChartBrushRange,
} from './ChartBrush'
import type { BaseChartProps } from './types'
import { useChartPrint, type ChartRef } from './chartRef'
import { useChartSize } from './useChartSize'
import { ChartHoverToolbar, resolveChartActions } from './ChartHoverToolbar'
import { makeChartContextMenuHandler, makeSeriesContextMenuHandler } from './chartContextMenu'
import { useConfig } from '../../ConfigProvider'

/**
 * Crosshair behaviour toggle for {@link LineChart}. When `true`, a vertical
 * guide line + per-series tooltip appears on hover.
 */
export type LineChartCrosshair =
  | boolean
  | {
      /** Custom formatter for tooltip numeric values. */
      valueFormatter?: (value: number) => string
    }

export interface LineChartProps extends BaseChartProps {
  /** Show small dot markers at each data point. @default true */
  markers?: boolean
  /** Stroke width in pixels. @default 2 */
  strokeWidth?: number
  /**
   * Hover crosshair with a vertical guide line and per-series value tooltip.
   * @default false
   */
  crosshair?: LineChartCrosshair
  /**
   * Brush для drag-выбора диапазона по X. `true` — uncontrolled с пустым
   * стартовым значением; объект — `ChartBrushConfig`. См. `ChartBrush`.
   */
  brush?: boolean | ChartBrushConfig
}

/**
 * SVG line chart with optional axes, legend, hover crosshair, and CSS
 * mount / data-change animation. Theming via `--sg-color-*` tokens; line
 * "draw-in" effect uses pure-CSS `stroke-dashoffset` per segment (no rAF).
 *
 * Responsive: SVG `viewBox` пересчитывается в реальные пиксели контейнера
 * через `useChartSize` (ResizeObserver). `preserveAspectRatio` не задан —
 * один CSS-пиксель = один user-space-unit, без растягивания. На stroke-
 * элементах включён `vector-effect="non-scaling-stroke"` — толщина линии
 * стабильна при печати / zoom.
 */
function LineChartInner(
  {
    categories,
    series,
    width = '100%',
    height = 200,
    className,
    style,
    unstyled = false,
    padding,
    markers = true,
    strokeWidth = 2,
    legend = false,
    xAxis,
    yAxis,
    animate,
    crosshair = false,
    brush,
    printable,
    actions,
    fileName,
    onSeriesContextMenu,
    onChartContextMenu,
  }: LineChartProps,
  forwardedRef: ForwardedRef<ChartRef>,
) {
  const chartsLocale = useConfig().locale?.charts
  const { rootRef } = useChartPrint<Element>(forwardedRef, printable)
  const svgRef = useRef<SVGSVGElement | null>(null)

  const { min, max } = useMemo(() => chartBounds(series.map((s) => s.values)), [series])
  const [pt, pr, pb, pl] = useMemo(
    () => resolveChartPadding(padding, yAxis, min, max),
    [padding, yAxis, min, max],
  )

  const fallbackW = typeof width === 'number' && Number.isFinite(width) ? width : 600
  const fallbackH = typeof height === 'number' && Number.isFinite(height) ? height : 200
  const measured = useChartSize<SVGSVGElement>(svgRef, { width: fallbackW, height: fallbackH })
  const viewW = measured.width
  const viewH = measured.height
  const plotW = Math.max(0, viewW - pl - pr)
  const plotH = Math.max(0, viewH - pt - pb)

  const range = max - min || 1
  const xStep = categories.length > 1 ? plotW / (categories.length - 1) : 0

  function xFor(i: number) {
    return pl + i * xStep
  }
  function yFor(v: number) {
    return pt + (1 - (v - min) / range) * plotH
  }

  const wrapperClass = unstyled
    ? className
    : ['sg-chart', 'sg-chart-line', className].filter(Boolean).join(' ')

  const anim = resolveChartAnimation(animate)
  const animKey = useMemo(
    () => chartDataKey([categories, series.map((s) => s.values)]),
    [categories, series],
  )
  const animStyle: CSSProperties | undefined = anim.enabled
    ? ({ ['--sg-chart-anim-duration' as string]: `${anim.duration}ms` } as CSSProperties)
    : undefined
  const animClass = anim.enabled && !unstyled ? 'sg-chart-line-animate' : undefined

  const crosshairEnabled = crosshair !== false && categories.length > 0
  const crosshairFmt =
    typeof crosshair === 'object' && crosshair !== null ? crosshair.valueFormatter : undefined
  const [hoverIdx, setHoverIdx] = useState<number | null>(null)

  const brushConfig = resolveBrushConfig(brush)
  const isBrushControlled = brushConfig != null && 'range' in brushConfig
  const [internalBrushRange, setInternalBrushRange] = useState<ChartBrushRange | null>(
    brushConfig?.defaultRange ?? null,
  )
  const effectiveBrushRange = isBrushControlled ? (brushConfig!.range ?? null) : internalBrushRange
  const handleBrushChange = (next: ChartBrushRange | null) => {
    if (!isBrushControlled) setInternalBrushRange(next)
    brushConfig?.onRangeChange?.(next)
  }

  const handleMouseMove = (e: React.MouseEvent<SVGSVGElement>) => {
    if (!crosshairEnabled) return
    const svg = e.currentTarget
    const rect = svg.getBoundingClientRect()
    if (rect.width === 0) return
    const localX = ((e.clientX - rect.left) / rect.width) * viewW
    if (categories.length === 1) {
      setHoverIdx(localX >= pl - xStep / 2 && localX <= pl + xStep / 2 + plotW ? 0 : null)
      return
    }
    const rawIdx = Math.round((localX - pl) / xStep)
    if (rawIdx < 0 || rawIdx >= categories.length) {
      setHoverIdx(null)
      return
    }
    setHoverIdx(rawIdx)
  }

  const handleMouseLeave = () => {
    if (crosshairEnabled) setHoverIdx(null)
  }

  const crosshairPoints: ChartCrosshairPoint[] = useMemo(() => {
    if (hoverIdx === null) return []
    const out: ChartCrosshairPoint[] = []
    series.forEach((s, sIdx) => {
      const v = s.values[hoverIdx]
      if (v === null || v === undefined) return
      out.push({
        label: s.label,
        value: v,
        color: colorForSeries(s, sIdx),
        y: pt + (1 - (v - min) / range) * plotH,
      })
    })
    return out
  }, [hoverIdx, series, pt, plotH, min, range])

  // ─── toolbar / context menu wiring ──────────────────────────────────
  const brushReset = brushConfig
    ? () => {
        if (!isBrushControlled) setInternalBrushRange(null)
        brushConfig.onRangeChange?.(null)
      }
    : undefined
  const resolvedActions = resolveChartActions(actions, { fileName, brushReset })
  const [toolbarVisible, setToolbarVisible] = useState(false)
  const handleSvgContextMenu = makeChartContextMenuHandler(onChartContextMenu)

  const setSvgRef = (el: SVGSVGElement | null) => {
    svgRef.current = el
    if (!legend) (rootRef as React.MutableRefObject<Element | null>).current = el
  }

  const svg = (
    <svg
      ref={setSvgRef}
      className={wrapperClass}
      style={legend || resolvedActions ? undefined : style}
      width={width}
      height={height}
      viewBox={`0 0 ${viewW} ${viewH}`}
      role="img"
      aria-label={chartsLocale?.lineChart ?? 'Line chart'}
      onMouseMove={crosshairEnabled ? handleMouseMove : undefined}
      onMouseLeave={crosshairEnabled ? handleMouseLeave : undefined}
      onContextMenu={handleSvgContextMenu}
    >
      <ChartAxes
        plotX={pl}
        plotY={pt}
        plotW={plotW}
        plotH={plotH}
        min={min}
        max={max}
        categories={categories}
        xAxis={xAxis}
        yAxis={yAxis}
        unstyled={unstyled}
      />
      {series.map((s, sIdx) => {
        const stroke = colorForSeries(s, sIdx)
        const segments: { from: [number, number]; to: [number, number]; valueIndex: number }[] = []
        let prev: { pt: [number, number]; idx: number } | null = null
        s.values.forEach((v, i) => {
          if (v === null || v === undefined) {
            prev = null
            return
          }
          const point: [number, number] = [xFor(i), yFor(v)]
          if (prev) segments.push({ from: prev.pt, to: point, valueIndex: i })
          prev = { pt: point, idx: i }
        })
        const segCount = segments.length
        return (
          <g key={`${s.id}-${animKey}`} className={animClass} style={animStyle}>
            {segments.map((seg, segIdx) => {
              const len = Math.hypot(seg.to[0] - seg.from[0], seg.to[1] - seg.from[1])
              const segStyle: CSSProperties | undefined = anim.enabled
                ? {
                    strokeDasharray: len,
                    strokeDashoffset: len,
                    animationDelay: `${(segIdx / Math.max(1, segCount)) * anim.duration}ms`,
                    animationDuration: `${anim.duration / Math.max(1, segCount)}ms`,
                  }
                : undefined
              return (
                <line
                  key={segIdx}
                  className={
                    anim.enabled && !unstyled ? 'sg-chart-line-segment-animate' : undefined
                  }
                  x1={seg.from[0]}
                  y1={seg.from[1]}
                  x2={seg.to[0]}
                  y2={seg.to[1]}
                  stroke={stroke}
                  strokeWidth={strokeWidth}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  fill="none"
                  vectorEffect="non-scaling-stroke"
                  style={segStyle}
                  onContextMenu={makeSeriesContextMenuHandler(onSeriesContextMenu, {
                    seriesId: s.id,
                    seriesIndex: sIdx,
                    valueIndex: seg.valueIndex,
                    value: s.values[seg.valueIndex] ?? undefined,
                  })}
                />
              )
            })}
            {markers &&
              s.values.map((v, i) => {
                if (v === null || v === undefined) return null
                return (
                  <circle
                    key={i}
                    cx={xFor(i)}
                    cy={yFor(v)}
                    r={Math.max(2, strokeWidth)}
                    fill={stroke}
                    onContextMenu={makeSeriesContextMenuHandler(onSeriesContextMenu, {
                      seriesId: s.id,
                      seriesIndex: sIdx,
                      valueIndex: i,
                      value: v,
                    })}
                  >
                    <title>{`${s.label} · ${categories[i]}: ${v}`}</title>
                  </circle>
                )
              })}
          </g>
        )
      })}
      {crosshairEnabled && hoverIdx !== null && crosshairPoints.length > 0 && (
        <ChartCrosshair
          x={xFor(hoverIdx)}
          plotX={pl}
          plotY={pt}
          plotH={plotH}
          plotW={plotW}
          category={categories[hoverIdx]!}
          points={crosshairPoints}
          unstyled={unstyled}
          valueFormatter={crosshairFmt}
        />
      )}
      {brushConfig && (
        <ChartBrush
          plotX={pl}
          plotY={pt}
          plotW={plotW}
          plotH={plotH}
          categoryCount={categories.length}
          range={effectiveBrushRange}
          onRangeChange={handleBrushChange}
          unstyled={unstyled}
          fill={brushConfig.fill}
          disabled={brushConfig.disabled}
        />
      )}
    </svg>
  )

  const needsWrapper = legend || !!resolvedActions
  if (!needsWrapper) return svg

  return (
    <div
      ref={legend ? (rootRef as React.RefObject<HTMLDivElement>) : undefined}
      className={unstyled ? undefined : 'sg-chart-wrapper'}
      style={style}
      onMouseEnter={resolvedActions ? () => setToolbarVisible(true) : undefined}
      onMouseLeave={resolvedActions ? () => setToolbarVisible(false) : undefined}
      onFocus={resolvedActions ? () => setToolbarVisible(true) : undefined}
      onBlur={resolvedActions ? () => setToolbarVisible(false) : undefined}
    >
      {resolvedActions && (
        <ChartHoverToolbar
          visible={toolbarVisible}
          actions={resolvedActions}
          fileName={fileName}
          getSvg={() => svgRef.current}
          brushReset={brushReset}
          unstyled={unstyled}
        />
      )}
      {svg}
      {legend && <ChartLegend series={series} />}
    </div>
  )
}

export const LineChart = forwardRef<ChartRef, LineChartProps>(LineChartInner)
LineChart.displayName = 'LineChart'
